### ISSUE TITLE
The search_genes.py script is called twice when a permalink is used.

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#107]
Example:

http://localhost/index.html?layout_id=e237084e&gene_symbol=Sox2&gene_symbol_exact_match=1&gene_cart_share_id=undefined&multigene_plots=NaN

This is significant especially when a gene cart is used as those queries can take some time already - doubling them is no bueno.

**Comment by adkinsrs** [comment]
I may need to dbl-check this because when I wrote the projection code (before splitting it off of index.html), I did some refactoring and this may be one of the things I refactored.

**Comment by adkinsrs** [comment]
Outdated due to v2
