### ISSUE TITLE
headers that can be used for comparison tool

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#11]
the group displayed for the comparison tool is too complicated

![Screen Shot 2021-07-20 at 11 42 03 AM](https://user-images.githubusercontent.com/6730079/126355078-9e86ce89-24b1-4c28-9501-02841f92b804.png)

the header for the dataset is:

observations    group   cell_type       cell_type_colors        UMAP_1  UMAP_2  cluster_label

how to display the cell_type and group only?

**Comment by jorvis** [comment]
This shows the list of column names which are currently skipped.  Any other names get to be part of the condition generation:

https://github.com/IGS/gEAR/blob/master/www/cgi/get_condition_list.cgi#L54

**Comment by jorvis** [comment]
Updated the code to include these column variations.  Please try again.

**Comment by songeric1107** [comment]
@jorvis 

I could not select the significant test, is it because of no "replicates" column in the observation.tab file?

In that case, how the dataset is grouped into different cell types?

![Screen Shot 2021-07-20 at 2 12 11 PM](https://user-images.githubusercontent.com/6730079/126374510-18796471-7984-4d88-8e95-a08ea49c0d14.png)

**Comment by jorvis** [comment]
Are you sure the colors column was called 'cell_type_colors' exactly?  They shouldn't still be appearing.

And, yes, the stats tests can't be enabled if there aren't replicates.  And they're grouped into cell types using the column in the dataset called 'cell_type'.

**Comment by songeric1107** [comment]
this is the header of the observation.tab file

observations group cell_type group_colors UMAP_1 UMAP_2 cluster_label


If I modified the observation file by adding the replicates column, will it
breaks the primary analysis function that you did in the morning?

**Comment by songeric1107** [comment]
could you please add group_colors to the "skip_column"?

**Comment by jorvis** [comment]
I've added group_colors.  And as long as you don't change any other headers in the file it shouldn't matter if you add replicates.

**Comment by songeric1107** [comment]
@jorvis 

I create a testing dataset using the same matrix for the comparison tool, however, I got errors when I comparing clusters between different condition


![Screen Shot 2021-07-20 at 3 05 33 PM](https://user-images.githubusercontent.com/6730079/126381354-5e2d3b7d-f96b-4a07-80c1-aa5fb4fc8c88.png)


here is the dataset ID 

103a7817-e806-2f16-8c6b-eee88b6467de

**Comment by songeric1107** [comment]
relate to ticket #12

**Comment by adkinsrs** [comment]
```python
 /opt/Python-3.7.3/bin/python3 /home/jorvis/git/gEAR/www/cgi/get_dataset_comparison.cgi "dataset1_id=719efce0-307e-a719-fcd8-e57adebbfe24&dataset1_condition=Ctrl%3Bcluster_3%3BMacrophage%3BCtrl_cluster_3&dataset2_condition=Implanted%3Bcluster_1%3BMacrophage%3BImplanted_cluster_1&fold_change_cutoff=1&std_dev_num_cutoff=0&log_transformation=2&statistical_test=wilcoxon"
Traceback (most recent call last):
  File "/home/jorvis/git/gEAR/www/cgi/get_dataset_comparison.cgi", line 402, in <module>
    main()
  File "/home/jorvis/git/gEAR/www/cgi/get_dataset_comparison.cgi", line 203, in main
    sc.tl.rank_genes_groups(adata, 'comparison_composite_index', use_raw=True, groups=[condition1], reference=condition2, n_genes=0, rankby_abs=False, copy=False, method=statistical_test, corr_method='benjamini-hochberg', log_transformed=False)
  File "/opt/Python-3.7.3/lib/python3.7/site-packages/scanpy/tools/_rank_genes_groups.py", line 140, in rank_genes_groups
    and reference not in set(adata.obs[groupby].cat.categories)
  File "/opt/Python-3.7.3/lib/python3.7/site-packages/pandas/core/generic.py", line 5270, in __getattr__
    return object.__getattribute__(self, name)
  File "/opt/Python-3.7.3/lib/python3.7/site-packages/pandas/core/accessor.py", line 187, in __get__
    accessor_obj = self._accessor(obj)
  File "/opt/Python-3.7.3/lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 2534, in __init__
    self._validate(data)
  File "/opt/Python-3.7.3/lib/python3.7/site-packages/pandas/core/arrays/categorical.py", line 2543, in _validate
    raise AttributeError("Can only use .cat accessor with a 'category' dtype")
AttributeError: Can only use .cat accessor with a 'category' dtype
```

I'm am attempting to replicate up to this point in the python REPL.  A quick glance tells me that the used observation columns are of the "category" dtype, so I believe something may be up with the comparison_composite_index that is created.

**Comment by adkinsrs** [comment]
Turns out that 'cluster_colors', 'UMAP_1', 'UMAP_2' were added as columns to ignore in "get_condition_list.cgi" (which populates the dropdowns on the page) but not in "get_dataset_comparison.cgi" (which does the actual comparison), so scanp y was using a bad comparison_composite_index.

I fixed this directly in the production get_dataset_comparison.cgi script and was able to generate a plot.  I am about to make the same change in the commited code soon.

**Comment by adkinsrs** [comment]
Commited https://github.com/IGS/gEAR/commit/1bece38686d38ddf142887e27930ff79e412d462

**Comment by jorvis** [comment]
Nice catch there.

**Comment by jorvis** [comment]
Closing because I believe this issue has been addressed.
