### ISSUE TITLE
Multigene Curator - KeyError "index" on Dot Plot

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#112]
This "index" error is actually the Ensembl IDs under a category called "index" after some conversion to a dataframe.  Observed this when Ronna was walking me through her steps of using the multigene curator.  Need to replicate this and test.

**Comment by adkinsrs** [comment]
After seeing this in GCID as well, I concluded that some datasets have an "ensembl_ID" field column in adata.var for the Ensemble ID whereas others have "index" instead.  My test dataset used "index" so I wrote the code based on this.  I'm unsure if there was a change in how uploads were handled and converted to h5ad but I think it will be good to account for both conditions.  Or I just need to force that column to be called "index" when processing data.

**Comment by jorvis** [comment]
You might get clarification from Yang on how these were loaded.  There's the uploader UI and we have some conversion scripts to H5 for very old datasets - it might be these that she used.

**Comment by adkinsrs** [comment]
I've been in contact.  I was using a Kelley dataset as my test dataset, but Yang uploads everything modern using "ensembl_ID".

**Comment by adkinsrs** [comment]
I just found another dataset on the GCID portal that used a different field name, "Ensembl_ID".  So I am concerned about the uniformity of the uploaded datasets, and potentially encountering a fourth or fifth variation and so on.

**Comment by songeric1107** [comment]
which one is it? I can change it.

**Comment by adkinsrs** [comment]
Pushed a commit to resolve this.  By using `adata.var.index.name` I can grab the gene index name no matter what it's called.
