### ISSUE TITLE
Put gene count warnings on multigene display configurations

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#118]
When the user selects a multi-gene view the API call should check how many genes are in the cart and report a warning or maybe even exportable image.

**Comment by adkinsrs** [comment]
Extending this to observation count warnings too.  Recently encountered a heatmap issue where the dendrogram creation failed due to exceeding the max recursion depth.  This was because of the high number of observations.

**Comment by adkinsrs** [comment]
Committed.

Right now a warning goes up if more than 10 genes are added.  An "observation warning goes up if the user attempts to cluster heatmaps with more than 1000 observations.  I have had success with 1000 but I was not sure where the lower bounds was for the recursion depth failure.
