### ISSUE TITLE
comparison tool does not work for scRNA matrix

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#12]
The comparison tool does not work with scRNAmatrix to compare between groups for each cluster, no matter how I change the parameter.

07ba8ae9-f57e-9bb3-262c-9ba9151fe78c

here is the header of observation.tab

observations	UMAP_1	UMAP_2	replicate	group_cluster

![Screen Shot 2021-07-20 at 6 40 45 PM](https://user-images.githubusercontent.com/6730079/126404630-674b7898-826f-4473-9b02-b4faf7b24d04.png)

**Comment by songeric1107** [comment]
relate to ticket #11

**Comment by jorvis** [comment]
Closing this ticket because the issue raised in it was resolved.  Remaining problem is in ticket 11.
