### ISSUE TITLE
update symbols for funding sources on front page

### ISSUE THREAD

**Issue by RLC-DCPPC** [IGS/gEAR#121]

**Comment by jorvis** [comment]
Logos attached.
![hrp](https://user-images.githubusercontent.com/330899/145093841-1889771a-8010-4e80-90c9-e645bc1a790b.png)
![hearing_health_foundation](https://user-images.githubusercontent.com/330899/145093843-07394ee6-e27e-4993-a1e1-0b7d3325389b.png)

**Comment by jorvis** [comment]
In commit ce80cbd I've added this additional image.

![Screenshot from 2021-12-13 23-00-29](https://user-images.githubusercontent.com/330899/145936226-6773a743-c650-4d47-a981-9cb9ec3d4533.png)
