### ISSUE TITLE
define a specific color for the gene with no expression range(all 0) in svg /tsne plot

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#13]
Should we define a specific color (eg. grey) for a gene with all 0 across all samples or cell types?
A similar problem was observed in TSNE plot which was generated by scanpy.

![svg](https://user-images.githubusercontent.com/6730079/126547739-fe67aa0a-e4d7-41b3-aed7-d67a28e404e0.png)

**Comment by adkinsrs** [comment]
Currently grey is the 0.0 value for the "split by group" plots, but I can modify the code to add grey for the single gene expression plot as well.

**Comment by adkinsrs** [comment]
addressed with commit 479d272.  Will need to verify in gear-devel.

**Comment by adkinsrs** [comment]
<img width="1159" alt="Screen Shot 2021-09-30 at 1 57 43 PM" src="https://user-images.githubusercontent.com/5665914/135506864-aa4a39ea-9864-412a-8dc8-e9ba657f4a4d.png">

@songeric1107 this is the picture of the dataset from above using "sox2" as the gene.  Is this fine?  Looks like a lot of gray 0-expression cells.

**Comment by adkinsrs** [comment]
@songeric1107 mentioned this looked fine (though Sox2 is a bad example since there is virtually no expression in this dataset).  I tested using Malat1 as well, since it is expressed in the majority of cells, and things looked fine.  Closing for now

**Comment by adkinsrs** [comment]
@songeric1107 said this looks fine.  I also tested with Malat1, which has expression in most of the cells as well.  I've closed the ticket since this is deployed on devel, but feel free to reopen if there is contention with this change.
