### ISSUE TITLE
grid on the background of the image

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#131]
![Screen Shot 2021-12-08 at 11 32 53 AM](https://user-images.githubusercontent.com/6730079/145246578-5d33a2ce-e3d7-426b-bb3c-ae2f6eee80b0.png)

https://umgear.org/index.html?layout_id=ced52fd5&gene_symbol=sox2&gene_symbol_exact_match=0&gene_cart_share_id=undefined&multigene_plots=NaN

**Comment by adkinsrs** [comment]
@songeric1107 I clicked the link, and the 2 tSNE graphs look fine (without the grid in the background).  Furthermore I do not see this "induced" dataset in this profile that you linked.

**Comment by adkinsrs** [comment]
closing this ticket... feel free to reopen if this is still an issue
