### ISSUE TITLE
Ability to reorder genes in multigene curator

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#144]
In the multigene curator, it would be helpful if there was an ability to sort genes similar to the sorting option used for primary and secondary categories. Currently, how the order of genes are displayed differs between plot type. In the example below, genes in the heatmap are displayed in order of being added but genes in violin plots are alphabetical.

<img width="644" alt="Screen Shot 2022-01-04 at 11 27 21 AM" src="https://user-images.githubusercontent.com/28451557/148091407-7ab21775-ddce-4431-b0fb-07663b79be19.png">

**Comment by adkinsrs** [comment]
I think they should all be alphabetical by default, unless in situations where the user selects to cluster the genes in heatmaps.  That is an easy adjustment.  However, I don't think implementing the same vertical "sort order" element in the gene selection step would look very good considering the number of potential genes.

So I think I will work to ensure heatmaps, dotplots, and violins all use alphabetical order by default.  Any objections to this?

**Comment by JPReceveur** [comment]
That makes sense and sounds good to me.

**Comment by adkinsrs** [comment]
Complete.  Opening a new ticket for testing purposes
