### ISSUE TITLE
changes  of GCID portal

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#148]
- [x]  replace the dataset that links to http://gcid.igs.umaryland.edu/pub/wb-RNA-life with https://gcid.umgear.org/p?s=2160d42b.

- [x] replace the dataset that links to http://gcid.igs.umaryland.edu/pub/bm-RNA-life with https://gcid.umgear.org/p?s=73bee4b5.

- [x] remove "Multi-species transcriptomics data set of Brugia malayi across its entire lifecycle - Aedes aegypti - z score of log2(TPM)-multigene (V2) (https://gcid.umgear.org/p?s=ee063942)" from Aedes_aegypti_update profile:https://gcid.umgear.org/p?l=d25e02e9

- [x] change all the window sizes to 3 panels for this profile:
 https://gcid.umgear.org/p?l=87817322

- [x] remove all the datasets which are not tagged with V2 from Brugia_malayi(public)
 https://gcid.umgear.org/p?l=4a49270d

- [x] remove "Brugia malayi - z-score of the log2(TPM) values,V2 (https://gcid.umgear.org/p?s=bfca6a19)" from Brugia_malayi(public) profile
 https://gcid.umgear.org/p?l=4a49270d

**Comment by adkinsrs** [comment]
- [ ] replace the dataset that links to http://gcid.igs.umaryland.edu/pub/wb-RNA-life with https://gcid.umgear.org/p?s=2160d42b.

- [ ] replace the dataset that links to http://gcid.igs.umaryland.edu/pub/bm-RNA-life with https://gcid.umgear.org/p?s=73bee4b5.

- [ ] remove "Multi-species transcriptomics data set of Brugia malayi across its entire lifecycle - Aedes aegypti - z score of log2(TPM)-multigene (V2) (https://gcid.umgear.org/p?s=ee063942)" from Aedes_aegypti_update profile:https://gcid.umgear.org/p?l=d25e02e9

- [ ] change all the window sizes to 3 panels for this profile:
https://gcid.umgear.org/p?l=87817322

- [ ] remove all the datasets which are not tagged with V2 from Brugia_malayi(public)
https://gcid.umgear.org/p?l=4a49270d

- [ ] remove "Brugia malayi - z-score of the log2(TPM) values,V2 (https://gcid.umgear.org/p?s=bfca6a19)" from Brugia_malayi(public) profile
https://gcid.umgear.org/p?l=4a49270d

**Comment by adkinsrs** [comment]
Updated the GCID publication links on the internal GCID repository and used the webdeploy tool to update the production version of the site.  However it appears the updated publication URLs do not redirect to the new links yet.  Can @victor73 give an explanation perhaps?

**Comment by adkinsrs** [comment]
@songeric1107 I made all the edits.  Please confirm if these are acceptable.
