### ISSUE TITLE
add the function to select the entire row by clicking the row index (Primary analysis)

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#151]
could we add the function to be able to select the entire row by just clicking the row index ? it will be so useful for the datasets with a lot of cell types under different conditions. 

https://umgear.org/analyze_dataset.html?dataset_id=80eadbe6-49ac-8eaf-f2fb-e07706cf117b

![Screen Shot 2022-01-07 at 9 11 46 AM](https://user-images.githubusercontent.com/6730079/148555944-c915a01c-4541-453c-ad9a-cfa9d66a78e9.png)

**Comment by adkinsrs** [comment]
Added this.  Feel free to test @songeric1107 and @JPReceveur in the analysis workbench -> Find Marker Genes step.

**Comment by adkinsrs** [comment]
Thanks for the heads up.  I'll investigate further

**Comment by adkinsrs** [comment]
@JPReceveur believe I have resolved the issue (unnecessary brackets somewhere in the code).  Care to test again?

**Comment by JPReceveur** [comment]
@adkinsrs Issue with the error message is resolved. When clicking around, I noticed that if you click on the column numbers 0,1,2,3 etc, it adds to the gene counter, causing the number of highlighted genes to be off by one. 
<img width="493" alt="Screen Shot 2022-01-10 at 3 11 53 PM" src="https://user-images.githubusercontent.com/28451557/148833086-5405ee41-ae35-47be-abfa-8ff86d2bffdd.png">

And that number stays even after deselecting all the highlighted genes. 


<img width="375" alt="Screen Shot 2022-01-10 at 3 13 18 PM" src="https://user-images.githubusercontent.com/28451557/148833135-a869d28f-8cd9-47d0-9b0d-aa23a93a84e1.png">


.

**Comment by adkinsrs** [comment]
I've noticed in some cases that it counts "" as a gene.  No clue why but my next step will be to filter that out after every click.

**Comment by songeric1107** [comment]
@adkinsrs I still got the same error
![Screen Shot 2022-01-10 at 3 28 30 PM](https://user-images.githubusercontent.com/6730079/148834664-9361e32f-e6d4-49ce-ab95-0fb516b6200f.png)
.

**Comment by adkinsrs** [comment]
@songeric1107 is this from a fresh analysis or a saved one?  So far I have only been testing with new analyses.

**Comment by songeric1107** [comment]
it is a processed dataset with umap coordinate already, Josh add the primary analysis component to the dataset and I run "Find marker genes" step.

**Comment by adkinsrs** [comment]
@songeric1107 what dataset specifically were you using? I am wondering if you are actually running into a dataset-specific error.

I tested with "Single-cell RNA-Seq of cisplatin-treated adult stria vascularis identifies cell type-specific regulatory networks and novel therapeutic gene targets(Dr.Michael Hoa)" in the curator-only datasets, and used the Primary Analysis and was able to get the marker genes plots and table.

**Comment by songeric1107** [comment]
I am using this one. https://devel.umgear.org/dataset_curator.html#/dataset/943c3b03-fb83-c69a-3cfa-d8a6b98c02fd/displays

**Comment by adkinsrs** [comment]
@songeric1107 I checked the error logs, and the error I see for that dataset is that the louvain analysis results are not present.  I would recommend rerunning this analysis.

@JPReceveur if you think the testing looks good, I will close the ticket.

**Comment by JPReceveur** [comment]
@adkinsrs Just gave it a final look, testing looks good and no other bugs noticed.
