### ISSUE TITLE
Fix false logged out display on dataset curator page

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#154]
Moving https://github.com/jorvis/gEAR/issues/827 to here

**Comment by adkinsrs** [comment]
Addressed with commit b629da2

**Comment by adkinsrs** [comment]
I know @songeric1107 has observed this, so can you and @JPReceveur test this.

Go to the dataset curator on gear-devel using any dataset from the gene search results (click the dropdown, then Curate).  In the past, if you navigated to that URL from another tab or window, the login section of the page would show that you are not logged in when you really were.  You should not see a log-in section unless you are truly logged out.

**Comment by JPReceveur** [comment]
Tested on devel, observed same issue. Issue changes name to 'user' and login box reappears.

Login status on gene search page:
<img width="1538" alt="Screen Shot 2022-01-18 at 2 08 59 PM" src="https://user-images.githubusercontent.com/28451557/150002885-c0e3ced9-eb09-4db8-a4a9-7d5e93b92789.png">

After clicking on curate:
<img width="1792" alt="Screen Shot 2022-01-18 at 2 08 21 PM" src="https://user-images.githubusercontent.com/28451557/150002897-cb013faa-2dbe-4547-ba44-b776f88d0445.png">

**Comment by adkinsrs** [comment]
Would a refresh on the dataset curator page result in the same thing?  I'm having a gut feeling some stuff is cached in the browser for a few of these tasks.

**Comment by adkinsrs** [comment]
I did find two separate issues though, that I'll tack onto this ticket

- [ ] Logging out from within the dataset curator page navigates you to https://devel.umgear.org/dataset_curator.html#/ whether you had a dataset display passed in the URL query parameters or not.  It does not log you out however
- [ ] While logged out, navigating to https://devel.umgear.org/dataset_curator.html and logging in from there runs a "GET" request somewhere that passes all the "login" parameters into the URL, which is a huge security risk

**Comment by adkinsrs** [comment]
Resolved those two above issues.  Having the navigation bar elements within the Vue app breaks some jQuery event handler declarations since Vue does some injection stuff for it's "app".

**Comment by JPReceveur** [comment]
Just reset cache and tried this again. Still same outcome. Also opening the single cell workbench resulted in the false logout showing up.
<img width="1448" alt="Screen Shot 2022-01-19 at 3 00 30 PM" src="https://user-images.githubusercontent.com/28451557/150205180-e9c621dc-0922-41b9-a91a-fa0957dfbc10.png">

<img width="1485" alt="Screen Shot 2022-01-19 at 3 00 57 PM" src="https://user-images.githubusercontent.com/28451557/150205186-4a044188-c93c-4540-9ffe-b57fdd3db039.png">

**Comment by Kvnrose** [comment]
Navigating from the homepage to the curator does not cause a false logout for me when going to the curator or single cell workbench.

![image](https://user-images.githubusercontent.com/46610614/150551282-642dde88-a345-4bd7-bae3-5db86c70f7e5.png)

![image](https://user-images.githubusercontent.com/46610614/150551350-09b5de17-d75d-496a-95b0-0e77d2f2dc2e.png)


Google Chrome version:
![image](https://user-images.githubusercontent.com/46610614/150551468-4cc8a76f-0ac5-4d09-b6e2-af05aa451426.png)

Interestingly, I tried the same thing on the live gEAR website, and I did not have this issue either.

**Comment by adkinsrs** [comment]
Cool.  I'm going to close this ticket for now.
