### ISSUE TITLE
Update "get_user_gene_carts.cgi" to support public gene carts

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#156]
Currently it seems this script only handles private gene carts (where a user_id is passed in). I can update the index and multigene curator JS pages to handle public gene carts, but the CGI script will need to output them as well.

**Comment by adkinsrs** [comment]
Did brief work on this 981bb40
 for the "new_mg_plots" branch.

**Comment by adkinsrs** [comment]
@jorvis can this be closed?

**Comment by jorvis** [comment]
Yep
