### ISSUE TITLE
Multigene curator - Adjust volcano plot when non-expressed data is in play

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#161]
For a lot of datasets, the volcano plot looks very thin with some extreme outliers as shown below:

<img width="1431" alt="Screen Shot 2022-01-13 at 11 47 08 AM" src="https://user-images.githubusercontent.com/5665914/149372864-7f0c6a9d-8cbc-4081-8def-3b1bfcb23057.png">

When you zoom into a respectable logfoldchange range, the actual plot starts to become more apparent:

<img width="1438" alt="Screen Shot 2022-01-13 at 11 47 52 AM" src="https://user-images.githubusercontent.com/5665914/149373077-bac3f398-fd01-487d-a467-85d02975aad2.png">

I did some digging around and found that for some genes, they have no expression for a particular group for any observations. The "diffxpy" package will attempt to coax their mean expression from 0 to the smallest non-zero floating point number it can, which can lead to some crazy high logfoldchange values.

What I plan to do is pre-check genes for no expression in at least one group (for volcano plots and quadrant plots), and not plot that gene.  If the user requested it be included in annotation, then I will add a note that this gene has no expression in at least one comparison group.

**Comment by adkinsrs** [comment]
<img width="1430" alt="Screen Shot 2022-01-13 at 3 31 03 PM" src="https://user-images.githubusercontent.com/5665914/149404657-36b4e391-a33e-4089-a212-802af702bb49.png">

Added +1 counts to all raw values, and if the original data was non-expressed, then the log-mean would then still end up being 0. I worked on these adjustments for all plots.

**Comment by adkinsrs** [comment]
@songeric1107 @JPReceveur

Can you create a volcano or quadrant plot in the multigene curator on gear-devel and ensure it does not look like the first picture. Ideally the first picture (3 vertical lines) occurs when there are genes that are completely not expressed in one group or the other group. @songeric1107 may know of a good representative dataset.

**Comment by JPReceveur** [comment]
Tested volcano and quadrant plots for a couple random datasets, all plots looked normal. Know of any specific datasets that would be good to test?

**Comment by adkinsrs** [comment]
The test dataset I used was "P7-adult, mouse, RNA-seq, medial geniculate and primary auditory cortex (A1) (Hackett)" where a gene such as Mup5 was present in the A1 group by was not expressed in MG.  But this sort of show bias by pointing you to something I was using to address the issue.  I feel @songeric1107 or Kevin would know some datasets with similar things.

**Comment by adkinsrs** [comment]
Closing for now.  If there are still issues, feel free to reopen

**Comment by Kvnrose** [comment]
Testing:

Volcano plots are working as intended all datasets I have tested.

![image](https://user-images.githubusercontent.com/46610614/150380494-725251af-14e8-4356-b398-b4257ca8e55e.png)

I have two suggestions:

1) I would like to be able to test 1 condition against all other conditions. For example, the volcano plot above is Type1 vs Type3.  It would be more informative for me to have Type1 vs All other types (Type2, Type3, and Type4).
2) I would like to change the fold change and pvalue cutoffs in the plot.

**Comment by adkinsrs** [comment]
For suggestion 1, are you suggesting a union of the rest of the types, or 3 separate volcano plots for the each type-vs-type comparison?  If it is the latter, this may take a bit more work since Dash.Bio's volcano plot function does not play nice with Plotly's subplotting functions

For suggestion 2, that is easily implementable.  I assume you are going to implement the p-value cutoff in scientific notation, right?

**Comment by adkinsrs** [comment]
Ok.  When I do the task, I'll mark this as closed, and create a new ticket for testing and assign you and a couple others to take a look.
