### ISSUE TITLE
enlarge the icon of funding resources (from Ronna)

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#162]
Josh

could you please make the 3rd icon (hearing health) larger to match the same size as other icons?
![Screen Shot 2022-01-14 at 8 55 54 AM](https://user-images.githubusercontent.com/6730079/149526839-4f216ab7-6ebb-489b-b00d-ee153d3cb350.png)

**Comment by jorvis** [comment]
They are all the same size now (on next server update):

![Screenshot from 2022-01-18 13-11-35](https://user-images.githubusercontent.com/330899/150003060-b7120de1-2859-4d7a-b698-338cfef3a78a.png)
