### ISSUE TITLE
modified the svg display for PTS-NIHL dataset

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#17]
![Screen Shot 2021-08-11 at 1 59 23 PM](https://user-images.githubusercontent.com/6730079/129079772-483df39e-bd45-4f66-9d0b-2192c9d15315.png)

https://umgear.org/p?l=76ae3595

![Screen Shot 2021-08-11 at 2 00 19 PM](https://user-images.githubusercontent.com/6730079/129079884-cfb0768b-5f51-424d-968e-536989ebb3dd.png)

modification requested:

If at 24 hours the expression went up - then color only genes that at 24h their value is >0 for enrichment in the sc svg profile
If at 24 hours the expression went down - then color only genes that at baseline their value is >0 for enrichment in the sc svg profile

**Comment by songeric1107** [comment]
the only problem is the color for all zero value, we should set up a defined color for all zero values

**Comment by songeric1107** [comment]
replace the zero with -0.012345679104328156, now the all zero values are displayed as grey.

but there is another problem, how to set up the middle point / zero value as white.

![Screen Shot 2021-08-12 at 11 32 59 AM](https://user-images.githubusercontent.com/6730079/129225942-7966de1b-e7bf-4bbd-b478-275c65f757f1.png)

**Comment by songeric1107** [comment]
the solution is for any genes should be displayed,  put this value in them:
-0.012345679104328156

**Comment by songeric1107** [comment]
**test "ngfr" :**


![Screen Shot 2021-08-16 at 2 14 44 PM](https://user-images.githubusercontent.com/6730079/129611515-c1eeb546-78c9-47d0-bdbe-12d43ea3cd9e.png)

**Comment by songeric1107** [comment]
@jorvis , I have made the changes corresponding to what Ronna suggested during the meeting.

now the problem is how to set color of zero as white.


using "ngfr" as an example, the left image of the second row is the original display, the v4 is the current display, the difference is the color for zero


gene | OHC | SC | T1A | T1B | T1C | T2 | Glia | MC | ImC | BC | FC | SpRC | Mono | BCell | Nphil
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ngfr_orig | -0.51 | 1.11 | -0.3958327 | -0.160827 | -0.0402576 | -0.8301972 | -0.0123457 | -0.0123457 | -0.0123457 | -0.0123457 | -0.0123457 | -0.0123457 | -0.0123457 | -0.0123457 | -0.0123457
ngfr_mod | -0.0123457 | -0.0123457 | -0.3958327 | -0.160827 | -0.0402576 | -0.8301972 | -0.0123457 | -0.0123457 | -0.0123457 | -0.0123457 | -0.0123457 | -0.0123457 | -0.0123457 | -0.0123457 | -0.0123457



</body>

</html>



![Screen Shot 2021-08-18 at 4 10 36 PM](https://user-images.githubusercontent.com/6730079/129965660-2d98486d-60a6-4c0d-be2e-3f0a0cb08fb2.png)

**Comment by songeric1107** [comment]
@jorvis , sorry to bother you again. We made more changes to the SVG. could you please change the zero to the white color of this version (v7)?


https://umgear.org/dataset_curator.html#/dataset/4d4eb481-2a2f-3918-1ada-30fb535bd0c7/displays



![Screen Shot 2021-08-30 at 3 17 35 PM](https://user-images.githubusercontent.com/6730079/131392868-53eabb9b-3547-415b-96b7-2bf66f8812a4.png)

**Comment by jorvis** [comment]
OK, please try again now and re-open if necessary.
