### ISSUE TITLE
Annotation support for multigene search on gene results page

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#170]
Annotation information by organism correctly shows if single-gene search is enabled.  However (and this is partially a lack of foresight on my part), clicking one of the organism icons in a multigene search fails because the FunctionalAnnotationPanel class object only supports single genes.

The way I had gotten around this was by calling `dataset_collection_panel.update_by_all_results` inside of `index.js:update_datasetframes_generesults` for multigene searches (same for the `search_genes.py` success callback).  It seems that single gene searches instead go from `index.js:update_datasetframes_generesults` to `index.js:select_search_result` then to `dataset_collection_panel.update_by_search_result`.  There are other locations that call `index.js:select_search_result` as well.  

I don't think moving the `dataset_collection_panel.update_by_all_results` call inside of `index.js:select_search_result` is the best solution for this, since the latter function seems to deal with handling selections from the single-gene search list of genes.  Maybe a multigene equivalent of that function can be made which will populate the annotation object and then call `dataset_collection_panel.update_by_all_results` (which itself probably needs to be modified to handle a per-organism basis

**Comment by jorvis** [comment]
Closing, as this has been in production for some time.  We simply show a message for now.
