### ISSUE TITLE
Test volcano plot fold-change, p-value threshold options, and "group vs rest" plot option

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#174]
Referencing the suggestions at the bottom of #161.  There should be new options for setting the p-value threshold, upper and lower logfoldchange thresholds, and also to plot a group vs the union of the rest of the groups.  Please test to ensure a) they work and b) to ensure the aesthetics and user experience is fine.

**Comment by Kvnrose** [comment]
I dont see the pvalue / fold change thresholds. I am also getting the following error.

![image](https://user-images.githubusercontent.com/46610614/150596450-57cf69c6-2abd-4c05-a0eb-85e30c391328.png)

**Comment by adkinsrs** [comment]
@Kvnrose I forgot to restart the apache server, which compiles the latest CGI code /facepalm

Anyways regarding the pvalue/logfc content, can you either clear your browser cache for the devel server, or open the browser in "incognito mode"?

**Comment by Kvnrose** [comment]
Looks to be working well! Nicely done.

![image](https://user-images.githubusercontent.com/46610614/150598620-95421eb3-10c5-4a59-8b2e-6148841a95ba.png)

**Comment by JPReceveur** [comment]
Found another dataset where a log2FC of 15K is pulling the plot axis and making it hard to read:
4-6wks, mouse, scRNA-seq, utricle Atoh1-transduced supporting cells (Groves)


<img width="978" alt="Screen Shot 2022-02-28 at 1 12 09 PM" src="https://user-images.githubusercontent.com/28451557/156037275-aee987b1-15dd-48c7-be3b-7fdad2ac8de9.png">

**Comment by adkinsrs** [comment]
I wonder if this dataset needs to be added to the list of datasets that are considered log10 by default.  I believe this is a case where we assume the data is raw and then it gets log transformed when already transformed.

**Comment by adkinsrs** [comment]
As a result I think it's fair to close the ticket again since it seems to be a specific dataset issue and not necessarily a malady of the codebase

**Comment by adkinsrs** [comment]
So this dataset is already in the "log10-transformed" list.  I'm going to leave this ticket closed and just poke around some.

**Comment by adkinsrs** [comment]
Pushed a commit to remove that dataset from the "log10-transformed list".  I believe it's inclusion into the list was in error. Volcano plot looks normal when dataset is excluded from this list (meaning that log2 transformation is applied).


![newplot](https://user-images.githubusercontent.com/5665914/156593292-8574e8b6-edb6-4bc0-ab0d-2fd19ea0c9b1.png)
