### ISSUE TITLE
able to adjust the panel size for multi-gene display

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#176]
could we adjust the panel width for the multigene display?

**Comment by adkinsrs** [comment]
Set mg_grid_width = 6 (originally 4 or 1/3 of the panel row).

If displays for certain plot types need to be adjusted, I can adjust them with a plot config file I created.

If individual plot displays need to be adjusted (one or two displays where the majority for that plot type look fine), then we can discuss that later.

**Comment by adkinsrs** [comment]
This is in v2, in the dataset collection "layout arranger" mode
