### ISSUE TITLE
multigene display takes longer time for heatmap.

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#177]
I am able to generate the heatmap, however, it takes forever to display on the front page.

**Comment by songeric1107** [comment]
![Screen Shot 2022-01-24 at 10 37 48 PM](https://user-images.githubusercontent.com/6730079/150906648-8895fd32-2959-417e-b953-2f91e715dc67.png)
![Screen Shot 2022-01-24 at 10 38 43 PM](https://user-images.githubusercontent.com/6730079/150906651-57c7e4b3-b01c-43cc-85c2-514c4b2a796e.png)

**Comment by songeric1107** [comment]
due to the privacy of the tested dataset, open a new ticket in another area. https://github.com/jorvis/gEAR/issues/1108

**Comment by adkinsrs** [comment]
Closing this ticket due to it being moved
