### ISSUE TITLE
how to load gene cart on the front page

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#178]
how to select the gene cart on the front page of gEAR? especially for multi-gene display

![Screen Shot 2022-01-25 at 10 12 58 PM](https://user-images.githubusercontent.com/6730079/151097968-8c0b4444-c08a-472e-b7d0-040f790262e3.png)

**Comment by adkinsrs** [comment]
I feel there was a reason that the gene carts aren't loaded pre-search.  @jorvis was this an intentional choice or something we overlooked?

**Comment by jorvis** [comment]
I can't recall any specific reason it isn't on the front page other than a general worry of cluttering that initial search widget too much.  It doesn't flow well though at all, of course, if you're an advanced user and know you want to start with a cart.  

I'm up for any elegant suggestions.

**Comment by adkinsrs** [comment]
This has been implemented
