### ISSUE TITLE
change a profile as a public profile

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#179]
https://umgear.org/p?l=9ceebacc
 
orig name: “Waldhaus Lab”

new name: scRNA/ATAC-seq - P2, mouse cochlea (Waldhaus)

**Comment by jorvis** [comment]
This is done

**Comment by jorvis** [comment]
Sorry, I didn't pay attention to the title here and only did the name change as the main comment.

**Comment by jorvis** [comment]
Done now.
