### ISSUE TITLE
Analysis Workbench - Should we clear Analysis-class object when rerunning certain steps?

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#185]
I was testing a feature addition in the analysis workbench, and I noticed that some analysis steps are modified depending on if there is a property in the Analysis-class object stored in JS. 

For instance, for the Marker Gene Visualization step, I noticed that if you run with a certain number of genes (5 for this example), the "marker_genes.n_genes" and "marker_genes.calculated" properties are set after success, and allows the step to skip marker gene computation, via scanpy.tl.rank_genes_groups if run subsequently.  However if I wanted to rerun with a different number of top genes (say 10), this was not possible since the "compute_markers" step is set to true if the "marker_genes.calculated" step is true. In this case, I have an unpushed change to ignore the "calculated" property and recompute if the selected top N genes does not match what is stored in the Analysis object.  I see that some other steps take changing parameters on the current step into consideration for rerunning analysis, so maybe this was just a one-off issue I found

This brings me to my discussion question, and maybe this should actually be under "Discussions" instead. What if a user clicks the "New" option from the Stored Analysis dropdown?  Should we clear the analysis object in the situation?  Is it possible for a user to ever want to go back a step or two in the analysis, and if so, does it make sense to clear all future-step Analysis object properties?

**Comment by jorvis** [comment]
So we want to prevent the situation where we're saving copies of the h5 file after every step.  We should allow users to go back to some, but some of the steps modify the data in a way what isn't reversible without starting over from the original file.  As long as we keep the UI in sync with this limitation this is a fine thing to do.

**Comment by adkinsrs** [comment]
Looking at some of this code more intensely and it seems that some of my concerns are already addressed (particularly the "New" analysis selection). I will close this ticket and have a look-over to ensure that user changes in the same step are running correctly and updating the analysis object correctly.
