### ISSUE TITLE
Problem with saving gene cart from multigene page

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#186]
https://github.com/jorvis/gEAR/issues/1111#issue-1117800808

From @beamilon

**Comment by adkinsrs** [comment]
> ![image](https://user-images.githubusercontent.com/70719873/151612120-69f71f76-7710-44e1-81b9-0717286acaca.png)


I created a volcano plot from the multigene display and used the lasso tool to select few genes. When I clicked on "save new gene cart", the gene cart window appears but when I try to save it, a message "issue with saving gene cart" appears. I pasted a picture below.

**Comment by jorvis** [comment]
From the list of genes there is it possible the string being passed contains new lines?  I just pushed a fix for this earlier today

**Comment by adkinsrs** [comment]
@beamilon, since Joshua recently updated production, can you confirm if this works now?

**Comment by beamilon** [comment]
@adkinsrs, I still get the error message

**Comment by adkinsrs** [comment]
Closing this for now.  Was able to successfully save a gene cart
