### ISSUE TITLE
Add error label on plots that fail from the panel display page

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#191]
References #190 

This includes both the default display and the loaded alternate displays

**Comment by adkinsrs** [comment]
This should be available for testing whenever devel or production servers are updated

**Comment by beamilon** [comment]
It is working. Thanks

**Comment by adkinsrs** [comment]
I am closing this ticket.

If you ever find that a single plot appears to take forever in loading, it is probably because I missed an error for that particular case.  So for those, just open up a new ticket with the dataset information and other pertinent information (unless it is a private dataset), and I'll address that.
