### ISSUE TITLE
Move "Forget Password" to be more visible.

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#192]
Tested this out by putting in a wrong password and realized the functionality already exists. Should the forget password option be available by default when signing in and then get hidden after login to keep the page less cluttered? Users might not know to put in a wrong password in order to get the forget password option to come up.

_Originally posted by @JPReceveur in https://github.com/IGS/gEAR/discussions/168#discussioncomment-2007335_

I think I will take some inspiration from Facebook's inline login

**Comment by adkinsrs** [comment]
<img width="620" alt="Screen Shot 2022-02-02 at 11 13 35 AM" src="https://user-images.githubusercontent.com/5665914/152192680-34623a21-ed60-4e2a-8ba2-807495f1b0c3.png">

**Comment by adkinsrs** [comment]
<img width="1375" alt="Screen Shot 2022-02-02 at 1 12 21 PM" src="https://user-images.githubusercontent.com/5665914/152212859-e2e20421-26d3-441a-872f-e952d544b0db.png">


@JPReceveur  any thoughts on this?

**Comment by JPReceveur** [comment]
@adkinsrs The image looks good to me, was going to check it on devel but the site been giving me connection issues today

**Comment by adkinsrs** [comment]
c7b99ca addresses this.  This should be reflected in the next devel/production server code update
