### ISSUE TITLE
could not find the gene cart which is created using comparison tool

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#194]
a gene cart that is created after using the comparison tool could not find in the gene cart management system.
![Screen Shot 2022-02-03 at 10 50 17 PM](https://user-images.githubusercontent.com/6730079/152469125-90c60614-3d62-4d11-aea8-3ad2bb545d38.png)

![Screen Shot 2022-02-03 at 10 54 00 PM](https://user-images.githubusercontent.com/6730079/152469203-c66c884d-2221-484b-8143-bd04fac56508.png)

**Comment by adkinsrs** [comment]
I can replicate this locally.  The CGI script runs but does not return the gene card ID in the response as was expected.  The stacktrace error says ` Column 'organism_id' cannot be null`.  So I think that compare_datasets.js needs to be adjusted

**Comment by adkinsrs** [comment]
Pushed commit to fix this.

Turns out when I originally wrote this, I mistyped the HTML id the "organism_id" data property was bound to.

**Comment by adkinsrs** [comment]
@songeric1107 feel free to try it out on production now

**Comment by adkinsrs** [comment]
Discovered the "organism-id" is not prepopulated as a data attribute for the datasets when a dataset_id is passed as a URL parameter... only when the user manually selects a dataset from the tree structure.  I'm working on a fix for this.

**Comment by adkinsrs** [comment]
Addressed with [4e7471b](https://github.com/IGS/gEAR/commit/4e7471b4b3ab68dd2b22299c14b568c9850f2707)
