### ISSUE TITLE
comparison tool does not work for 3 factor combination

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#195]
https://umgear.org/compare_datasets.html?dataset_id=097ae3e2-014e-39df-7087-691ed5f46ab9

![Screen Shot 2022-02-04 at 11 02 58 AM](https://user-images.githubusercontent.com/6730079/152561727-9fa023bf-1748-4b28-8ca5-36643ae7ee54.png)

![Screen Shot 2022-02-04 at 11 05 34 AM](https://user-images.githubusercontent.com/6730079/152562066-02686e53-4402-431a-9de9-3f9150a88546.png)

**Comment by adkinsrs** [comment]
Just to confirm, this does work if you do both A1;ADULT;F and A1;ADULT;M, correct?  

I would also recommend hitting "Plot" a few times... I have run into the issue where it takes a couple tries to successfully plot, because the server was hitting memory or cpu limits

**Comment by adkinsrs** [comment]
<img width="1147" alt="Screen Shot 2022-02-04 at 11 10 58 AM" src="https://user-images.githubusercontent.com/5665914/152562953-73f324dc-4553-4fd0-a8bd-a1f762ec6813.png">

**Comment by adkinsrs** [comment]
I'm going to poke around and find out why it randomly works and does not work

**Comment by adkinsrs** [comment]
@songeric1107 I see what is happening now.  Sometimes the order of the conditions is not preserved when passed to certain parts of the script, and this is breaking things.  I'll work on a fix and push a commit soon

**Comment by adkinsrs** [comment]
Pushed out a fix... waiting for @jorvis to update production
