### ISSUE TITLE
Issue #187 is back

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#196]
![image](https://user-images.githubusercontent.com/70719873/152600725-e4b0ca4c-781d-4b3d-9f31-e4ee83cb391b.png)

**Comment by jorvis** [comment]
Issue #187 - Can you provide for me the URL you used to get this (privately, if needed)

**Comment by beamilon** [comment]
It's not URL specific. It happened when refreshing any page on the gEAR.

**Comment by jorvis** [comment]
Fixed again.  Issue was reintroduced today when I fixed permalinks.  Now have uploaded a version which corrects both.
