### ISSUE TITLE
Primary analysis needed for public 2 scRNAseq datasets

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#201]
Could we create primary analysis for the single cell workbench for the following 2 datasets?
- 9 wko, mouse, scRNA-seq, cochlea, spiral ganglion neurons (Decibel Tx)
- P25-P27, mouse, scRNA-seq, cochlear sensory neurons (Goodrich)

**Comment by jorvis** [comment]
These are dataset IDs:
2f79f784-f7f7-7dc3-9b3e-4c87a4346d91
c32835d3-cac4-bb0e-a90a-0b41dec6617a

I ran it, but neither had primary analysis data to parse out.  The second one, for example, has only coluns 'tissue_type' and 'replicate'

**Comment by beamilon** [comment]
Ok. Thanks. We will probably need to contact them if they want to have one.

**Comment by jorvis** [comment]
Closing then until this is needed again and new data is acquired.

**Comment by songeric1107** [comment]
anything I can help? I can add a column for primary analysis purposes, do you want me to do it?

**Comment by beamilon** [comment]
@songeric1107 . If it is easy to do, you can do it. I don't know how it works and if we ask for permission before publishing a primary analysis.

**Comment by beamilon** [comment]
@songeric1107 Ronna said to go ahead.

**Comment by songeric1107** [comment]
@jorvis , I add extra column "cluster_lab" for both datasets

- **c32835d3-cac4-bb0e-a90a-0b41dec6617a.h5ad**

![Screen Shot 2022-02-05 at 4 07 11 PM](https://user-images.githubusercontent.com/6730079/152659078-3eaf1e1a-62e6-441c-81b2-08d1b9872687.png)

- **2f79f784-f7f7-7dc3-9b3e-4c87a4346d91.h5ad**

![Screen Shot 2022-02-05 at 4 09 07 PM](https://user-images.githubusercontent.com/6730079/152659128-a7643e62-d953-462f-a6a5-c121b433c1fe.png)

**Comment by jorvis** [comment]
OK, clustering analysis added to both.

**Comment by songeric1107** [comment]
This dataset is one of the earliest scRNA datasets we load to the gEAR (1/2019). At that time, we are not finalized what to load to gEAR. I finally found the tsne coordinate of this dataset, I will re-upload it, @jorvis could replace it in the public profile.

**Comment by songeric1107** [comment]
I reupload the dataset again, here is the link

https://umgear.org/dataset_curator.html#/dataset/53f99080-29cd-44ca-4c14-b26ca1ad7588/displays
![Screen Shot 2022-02-14 at 1 05 38 PM](https://user-images.githubusercontent.com/6730079/153921140-4a2b8eb5-b96b-48ae-a919-a63641b981b2.png)


@jorvis , could you please add the primary analysis to this? thank you

**Comment by jorvis** [comment]
Can this be closed now since #221 is?

**Comment by songeric1107** [comment]
I guess so
