### ISSUE TITLE
Info icon not working in multigene view mode

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#203]
When in multigene view mode, clicking on the Info icon doesn't open the info window.
![image](https://user-images.githubusercontent.com/70719873/152696218-ce9d3738-4e66-403b-a2ef-54098cd8cf93.png)

**Comment by adkinsrs** [comment]
Hi @beamilon, 

I need an example where you are seeing this.  I have clicked the "info" button for a couple of datasets and had no issues generating the dialog box

**Comment by adkinsrs** [comment]
Closing this ticket for now, but it may be worth addressing the order of operations for when elements become clickable in the future.
