### ISSUE TITLE
Gene carts empty after login

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#205]
Steps to reproduce:

- Be NOT logged in when you load the front page.  All gene carts show empty
- Log in
- Gene carts still show empty until page is loaded.

**Comment by adkinsrs** [comment]
https://github.com/IGS/gEAR/blob/2fa46e6bc501e9a3a2692da910a03d399e0a4f39/www/js/index.js#L240-L249

**Comment by adkinsrs** [comment]
Should not be an issue for v2
