### ISSUE TITLE
Datasets without category for multigene display generation.

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#208]
Four datasets have no category appearing in the multigene display viewer, so graphs can't be generated.
- P0, mouse, RNA-seq, hair cells vs epithelial non-hair cells (Hertzano)
- P0, mouse, RNA-seq, cochlea, hair cells compared with rest of cochlear duct (Groves)
- E12.5-P30, mouse, scRNA-seq, endolymphatic sac (Griffith)
- E18.5, mouse, microarray, cochlea, Igf1+/+ and Igf1-/- (Varela-Nieto)

Example for P0, mouse, RNA-seq, hair cells vs epithelial non-hair cells (Hertzano)
![image](https://user-images.githubusercontent.com/70719873/153230331-cc19bcb7-8c5f-4849-a4e8-2a22ccd8fc6a.png)

**Comment by adkinsrs** [comment]
Using the example from #1114, I feel it may be tricky for some cases.  I can tell from the shape of the `adata.X` object that has 4 total observations which is the same as the adata.obs.index (meaning no replicates present). But creating the obs table would be manual work.... is this 2 categories with 2 conditions each, or is it 1 category with 4 conditions in that one category?

**Comment by adkinsrs** [comment]
Is it possible to reupload these datasets, and change their UUID to match the previous one?

**Comment by jorvis** [comment]
I think we're going to hold on this one until either after ARO or we find ourselves with nothing to do.

**Comment by adkinsrs** [comment]
Going to work on an error message notifying the users there are no observations for this dataset.

**Comment by adkinsrs** [comment]
<img width="1139" alt="Screen Shot 2022-02-10 at 2 25 32 PM" src="https://user-images.githubusercontent.com/5665914/153481805-6b10653e-fdb3-4f2d-a517-23a5d2e5daf1.png">

**Comment by jorvis** [comment]
I like it.

**Comment by beamilon** [comment]
P0, mouse, RNA-seq, hair cells vs epithelial non-hair cells (Hertzano) has now categories so I created a multigene display.

Can we have the error message for E18.5, mouse, microarray, cochlea, Igf1+/+ and Igf1-/- (Varela-Nieto), there are no category.

**Comment by songeric1107** [comment]
I am not sure it is due to the special character of the "condition" or lack of duplicate for the condition.

![Screen Shot 2022-02-16 at 5 39 57 PM](https://user-images.githubusercontent.com/6730079/154369581-5c6a635b-c231-4a46-bf2f-2090b45f5ea0.png)

**Comment by beamilon** [comment]
The Hertzano dataset doesn't have replicates either but the categories are now showing up, so it is probably another problem.

**Comment by songeric1107** [comment]
@beamilon , I modified the h5ad file (Ronna's) by adding the category variable to it. https://github.com/jorvis/gEAR/issues/1114

**Comment by songeric1107** [comment]
E18.5, mouse, microarray, cochlea, Igf1+/+ and Igf1-/- (Varela-Nieto)

there is no duplicate for this dataset

https://umgear.org/dataset_curator.html#/dataset/1123e546-e178-01a4-54d9-13492913c739/displays


![Screen Shot 2022-02-23 at 12 52 37 PM](https://user-images.githubusercontent.com/6730079/155377956-c8d29542-27c6-463d-b762-44a221c8dbf8.png)

**Comment by adkinsrs** [comment]
This is what I see in the observations

```
            conditions cell_type   louvain
index
Coch_4_1+_+  Igf-1 -/-  cochleas  cochleas
Coch_4_2-_-   Igf-1+/+  cochleas  cochleas
```

The error you posted was that the "cell_type" and "louvain" only have a single group present and so it would be pointless to filter them.  Should I get rid of that, and let you filter them anyways, even if it does not matter in the end?

The "conditions" category should have been shown but I am guessing the slash in both groups is causing some issue.

**Comment by adkinsrs** [comment]
@songeric1107 do you want me to edit this dataset to fix the "conditions" datatype to category?

**Comment by songeric1107** [comment]
I think you can try. Maybe let Bea know what she wants to change it to?

**Comment by adkinsrs** [comment]
closing

**Comment by adkinsrs** [comment]
related to https://github.com/IGS/gEAR/issues/258
