### ISSUE TITLE
Reproducible failure to load curator

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#212]
I'm logged in as myself.  When I go to the Dataset explorer and filter on my datasets, each result has a button to load the curator:

![edit_delete](https://user-images.githubusercontent.com/330899/153450284-de7c78e7-ab40-44a7-ab9c-a38f95858e83.png)

When I click it I'm no longer logged in and the curator fails to load.

![Screenshot from 2022-02-10 10-15-05](https://user-images.githubusercontent.com/330899/153449857-f4491b91-e49d-4b79-8e7c-88854b412d6f.png)

**Comment by adkinsrs** [comment]
Can replicate via the "Curate Display" button on a dataset

**Comment by adkinsrs** [comment]
I see the requested version of VueRouter cannot be found.  Looking into it

**Comment by adkinsrs** [comment]
I believe the some CDN links for a combination of Vue, Vuex, and VueRouter got updated, and I am trying to ensure the correct compatible versions are used.  I know Vue has steadily changed from Vue2 to Vue3 and https://cdn.jsdelivr.net/npm/vue actually references Vue3 instead of 2 now.
