### ISSUE TITLE
Find marker genes step returns errors on a particular dataset

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#218]
Sorry if I missed something and it is being taking care of, but the 'find marker genes' from the primary analysis for P25-P27, mouse, scRNA-seq, cochlear sensory neurons (Goodrich) returns an "Error reporting marker genes"

**Comment by songeric1107** [comment]
this needs to be re-uploaded, there is no umap coordinate in the observation file, the primary function will not work.

**Comment by songeric1107** [comment]
reupload the dataset again with tsne coordinate. 

https://umgear.org/dataset_curator.html#/dataset/53f99080-29cd-44ca-4c14-b26ca1ad7588/displays
![Screen Shot 2022-02-14 at 1 05 38 PM](https://user-images.githubusercontent.com/6730079/153921293-33e4686d-160d-4c1e-8b57-4f90e727563c.png)

**Comment by beamilon** [comment]
The primary is still not working. Since 221 was closed, I thought the dataset had been re-uploaded.
Is there a different problem?

**Comment by beamilon** [comment]
The dataset in the public profile is the one without "TSNE": P25-P27, mouse, scRNA-seq, cochlear sensory neurons (Goodrich)
There is a primary analysis available apparently but the 'Find marker genes' returns an error message.
![image](https://user-images.githubusercontent.com/70719873/159773537-178e2d7a-d27a-40e1-b7af-1d74ee9ebf58.png)

**Comment by songeric1107** [comment]
@beamilon , the TSNE coordinate only adds to the one with TSNE in the title, the other one is for violin plot /svg purposes.

![Screen Shot 2022-05-20 at 9 34 38 AM](https://user-images.githubusercontent.com/6730079/169539597-a2965265-500b-4516-94e3-c003adb588fe.png)


If you want to use the one with tsne, we should replace the one in the profile with the new one. 
without TSNE: c32835d3-cac4-bb0e-a90a-0b41dec6617a
new with TSNE:53f99080-29cd-44ca-4c14-b26ca1ad7588

**Comment by beamilon** [comment]
@songeric1107  Yes, I think we should replace with the new one to have access to the primary analysis

**Comment by songeric1107** [comment]
@beamilon @jorvis , this dataset is included in multiple profile, what is the best way to replace it. 

data_308_2022.txt:scRNA-seq / Cell Types/Tissues / Andy / Neuron / SGNs / Neuron Total / Neuron / PMB SGNs / scRNAseq+deafenedRats / Tom / My Profile FW / test / single cell sq (interest) / Sian test / MyProfile01 / Neuron / Mouse cochlea Single-c RNAseq / SGN RNAseq	c32835d3-cac4-bb0e-a90a-0b41dec6617a	P25-P27, mouse, scRNA-seq, cochlear sensory neurons (Goodrich)	single-cell-rnaseq	rhertzano@smail.umaryland.ed30078709	GSE114997	Public	2019-01-31 18:37:40

**Comment by jorvis** [comment]
So is that the only thing which has changed?  tSNE was added but everything else stayed the same?

**Comment by songeric1107** [comment]
the column names are different, but the plot is the same
![Screen Shot 2022-05-20 at 2 04 45 PM](https://user-images.githubusercontent.com/6730079/169587377-91024174-92f4-41e0-9be6-99d66750e4f4.png)
![Screen Shot 2022-05-20 at 2 04 29 PM](https://user-images.githubusercontent.com/6730079/169587379-05ff3270-b3bd-4f4e-a47f-73a7aea22cec.png)

![Screen Shot 2022-05-20 at 2 07 12 PM](https://user-images.githubusercontent.com/6730079/169587598-e3a18d92-5186-4001-ab32-0d0c368f8543.png)

![Screen Shot 2022-05-20 at 2 08 12 PM](https://user-images.githubusercontent.com/6730079/169587696-f69666a6-5d14-4e63-a0ea-a36a34f652c6.png)

**Comment by songeric1107** [comment]
this dataset is included in multiple profiles, I am not sure whether other users have any curations using the old version.

@beamilon any comments?

**Comment by beamilon** [comment]
@songeric1107 That's a good point. I will ask Ronna.

**Comment by songeric1107** [comment]
- old version without TSNE (in the public profiles):c32835d3-cac4-bb0e-a90a-0b41dec6617a,  

3 optional columns names for plotting: 
position(Apex,Base,Middle), 
tissue_type(1_A,1_B,1_C,T2),
cluster_labe( Apex_1_A, Apex_1_B........Middle_1_A,Middle_1_B,Middle_1_C)

![](https://user-images.githubusercontent.com/6730079/169587377-91024174-92f4-41e0-9be6-99d66750e4f4.png)


- new version with TSNE ():53f99080-29cd-44ca-4c14-b26ca1ad7588.
3 columns except for the tsne coordinate: 
condition(Apex, Base,Middle)---maybe change this as "position"
cell_type(A_T1,B_T1,C_T1,T2)
cluster_label(A_T1,B_T1,C_T1,T2)



![](https://user-images.githubusercontent.com/6730079/169587379-05ff3270-b3bd-4f4e-a47f-73a7aea22cec.png)

**Comment by jorvis** [comment]
So the values within that column are different but the column name is the same.  I think think there's anything to do with that one then.

**Comment by jorvis** [comment]
The 53f99080-29cd-44ca-4c14-b26ca1ad7588 dataset can be deleted.
