### ISSUE TITLE
what statistic method is used for  "Find marker genes" of single-cell-workbench

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#22]
what statistic method is used for the "Find marker genes" step of the workbench

"t-test" or "wilcoxon rank-sum"?

also what value is used for comparison?  for example, the mean value of gene1 across all the cells in cell_type1 vs the mean value of gene2 in cell_type2?

This is a question from a user.

**Comment by jorvis** [comment]
Currently it's t-test but the underlying libraries support t-test, wilcoxon rank-sum and logistic regression.  We could add those as options for the user to specify.

https://scanpy.readthedocs.io/en/stable/generated/scanpy.tl.rank_genes_groups.html
