### ISSUE TITLE
saving a list of genes into a new cart

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#220]
**From:** Elena Chrysostomou

**Email:** echrysostomou@salk.edu

**Server IP:** 10.142.0.16

**Msg:** Hi all 

Hope you are doing well. I was just wondering if there is a way to save a list of genes that you have manually listed in the search bar into a gene cart.

I really like the new multigene display viewer!!

**Tags:** ['']

**Screenshot:** None

**Comment by jorvis** [comment]
I've responded.
