### ISSUE TITLE
add primary analysis to a re-uploaded dataset

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#221]
reupload the scRNAseq dataset with tsne coordinate. (P25-P27, mouse, scRNA-seq, cochlear sensory neurons (Goodrich))

https://umgear.org/dataset_curator.html#/dataset/53f99080-29cd-44ca-4c14-b26ca1ad7588/displays

@jorvis could you please add the primary analysis to it?

#201 #218

**Comment by jorvis** [comment]
Done
