### ISSUE TITLE
The default icon is not visible  during curation

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#224]
the "default" icon does not show on the top right corner of the default display during curation although I clicked it multiple times, although I refresh the page multiple times.

![Screen Shot 2022-02-15 at 3 48 17 PM](https://user-images.githubusercontent.com/6730079/154146859-39d5f168-d630-4ae6-98de-c1871760d352.png)

**Comment by adkinsrs** [comment]
It could indicate the "save as default" CGI call is not succeeding

**Comment by adkinsrs** [comment]
@songeric1107 can you paste the URL for this?

**Comment by songeric1107** [comment]
7960565d-bc9e-2320-8492-f482745ef498

**Comment by adkinsrs** [comment]
save_default_display.cgi returns true, so it is something else

**Comment by adkinsrs** [comment]
Since I recently had to change the Vue JS library loaded to a specific version, maybe there was a breaking code-change associated with that release compared to whatever version was being pulled in by default.

**Comment by adkinsrs** [comment]
<img width="351" alt="Screen Shot 2022-02-15 at 4 07 56 PM" src="https://user-images.githubusercontent.com/5665914/154149371-e1ccd179-4a81-42f1-8f61-e8936e3e61c1.png">

It's neither.  It's an issue with the CSS not rendering the purple color.  I recently adjusted the CSS to use variables but some have too many hyphens.  Going to push a commit soon, and fix it directly on the production server too

**Comment by adkinsrs** [comment]
Should be fine now... closing
