### ISSUE TITLE
Refresh needed when creating a new profile

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#227]
I created a new profile and in order for it to be 'active', I have to refresh the page. If I don't refresh and click the eye icon to see the datasets in my new profile, it lists all the public datasets. Only after I refresh the page, the correct datasets for the profile are shown.

**Comment by jorvis** [comment]
Thanks for catching this.  I think it happened to me during a demo but I couldn't catch what the series of steps was at the time. It has been fixed and will be part of the next production update.
