### ISSUE TITLE
Epiviz Panel Designer unresponsive

### ISSUE THREAD

**Issue by brianherb** [IGS/gEAR#23]
I've recently uploaded bigwig data via url and tried to create a epiviz panel on the umgear.org site. The specific issue is on the "Step 2: Add Tracks to Epiviz viewer" step - Clicking on the blue ADD CHART 
![image](https://user-images.githubusercontent.com/13540148/130495752-67a77f5d-4012-42fc-b5a9-780523ec35e4.png)
button does not seem to do anything. Is this a known problem?

**Comment by brianherb** [comment]
looks like this error pops up when the button is clicked:
epiviz-components.html-202.js:181 Uncaught TypeError: Cannot read property 'forEach' of null
    at HTMLElement.handleGetCollections (epiviz-components.html-202.js:181)
    at HTMLElement.handler (epiviz-components.html-12.js:83)
    at HTMLElement.fire (epiviz-components.html-37.js:388)
    at HTMLElement._handleResponse (epiviz-components.html-121.js:520)

**Comment by brianherb** [comment]
Update - I created a trackhub and was able to view it on the UCSC genome browser, so bigwigs are fine.  When I tried using this trackhub to upload data, I got the following error: 

jquery-3.3.1.min.js:2 GET https://umgear.org/trackhub?hub=http%3A%2F%2Fdata.nemoarchive.org%2Fother%2Fgrant%2Fsament%2Fsament%2FEdge_ATAC%2FTrackHub%2Fhub.txt 500 (Internal Server Error)

**Comment by jorvis** [comment]
I have updated the production server and restarted apache.  Please re-open if this is still an issue.
