### ISSUE TITLE
Test new Multigene Curator gene selection features

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#232]
References to #225

In the multigene curator, if you select a "quadrant" or "volcano" plot, when you select genes a table will pop up on the right side.  This table resembles that of the comparison tool in that you can download data and save a gene cart from those genes. This table also can scroll if the genes list is long, but it is imperfect in my opinion but serviceable.

**Comment by JPReceveur** [comment]
Table works as expected. 

Some other volcano plot related comments:
When clicking on a plot for the first time, is the zoom functionality supposed to be default or is the select tool? The tooltip for how to go back to the full sized plot by double-clicking should stay up longer. Should there be a zoom icon in the plot controls and do we want the plot controls vertically to match the comparison tool?

In the adjust p value threshold box, can the counter be changed so the arrows move the value by smaller increments, 0.1 or similar? Currently it moves values by 1, which doesn't have much utility for p values.

Under the adjust log-fold change threshold header, should 'All data points outside of this range are considered significant.' be changed to 'All data points outside this range will be colored as up or down regulated'? log-fold change thresholds do not test for significance, which may get confused with the differential expression tests.

**Comment by adkinsrs** [comment]
- The zoom functionality is the default in plotly, and I am not sure if it is possible to reset which tool is the starting default... would have to look it up.
- Help instructions (just like in the comparison tool) since they would have to account for the plot width being different since some plots do not show a table to the right of it.  I can just make all plots the same width and put the help instructions to the right though.
- I can certainly adjust the p-value threshold (and I thought I had made the step increment smaller haha)
- Will make the text change for log-fold change threshold.

**Comment by adkinsrs** [comment]
Updated gear-devel with everything but the "help instructions" bullet point since that wasn't specifically requested, and I'm not sure how best to implement that if I wanted to.

**Comment by JPReceveur** [comment]
Related to the zoom functionality in the volcano plot,  can a plot control be added for zoom (similar to the compare tool)? I think zoom is a useful control to have for the volcano plots. 

Other changes look good and work as expected

**Comment by adkinsrs** [comment]
@JPReceveur Yes,  in fact we have full control over what controls are shown or hidden. It may be worth having a discussion to determine if any additional plot controls should be added.

**Comment by JPReceveur** [comment]
@adkinsrs Do we want to close this for now and revisit if needed or discuss plot controls further now? (Was just going through outstanding tickets assigned to me).
