### ISSUE TITLE
Add analysis tool links to dataset explorer

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#236]
Currently if users want to open a dataset in an analysis tool from the dataset explorer, there are no easy ways of going directly from the dataset explorer to an analysis tool (similar to how when doing a gene search you can use the dropdown menu to open the dataset in a tool.

Perhaps adding buttons in line with the view, change display buttons for the various tools or one 'analysis' button with a dropdown (if we want to avoid having a bunch of different buttons) would encourage users to use those tools more.

<img width="1470" alt="Screen Shot 2022-03-03 at 9 07 20 AM" src="https://user-images.githubusercontent.com/28451557/156581160-006e1de5-e366-4cf4-b031-8c342782b28d.png">
)

**Comment by jorvis** [comment]
![Screenshot from 2022-03-30 15-38-50](https://user-images.githubusercontent.com/330899/160928780-abc6b3a2-7261-4c3a-8bcd-9b3eebd4c53c.png)
