### ISSUE TITLE
Add links to tutorials/get help button to all tool pages

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#239]
From user feedback, we keep getting asked for tutorials (video or otherwise) which suggests users are not going to the manual and looking for the tool they are interested in. Adding a 'get help' or 'tutorial' button to the single cell workbench and multigene curator tool might help remind users the tutorials are there. Also while the help popup for the compare tool is already there, it would be good to link to the manual page as well in the help message.

Minor note: For the get help button on the comparison tool, the plot control options shown in the help are not the same that users would see in the plots. This change can wait if we want to think about what controls are useful and which just add clutter (Currently I think there are a couple too many compare plot controls but it would be good if we could pick a set that would be useful and consistent across plots).

<img width="260" alt="Screen Shot 2022-03-07 at 9 17 55 AM" src="https://user-images.githubusercontent.com/28451557/157051486-2ceb3d57-4536-424a-8873-c2f12ce24604.png">

**Comment by JPReceveur** [comment]
Can the epigenetic and expression (e.g. https://umgear.org/upload_dataset.html) upload pages be modified to include links to their respective tabs in the manual documentation (https://umgear.org/manual.html)? It seems a lot of people forget that they're there. 

Might also be worth putting a direct link to the respective Youtube walkthroughs for the comparison/single cell tools in their 'get help' buttons if it doesn't make them look too cluttered.

**Comment by adkinsrs** [comment]
- [ ]  Change image in compare tool controls "help" to reflect vertical orientation
- [ ]  Decide what compare tool controls to keep or remove
- [ ]  Figure out where to put a help button.  Ideally I would like to be able to reuse code, which means the button should go in a reusable element, like the navigation bar, or the top of the "container" class for each page.
- [ ]  Should the help button link to the corresponding Github Wiki documentation, or to the "manual" page in gEAR, or even another thing?

**Comment by adkinsrs** [comment]
<img width="1726" alt="Screen Shot 2022-09-06 at 11 34 33 AM" src="https://user-images.githubusercontent.com/5665914/188676798-391de2c6-8dd3-450f-b74e-16c21703c603.png">

This is what I was thinking.  A help button in the upper-right of all pages, just under the purple header banner.  Thoughts?

**Comment by jorvis** [comment]
I'd just flick through the main pages and make sure that doesn't interfere with any controls, but it seems fine to be there to me.

**Comment by JPReceveur** [comment]
Works for me too, let me know if you want to go through devel to test it, didn't see it up there yet. 

For the last point, I'd say link it to the gEAR manual page rather than the Wiki

**Comment by adkinsrs** [comment]
It's only on my local copy right now and just adding that button for the multigene curator was the only change I did.

**Comment by adkinsrs** [comment]
It just occurred to me that every one of these pages already has a "Manual" link in the navigation bar up top.  Having another "help" button would just add redundancy and potentially make things more busy.  So I was thinking we just make the "Manual" button more noticeable (maybe change the name to "Help" or "User Guide"), and have it automatically go to the correct documentation for the page it was clicked on.

Thoughts @jorvis @JPReceveur ?

**Comment by JPReceveur** [comment]
Works for me. Another thought if we wanted to really highlight that we have walkthrough videos would be to split the user help button into 2 ('video walkthrough' and 'user guide', for pages we have videos for) where clicking takes them to either the video or slides spot on the manual page. 

It's a bit redundant in that both would take users to different parts of the same page but I'm for anything that helps with people not noticing or being able to find the walkthrough videos. 

However we decide to approach the button, I think it should open in a new window by default. Currently if a user hits the manual link, it opens in the same window. Given the lingering weirdness with the back button (#238), they might not always be able to get back to the place they were easily.

**Comment by adkinsrs** [comment]
The code I was implementing was going to open in a new window fortunately :-)

Most other documentation tool pages I tend to look at have their user guide and tutorial links in the header, so I think that's what we need to focus on. I wonder if the links would be more noticeable if the font was changed in "Manual" and "Contact".... those font types are not reused in the main gEAR text.

**Comment by adkinsrs** [comment]
<img width="1621" alt="Screen Shot 2022-09-07 at 2 11 04 PM" src="https://user-images.githubusercontent.com/5665914/188948909-b3e5ac50-d504-4354-ad64-3fea815d8f11.png">
<img width="1595" alt="Screen Shot 2022-09-07 at 2 11 42 PM" src="https://user-images.githubusercontent.com/5665914/188948991-ff451d62-5fc0-4332-a5b1-380ee6be55a5.png">

For example, Pandas seems to space out their navbar elements compared to ours, which seem a bit more cramped.

**Comment by adkinsrs** [comment]
<img width="1595" alt="Screen Shot 2022-09-07 at 3 18 11 PM" src="https://user-images.githubusercontent.com/5665914/188959551-23d8f7a7-ae55-4b5f-a871-2b08eec10ee4.png">

Thoughts on this?

**Comment by JPReceveur** [comment]
It looks good to me, I think its fine without being bolded.

**Comment by adkinsrs** [comment]
Addressing with commit [a7be4c1](https://github.com/IGS/gEAR/commit/a7be4c1b16b5a2c3f94417d9a433e7876b4d6739)

Any page with a youtube walkthrough will have a link in the navbar, and any page without one will had that navbar link hidden (since there is nowhere to direct the user).
