### ISSUE TITLE
Update software versions on server and fix any associated introduced bugs

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#240]
Recently created a branch "software_update_bugfixes" to address this.  Eventually we want to update software on the servers to take advantage of new functions and efficiency.

My current Docker version of code (which has python package versions as shown in https://github.com/IGS/gEAR/blob/main/docker/requirements.txt) has issues with a few things, such as the compare tool failing in `scanpy.rank_genes_groups` if a significance test is performed.  I believe I have also seen bugs in later portions of the scRNA-Seq Analysis Workbench with `scanpy.rank_genes_groups_violin`, and these all usually center around the "adata.raw" property.  We can make fixes on the new branch, while not affecting current code.

**Comment by jorvis** [comment]
Commit a9379a6 updates documentation for Ubuntu 21.10, Python 3.10.4 and module dependencies.

**Comment by adkinsrs** [comment]
Pushed another pair of commits on "software_update_bugfixes" to update the Dockerfile.  The docker image successfully built but I would still need to verify that code works.  Since I have the image saved locally, I can easily test my projectR branch to ensure it is still functional.

**Comment by jorvis** [comment]
Issue noted in issue #307 which means we may need to keep scanpy at 0.7.8

**Comment by adkinsrs** [comment]
Currently encountering another issue with h5ad_compare_genes where scanpy.pl.rank_genes_groups_violin is failing as it is trying to access gene ensembl IDs from adata.var that do not exist in the adata object.  Currently debugging.

**Comment by adkinsrs** [comment]
Created https://github.com/scverse/scanpy/issues/2258 to address this

**Comment by adkinsrs** [comment]
Closing as superceded by https://github.com/IGS/gEAR/pull/694
