### ISSUE TITLE
Make zebrafish profile public

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#241]
From Ronna:

> Regenerating Neuromast (Piotrowski) can now be public. Need to find a way to put it in the highlighted public profiles and also have it in the HRP profiles. OK to change the name a bit (e.g. call it in the highlighted public profiles 
> 
>  Regenerating ZF Neuromast (Piotrowski))

**Comment by jorvis** [comment]
OK, this is done.

@songeric1107 - Ronna has requested that a full copy of this profile be created with the same name so that I can make it appear under the HRP folders too.  A coming update will make it such that one layout can appear in multiple places, but for now a manual copy has to happen.

**Comment by songeric1107** [comment]
@jorvis , If I understand correctly, I need to add the datasets in Regenerating Neuromast (Piotrowski) to HRP profile, right?

**Comment by songeric1107** [comment]
I could not see the group profile from "data explore".
![Screen Shot 2022-03-09 at 11 41 49 AM](https://user-images.githubusercontent.com/6730079/157488502-6041b513-1575-470e-b457-1806c74d4035.png)

**Comment by jorvis** [comment]
Create a new profile called "Regenerating Neuromast (Piotrowski)" and make it identical to this one:

https://umgear.org/index.html?&gene_symbol_exact_match=1&multigene_plots=0&layout_id=5e1bb1ec&gene_symbol=Sox2

**Comment by songeric1107** [comment]
got it

**Comment by songeric1107** [comment]
https://umgear.org/p?l=466fb708

change the profile name from "Regenerating ZF Neuromast (Pio)" to "Regenerating ZF Neuromast (Piotrowski))

**Comment by jorvis** [comment]
This has all been done.
