### ISSUE TITLE
Category order not updating for Lateral wall profile

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#245]
When creating multigene displays for the datasets in the lateral wall profile, adjusting the sort order for categories doesn't transfer to the graph.
It is fixed for the other datasets that had the same problem.

**Comment by beamilon** [comment]
Seems to work now so closing the ticket

**Comment by beamilon** [comment]
Now realize that deleting one of the cell type (for example I remove "unknown") prevent the the category order to be updated in the created graph. If I leave all cell types then it works fine.

**Comment by adkinsrs** [comment]
so @JPReceveur mentioned this as well.

As a temporary solution, if you select a different category, then the original one, the sort order groups will be updated to match the category filter.

**Comment by adkinsrs** [comment]
Regarding sort order, I also have a similar issue at #254 specifically for stacked violin plots that I need to work out.

**Comment by adkinsrs** [comment]
Added immediate change to sort order categories when the user adds or removes a group from the filters.  This is committed but not pushed to gear-devel or gear-production yet.

Note that when the function triggers, the sort order is reset to the original order.

**Comment by JPReceveur** [comment]
Tested and works as expected for primary and secondary categories, closing ticket
