### ISSUE TITLE
Multigene displays updated and ready to be made default

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#246]
I have updated some of the heatmaps in the public profiles following @adkinsrs update. Some are automatically updating in user account but the following ones need to be pushed:

- [x] P0, mouse, RNA-seq, hair cells vs epithelial non-hair cells (Hertzano)
- [x] P1, mouse, RNA-seq, cochlea, hair cells, Gentamicin-induced gene expression changes (Segil)
- [x] P0, mouse, RNA-seq, epithelial vs neuronal, mesenchymal and vascular endothelial (Hertzano)
- [x] embryonic stem cell line, microarray, induction of hair cells (Henrique)
- [x] P1, P4, mouse, RNA-seq, cochlea, with and without Wnt activation (Dabdoub)
- [x] 4dpf, zebrafish, microarray, hair cell, mantle cell and skin (Hudspeth)
- [x] 5dpf, zebrafish, RNA-seq, hair cell (IP) and whole larvae input (IN) (Hertzano)
- [x] 4dpf, zebrafish, RNA-seq, TU-tagged hair cells mRNA and whole larvae input (Nicolson)
- [x] P7-adult, mouse, RNA-seq, medial geniculate and primary auditory cortex (A1) (Hackett)
- [ ] P1, mouse, scRNA-seq, cochlear epithelium (Kelley)
- [ ] 5dpf, zebrafish scRNA-seq, neuromast (Piotrowski)

**Comment by beamilon** [comment]
@jorvis @adkinsrs  The above multigene displays still need to be made available on the production site for every users.

**Comment by adkinsrs** [comment]
Is this done?  Can we close this?

**Comment by beamilon** [comment]
@adkinsrs Not done yet.

**Comment by jorvis** [comment]
OK, I can try to look at this today.

**Comment by jorvis** [comment]
@beamilon - The ones I checked above have been fixed.  The unchecked two I couldn't see a multi-gene curation which wasn't owned by the dataset owner.  In addition, these three datasets DID have multi-gene curations made by the curator but which were owned by the user and weren't on your list:

- [ ] 5dpf, homeostatic neuromast, zebrafish, scRNAseq (Piotrowski)
- [ ] mouse cochlea, adult (1,9,26 months), RNA-seq (He 2022)
- [ ] P25-P27, mouse, scRNA-seq, cochlear sensory neurons (Goodrich)

**Comment by beamilon** [comment]
@jorvis Thanks. I will check tomorrow for the missing ones.

**Comment by beamilon** [comment]
@jorvis I looked at the 2 unchecked datasets and they look ok now. If I remember correctly, the order for the X-axis was not updating correctly. All good now.
I will check the 3 you sent later today.

**Comment by jorvis** [comment]
OK, closing this for now then.  We can re-open if more needs to be done.
