### ISSUE TITLE
Zoom in view icon

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#247]
I think that the drop down menu will be updated but would it be possible to have the (+) View by itself on the dataset banner. I feel that especially with having now the multigene displays, the zoom in option is really important and may be missed.
Example below
![image](https://user-images.githubusercontent.com/70719873/157771809-12a05663-56cb-49f6-a317-96b987589576.png)

**Comment by adkinsrs** [comment]
This was directly mentioned in https://github.com/IGS/gEAR/issues/180
