### ISSUE TITLE
Path in for non-coding biologists

### ISSUE THREAD

**Issue by RLC-DCPPC** [IGS/gEAR#256]
Need a way for non-coders to get data in

Assumptions:

- all datasets will be analyzed, not raw

Work to do:

- [x] roadmap/flowchart/decision tree/wizard/sorting hat to help folks at varying levels and experience get to what they need
- [x] documentation of format needed
- [ ] Zoom hand-holding session
- [ ] define the process and document it

**Comment by JPReceveur** [comment]
Related to the first point, I started putting together a flowchart for the different data types and what documentation individuals might need based on their data. @songeric1107 @adkinsrs Any thoughts on whether to keep the documentations broad or split them into smaller pieces? For example, splitting out the single cell documentations based on the different pipelines (Serat,  SingleCellExperiment, etc) . At least for this flowchart that was too many boxes but having them in separate documentations might be clearer for users reading them. 

For the flowchart eventually it'll probably be best to have flowcharts for each of the data upload types. Having them all in one makes the text pretty small.


![DraftUploadFlowchart](https://user-images.githubusercontent.com/28451557/159051469-7e778b8f-d63e-4576-97d6-7ba3d6880dc3.png)

**Comment by adkinsrs** [comment]
This might actually be a good opportunity to make use of the Github repo's Wiki page (https://github.com/IGS/gEAR/wiki).  We could even link to the wiki from somewhere in the main gEAR site.  We did a similar thing with NeMO Archive stuff, where different ways to submit data as well as retrieve data were posted in that repo's wiki

**Comment by JPReceveur** [comment]
A draft Wiki is available here 
https://github.com/IGS/gEAR/wiki/Welcome-to-the-gEAR-Wiki!

Related to the path in for non-coding biologists, I created separate slide decks for uploading in Excel format to highlight that option better for users.
