### ISSUE TITLE
dataset stuck in loading for multigene viewer

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#258]
Chicken Basilar Papilla Baseline, P7, svg,scRNA-seq (Janesick), geneID is a dataset with no category for multigene viewer but the window in the search page still shows 'loading'
![image](https://user-images.githubusercontent.com/70719873/159034320-f5d5ef5f-ff59-4843-b051-4f899c93f4ae.png)

**Comment by adkinsrs** [comment]
I'm guessing for now if the dataset has no categorical observations then we just print an error to that effect, right?

**Comment by adkinsrs** [comment]
<img width="618" alt="Screen Shot 2022-03-18 at 3 01 59 PM" src="https://user-images.githubusercontent.com/5665914/159067920-d84930d7-4d81-4caf-a8bc-de24b3e7523c.png">

Pushed a commit to address this, and it is hard-coded in gear-production.  @beamilon does this error message look fine for you?

**Comment by beamilon** [comment]
@adkinsrs There are still several datasets where the message "There are no categorical observations found for this dataset." appears only in the Multigene Display Viewer but the search window still shows "No default display. Create one in the multigene curator."
![image](https://user-images.githubusercontent.com/70719873/163606018-13956c70-1ac5-45e1-8900-274795449d95.png)

**Comment by adkinsrs** [comment]
@beamilon I believe the codebase on the production server has not been updated to the latest versions

**Comment by adkinsrs** [comment]
Looked into it more.  gEAR checks for default displays first before calling the API to generate a plot for the display.  The API is where I print the "There are no categorical observations found for this dataset." information.  So the issue is trying to figure out how to perform the categorical observation check before the check for default displays.

**Comment by adkinsrs** [comment]
<img width="1254" alt="Screen Shot 2022-04-15 at 3 02 14 PM" src="https://user-images.githubusercontent.com/5665914/163621673-9fcda873-395b-426b-9815-52159bb0d174.png">

Addressing on "main" branch in commit [fe8acfc](https://github.com/IGS/gEAR/commit/fe8acfc6854882cc60808d4faa56909751884b52)
