### ISSUE TITLE
change one scRNAseq from Dr.Liu's lab as public profile

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#262]
could you please change this profile as a public profile?

https://umgear.org/p?l=E9to13Innerear

the manuscript has been published.

Thanks

**Comment by jorvis** [comment]
Just public or is it also going as one of the site-recommended ones?

**Comment by songeric1107** [comment]
from Ronna.

"make it a highlighted public profile"

**Comment by jorvis** [comment]
This has been done, and I renamed the profile to make it match the convention of the others which started with "scRNA-seq"
