### ISSUE TITLE
Set annotation to proper organism if all datasets within profile are one organism

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#271]
the icon for zb fish is incorrect for all the zbfish profiles. the taxa icon displayed as mouse.

we use 7955 (Taxanomy ID) in the metadata for zbfish.

![Screen Shot 2022-03-31 at 4 33 50 PM](https://user-images.githubusercontent.com/6730079/161144786-cce9cb63-320b-4b60-96b7-f83602926096.png)

**Comment by jorvis** [comment]
OK, I've changed the title to reflect this as a feature request in cases like this.

**Comment by adkinsrs** [comment]
Would it be as simple as adding a "layouts" field in the database for default organism id?  We can take requests to adjust the default organism if necessary (such as with the zebrafish profile), but eventually could implement customizable options when the user creates a new profile (such as default organism).
