### ISSUE TITLE
Test Issue #266

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#272]
#266

Currently available on gear-devel.  

Steps to create:
* There is a new "center mean expression around zero" checkbox when creating heatmaps

I would also like input on a) if the colorscales used for centered and non-centered heatmaps are acceptable and b) If the colorbar having a mid at 0 (for centered plots) and a min of 0 (for non-centered plots) is fine.

**Comment by adkinsrs** [comment]
Hold off on this until I give the OK.  I just realized that all the projectR dependencies are not installed.  While they have nothing to do with the multigene curator tool, the Flask API loads all modules for all API endpoints first

**Comment by adkinsrs** [comment]
Ok, I've installed the dependencies I needed to install.  So test away

**Comment by JPReceveur** [comment]
Tested on a couple datasets and works as expected.
I think the color choices are acceptable for defaults, I didn't have any problems interpreting them. 
Having the mid at 0 for centered or a min of zero for noncentered is fine.
