### ISSUE TITLE
scRNAseq, mouse,otic and peri-otic cells (Liu)

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#281]
**From:** Charles Morgan

**Email:** cmorga46@jhmi.edu

**Server IP:** 10.142.0.16

**Msg:** Hello,
I am interested in tracking expression of a gene using the scRNAseq, mouse,otic and peri-otic cells E9.5-E13.5 (Liu) datasets, but I noticed they are private and unpublished. Would you be able to provide me with contact information for the submitter of the datasets? I would love to reach out to them about a potential collaboration.

**Tags:** ['']

**Screenshot:** None

**Comment by songeric1107** [comment]
I have sent an email to the owner, the owner will contact Charles directly.

**Comment by adkinsrs** [comment]
Should this be closed now?
