### ISSUE TITLE
change datasets as public automatically if the profile is labeled as a public/highlight profile

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#282]
could we automatically change the datasets within a public profile/highlight profile as publically available?

for example :

https://umgear.org/p?l=E9to13Innerea

I could not add the PMID to it or change any datasets as public.

PMID: 35320729
GEO:GSE178931

![Screen Shot 2022-04-13 at 9 16 30 PM](https://user-images.githubusercontent.com/6730079/163294975-4ea21341-741b-4af5-88b7-575b6ac23f17.png)

**Comment by adkinsrs** [comment]
Relates to #259

**Comment by jorvis** [comment]
All datasets have been changed.  The other considerations will be handled in issue #260
