### ISSUE TITLE
Exact match tooltip doesn't match icon on/off upon page reload

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#295]
When first navigating to the homepage (or upon refreshing), the tooltip for the exact match in the explore gene expression box shows it is off while the button displays as on. If you click the exact match button off and then on again the tooltip corrects itself. Not a big deal in terms of usability but just recording the behavior here.

<img width="626" alt="Screen Shot 2022-04-25 at 12 16 26 PM" src="https://user-images.githubusercontent.com/28451557/165130720-7a127f54-ccfc-49a5-91e1-b4e6349f9d59.png">

**Comment by jorvis** [comment]
Ooh, that's the part I needed to hear, that this has been observed by others. 

Also, maybe next week we can do a screenshare where I request access to your screen and can walk around the debugger to help?

**Comment by JPReceveur** [comment]
Sure thing, I'm mostly free tomorrow and thursday if we want to do then. Also to clarify, the sign in issues have been noted by others (and by the Dieterich group, https://github.com/dieterich-lab/gEAR/issues/2), not the exact match issue.

**Comment by JPReceveur** [comment]
I think the tooltip issue noted here may be solved by the  login fix. On devel I now see below (the expected functionality), while on production I see the incorrect tooltip. 


<img width="656" alt="Screen Shot 2022-06-28 at 8 02 11 AM" src="https://user-images.githubusercontent.com/28451557/176173804-4706f0ac-a2f3-4438-8511-98c76f2d9887.png">

**Comment by adkinsrs** [comment]
Awesome!

I learned that the login fix exposed an issue where the profile and genecart trees, which require a session ID to retrieve user data, attempt to load before the session ID is retrieved (which occurs during the login step).  I am trying to work on that right now as well.

**Comment by jorvis** [comment]
@JPReceveur I have updated the production server - can you please confirm that it's working there for you now still too and, if so, close this?

**Comment by JPReceveur** [comment]
If I clear cache and hard refresh it works as expected. However, if I hit a normal refresh or hit the gear icon right after the clearing cache and hard refresh, it goes back to the tooltip being incorrect.

Devel has similar behavior, I just didn't click around after seeing it work earlier today

**Comment by JPReceveur** [comment]
Same behavior as before, clear cache and hard refresh results in correct tooltip but refresh or moving off the page after that results in incorrect tooltip

**Comment by adkinsrs** [comment]
It may just be another race condition that needs investigating

**Comment by jorvis** [comment]
Closing after site redesign.
