### ISSUE TITLE
errors about the annotation_release_number in the metadata sheet

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#300]
Trying to add a single-digit release number for Neisseria for GCID dataset. for example (-1, or 1), always get errors as follows.

Seems the annotation_release number only accepts a two-digit number.

should we remove the "restriction" for this term?

![Screen Shot 2022-04-29 at 9 11 24 AM](https://user-images.githubusercontent.com/6730079/165951648-1147b8dc-5ae4-4d5d-a99d-d6d7d680df74.png)
![Screen Shot 2022-04-29 at 9 09 11 AM](https://user-images.githubusercontent.com/6730079/165951657-5a85c433-9149-47be-9071-d000f33c374a.png)

![Screen Shot 2022-04-29 at 9 19 56 AM](https://user-images.githubusercontent.com/6730079/165952379-5d96bf17-7393-47c9-824b-636c9c0cb3f4.png)

![Screen Shot 2022-04-29 at 9 09 11 AM](https://user-images.githubusercontent.com/6730079/165952321-6f666b1c-6624-4bb0-9f44-76ab35400115.png)

**Comment by jorvis** [comment]
We actually need this information so it being required is appropriate.  We could either process the annotation history on Ensembl for protists or use the latest (54).  There are a lot of features of the site, especially upcoming, where we need these values to be both populated and correct.

What the [flowchart will be](https://docs.google.com/presentation/d/14EHyXnY9GEOjSKr-hz4MbnL4VJDQgb_3rEiGKotQcl0/edit?usp=sharing) for new and existing datasets.
