### ISSUE TITLE
Selecting marker genes for visualization in table returning wrong values

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#306]
Using the dataset "Cristal Ampullaris, Glail, Cell type (Bermingham-McDonogh) in the single-cell workbench, clicking on the button to select all of the genes in a row results in different numbers of genes depending on which row is selected (actual number for the screenshots shown below is 30).

Issue also replicated with scRNA-Seq of all principle neonatal cochlear cell groups, cell type,color_code (Heller).

<img width="1009" alt="Screen Shot 2022-05-04 at 1 17 34 PM" src="https://user-images.githubusercontent.com/28451557/166743597-dff1797f-c5d8-42ea-a6ea-b3cf361b01f5.png">

<img width="974" alt="Screen Shot 2022-05-04 at 1 17 55 PM" src="https://user-images.githubusercontent.com/28451557/166743617-e56898cc-3bba-41da-9112-5bccd7918f20.png">

<img width="969" alt="Screen Shot 2022-05-04 at 1 18 18 PM" src="https://user-images.githubusercontent.com/28451557/166743638-2315e289-306f-4078-9d85-63e45ecfca9a.png">

**Comment by adkinsrs** [comment]
I think the "Marker genes selected in table" section is actually counting unique marker genes, so it would make sense that the number is changing as different rows are selected.  Can you confirm this, and if that is the case, I think the best solution would be to change the text that displays the counts in the three bullet points

**Comment by JPReceveur** [comment]
Confirmed that that is the reason for the different numbers. Based on the text, I was expecting the 'Marker genes selected in table' to stay at 30 and the the unique genes number to change depending on what is there but the two numbers were identical even if a gene was selected multiple times.

**Comment by adkinsrs** [comment]
addressed in [28d0378](https://github.com/IGS/gEAR/commit/28d0378a03a3fb4dbfae63d6d22183f7c5521284)
