### ISSUE TITLE
Group labeling headers show up before click on clustering step, single-cell wb

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#307]
In the clustering step of the single cell workbench, the column names for the relabeling table show up before clicking on the button.

They make sense after clicking rerun but having them there beforehand might confuse people.

<img width="1112" alt="Screen Shot 2022-05-04 at 1 27 22 PM" src="https://user-images.githubusercontent.com/28451557/166745924-710dc536-e7c0-4628-b964-a57659cf13fe.png">

<img width="880" alt="Screen Shot 2022-05-04 at 1 33 55 PM" src="https://user-images.githubusercontent.com/28451557/166745990-07c9d593-0d97-4024-adc8-475cc2dec231.png">

**Comment by adkinsrs** [comment]
From what I understand, it was an intentional design choice to show the marker table in "Clustering" after the "Plot" button in "Find Marker Genes" is clicked.  That way you can edit the labels to your liking before rerunning the louvain analysis.  Is this not the order of how you are seeing things?

**Comment by JPReceveur** [comment]
Yup that overall design choice is fine for me, I'm just noting that when you first toggle the clustering step (before clicking anything) I see something along the lines of below.
<img width="1169" alt="Screen Shot 2022-05-10 at 3 41 50 PM" src="https://user-images.githubusercontent.com/28451557/167709309-6548e237-498f-4283-ac85-86c2274a5a37.png">

It looks like  'Group,Marker,New labels' shows up before clicking on plot or rerun with labels. If you look at this section thinking the text above the button is a description of what the button does, it doesn't make sense and may confuse people.

**Comment by adkinsrs** [comment]
Interesting.  I could not replicate this either on the devel server.  The table and "rerun with labels" only show for me after running the "Find Marker Genes" step.  I may have to observe what you are doing to ensure I ran though this in the same manner.

**Comment by JPReceveur** [comment]
Tried it again on devel and could not replicate the original issue (issue is present on production). However on devel, I get an error at the find marker genes step. Using the same dataset and settings on production, it works fine. The error shows up as Failed to load resource: the server responded with a status of 500 (Internal Server Error)

<img width="1261" alt="Screen Shot 2022-05-11 at 4 33 52 PM" src="https://user-images.githubusercontent.com/28451557/167945385-6215b16e-2d34-4215-adda-4d53966f9735.png">
)

**Comment by adkinsrs** [comment]
Ok, this was the issue I was worried about with respect to updated scanpy and using the "rank_genes_groups" function.  I'll create a branch and work on that.

**Comment by adkinsrs** [comment]
created branch "scanpy_rank_genes_groups_fix"

**Comment by adkinsrs** [comment]
Ticket https://github.com/scverse/scanpy/issues/2181 suggests backporting "anndata" to version 0.7.8, which is the version on my Docker image.  gear-devel has it at 0.8.0
