### ISSUE TITLE
create a RNASEQ profile of Neisseria gonorrhoeae with host 

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#308]
- [x] load the 3 expression profiles of Neisseria gonorrhea strains (Opaless3x, H041,FA1090)

1. https://gcid.umgear.org/p?s=fb789dce
2. 

- [ ] load the host expression profile
- [ ] build the connection between the locus IDs

**Comment by songeric1107** [comment]
@adkinsrs , there is a bug on the front page of this dataset. 

https://gcid.umgear.org/dataset_curator.html#/dataset/c373db45-9392-6c29-f947-f353e53da71f/displays/883/edit


I could see the plot on the curation page but not on the front page. I think there is a bug

![Screen Shot 2022-09-12 at 1 35 24 PM](https://user-images.githubusercontent.com/6730079/189720748-f723e0d6-4179-46c8-9cb4-9b5b1a7533fa.png)

![Screen Shot 2022-09-12 at 1 35 46 PM](https://user-images.githubusercontent.com/6730079/189720919-e71485a2-6e4e-493e-a58e-174c275d038c.png)

**Comment by adkinsrs** [comment]
I am guessing there is a uppercase/lowercase discrepancy between what is named in the dataset vs what is named in the mysql database.

**Comment by adkinsrs** [comment]
Closing in favor of new issue.  The latest comment is more of a bug fix than about creating a new profile
