### ISSUE TITLE
required column names to perform statistical analysis using comparison tool

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#310]
To perform statistical analysis using the comparison tool, a column named one of these “replicate”, “BioRep”, or “TechRep” is required

@JPReceveur , should we add this to the wiki page?

**Comment by JPReceveur** [comment]
Sure thing, I've added some information to the [RNAseq page ](https://github.com/IGS/gEAR/wiki/Prepare-3-tab-format-for-RNAseq-dataset-uploading) and the slides associated with doing that upload via Excel. Was there other points where you think that information should be added?

**Comment by JPReceveur** [comment]
@songeric1107 Any other spots where you think additional information about replicates should be added?

**Comment by adkinsrs** [comment]
Worth noting I added a blurb at the end of https://github.com/IGS/gEAR/wiki#comparison-tool but feel free to edit as needed

**Comment by songeric1107** [comment]
I think it may also be necessary to emphasize in the data prep section, that" the replicate column is needed to use the statistic analysis of comparison tool function".

https://github.com/IGS/gEAR/wiki/Prepare-3-tab-format-for-RNAseq-dataset-uploading
![Screen Shot 2022-05-16 at 8 25 26 AM](https://user-images.githubusercontent.com/6730079/168592018-35ff8101-1b65-465a-a439-276d5b89c29c.png)

**Comment by JPReceveur** [comment]
Added the following: A column named "replicate", “BioRep”, or “TechRep” is needed for conducting statistic analysis with the comparison tool.
