### ISSUE TITLE
Choosing a significance test in the compare tool prevents the graph to load

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#315]
@jorvis @adkinsrs 
I tried the compare tool with different datasets. Everything is fine until I select a significance test. Then I get an error message.
![image](https://user-images.githubusercontent.com/70719873/169396764-5814d8a4-101b-431f-9260-a96a6a5038ef.png)

**Comment by adkinsrs** [comment]
This is related to the upgrade with scanpy I believe.  I'll try and push a quick fix today

**Comment by adkinsrs** [comment]
Just added this fix to the production page.  Please check and see if it works now.

**Comment by beamilon** [comment]
@adkinsrs 
Awesome. Thank you.
