### ISSUE TITLE
single cell workbench PCA not displaying

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#321]
@jorvis @adkinsrs @songeric1107 
I was testing the single cell workbench with 2 different datasets and at the Principal Component Analysis (PCA) step and Genes to colorize (comma-separated), returns a blank plot
![image](https://user-images.githubusercontent.com/70719873/169547873-092b06dd-5b80-4506-a2cb-9b0ec60669c5.png)

**Comment by adkinsrs** [comment]
Need to comma-separate your genes

**Comment by adkinsrs** [comment]
Though we should make it also accept spaces in the future

**Comment by beamilon** [comment]
Thanks!!
