### ISSUE TITLE
Heatmap generation not working

### ISSUE THREAD

**Issue by Kvnrose** [IGS/gEAR#322]
When trying to make a heatmaps for any dataset (we tried both P1 and P7 Matt Kelley dataset).

Here is the screenshot with the error

![image](https://user-images.githubusercontent.com/46610614/169552979-ef9e06d7-881e-4b27-aaf4-df986bb246ac.png)

**Comment by adkinsrs** [comment]
@Kvnrose please check and ensure it is working now

The dash-bio package (which generates the clustergram) was updated from 0.6.1 to 1.0.2, which broke things.  The plot axis for both the heatmap and dendrogram components changed labels which broke things.

Pushed a commit that addresses this, and also the code on production has been hard-coded to work now
