### ISSUE TITLE
Marker gene visualization returns an error message

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#323]
@jorvis @adkinsrs 
Trying to visualize marker genes in the single cell workbench returns an error message.
![image](https://user-images.githubusercontent.com/70719873/169702865-5e13b7b3-1865-470c-99c1-76c17ccbea57.png)

**Comment by jorvis** [comment]
Can you post the dataset title here?

**Comment by beamilon** [comment]
5dpf, zebrafish scRNA-seq, neuromast (Piotrowski)

**Comment by adkinsrs** [comment]
I'm not able to replicate.  Using "primary analysis" and this dataset, I can generate the top 5 marker genes, label a tSNE with a gene, and get visualizations when comparing top 7 genes across Young vs Mature HC cells

**Comment by jorvis** [comment]
Bea, can you describe the steps you are doing?

**Comment by adkinsrs** [comment]
<img width="1003" alt="Screen Shot 2022-05-22 at 11 40 45 AM" src="https://user-images.githubusercontent.com/5665914/169703736-30afeb35-4d3f-45e7-a7bd-797c8524ddf7.png">

Also cannot replicate with top 10 genes (I see the earlier picture uses 10 genes)

**Comment by adkinsrs** [comment]
Ooh... it's the Visualize button.  Do get an error with that.

**Comment by beamilon** [comment]
I refreshed, used another dataset 4dpf, zebrafish, microarray, hair cell, mantle cell and skin (Hudspeth) and I am not getting error message but I am getting broken image icons
Primary analysis, enter 10 genes, click go, select several genes in the table, click visualize
![image](https://user-images.githubusercontent.com/70719873/169703725-90c989f3-df5c-48f9-9665-e9086b80494e.png)

**Comment by adkinsrs** [comment]
```
ValueError: adata.raw.var_names contains duplicated items
```

I suspect this is related to #318, where the adata.var index has some duplication that prevents scanpy from plotting

**Comment by beamilon** [comment]
It was working before the update, this how we created the story with tmem178b

**Comment by adkinsrs** [comment]
actually this dataset has completely unique index items (ensembl IDs), but the gene_symbols have some duplications.  I believe what I need to do is deduplicate the gene symbols, but again, it's random which ensembl ID is kept for that gene symbol so the expression may change.

**Comment by beamilon** [comment]
The problem came after the update, so what happened with the update that all datasets have duplication problems now?

**Comment by adkinsrs** [comment]
> The problem came after the update, so what happened with the update that all datasets have duplication problems now?

This is probably from the updates from the `anndata` package, but some of those could also be from the `scanpy` package too.

Anyways I have gotten the visualization plotting step to work (by deduplicating the gene symbols that map to multiple ensembl IDs) but one of the CGI scripts cannot retrieve the images that are generated.  Working on that now.

**Comment by adkinsrs** [comment]
Visualization should work now

**Comment by beamilon** [comment]
Tried with different datasets randomly and it is working

**Comment by adkinsrs** [comment]
Going to close this for now.
