### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#325]
**From:** Yoshitomo Ueda

**Email:** yosueda@iu.edu

**Server IP:** 10.142.0.16

**Msg:** Hi,

I'm resetting the password, but the email has not been sent. It says Syntax Error 200. What can I do for it?

Thanks,
Yoshi

**Tags:** ['']

**Screenshot:** None

**Comment by jorvis** [comment]
I can work on this.  I've already e-mailed him.

**Comment by jorvis** [comment]
I have fixed this and notified the user.
