### ISSUE TITLE
Question about Terms

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#326]
**From:** Jeffrey Lee

**Email:** posiden072@gmail.com

**Server IP:** 10.142.0.11

**Msg:** Are we allowed to use the data on this archive in our own publications?

**Tags:** ['']

**Screenshot:** None

**Comment by jorvis** [comment]
I've responded to this user.

============================

Jeffrey -

Yes, you can absolutely use any of the public datasets on the gEAR Portal within your publications.  And if you can see it, it's a public one.  You should only be sure to cite the data source you use (you can find the publication for each like in the attached screenshot) and ideally the gEAR itself.

gEAR: Gene Expression Analysis Resource portal for community-driven, multi-omic data exploration.
Orvis J, et al. Nat Methods. 2021 Jun 25. 
doi: 10.1038/s41592-021-01200-9   PMID: 34172972.

I hope this helps.

JO
![Uploading Screenshot from 2022-05-26 09-32-30.png…]()
