### ISSUE TITLE
add the option to close the warning window.

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#330]
It is great to include the warning message for multiple ensemble ID for the same gene, should we include the option to close the window?
![Screen Shot 2022-06-01 at 10 04 48 AM](https://user-images.githubusercontent.com/6730079/171424159-cd497d0e-c21f-4643-937c-9f976df7bb2b.png)

**Comment by adkinsrs** [comment]
We should definitely have a close button.  That was an oversight on my part

**Comment by adkinsrs** [comment]
@songeric1107 I have updated gear-devel to have this fix.  I don't know what dataset you used to see this warning, so can you check and see if it looks fine on gear-devel for me?  Or just let me know and I will look.

**Comment by songeric1107** [comment]
test in devel, seems to work. i can hover to see the marning
![Screen Shot 2022-06-28 at 1 05 22 PM](https://user-images.githubusercontent.com/6730079/176241580-ae235361-db56-4665-8702-0fb789e8e07a.png)


![Screen Shot 2022-06-28 at 1 03 37 PM](https://user-images.githubusercontent.com/6730079/176241307-1e4b0232-a65c-471a-a1ef-43aa4dc0c9bc.png)
https://devel.umgear.org/dataset_curator.html#/dataset/4a308503-d023-5411-080b-9b246f30e16e/displays

**Comment by adkinsrs** [comment]
Pushed a couple extra commits in "main" to address a small issue I found in the dataset curator code, and closing
