### ISSUE TITLE
Downloading bundle or h5ad returns an internal server error

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#335]
When attempting to download a bundle file or a h5ad file it returns an internal server error (replicated with the first dataset in the hearing profile and the first dataset in the chick profile).

<img width="1430" alt="Screen Shot 2022-06-03 at 1 26 31 PM" src="https://user-images.githubusercontent.com/28451557/171915723-c51ad908-b58e-463a-97a7-8d5c476c0534.png">

<img width="1107" alt="Screen Shot 2022-06-03 at 1 27 16 PM" src="https://user-images.githubusercontent.com/28451557/171915753-b6dd466d-37e8-44aa-8c03-278644c021fd.png">

**Comment by jorvis** [comment]
Fixed in commit 3ccbbf9.  Pushed to production.
