### ISSUE TITLE
should we add a wiki tag about how to download the public datasets

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#337]
should we add a page about how to download the public dataset? and explain what the bundle means, and what the h5ad format is briefly.

**Comment by songeric1107** [comment]
here is a demo. thank you

[download_public_dataset.pptx](https://github.com/IGS/gEAR/files/8864572/download_public_dataset.pptx)

**Comment by JPReceveur** [comment]
Sure will do. On the slides where it talks about the bundle file, users who hit download bundle would get the  file in whatever format it was originally uploaded right and not always as a 3 tab set, right? Thinking about if the dataset owner uploaded via Excel or a Mex file)?
