### ISSUE TITLE
add top highly variable genes list to single cell workbench 

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#34]
it will be helpful for users if we can provide top high variable genes for PCA plotting.

it the genes provided are not in the highly variable gene list, the pca plotting will fail and prevent user to move to the next step

![Screen Shot 2021-09-15 at 2 44 06 PM](https://user-images.githubusercontent.com/6730079/134203855-15f3c8ef-a44e-4b5a-b934-f86faad73221.png)

**Comment by adkinsrs** [comment]
I'll tackle this

**Comment by adkinsrs** [comment]
<img width="917" alt="Screen Shot 2021-10-04 at 3 35 50 PM" src="https://user-images.githubusercontent.com/5665914/135913362-19acb1c7-1517-4f3b-bde8-b9b0c63e6784.png">

@songeric1107 Here is a first stab at this.  See the genes right above the Plot/Save buttons.  I sort the highly variable genes by the normalized dispersion, as reported by `scanpy.pp.highly_variable_genes` and return the top 5 results.  What do you think?

**Comment by adkinsrs** [comment]
I also fixed a bug with the CGI script generating PCA plots, where it will fail if the "genes to colorize" text box is empty instead of generating a non-colorized PCA plot.

**Comment by songeric1107** [comment]
I think it is good idea to list top5 for user to start with

**Comment by adkinsrs** [comment]
Is it fine to close this?  The code is committed but not deployed yet

**Comment by songeric1107** [comment]
sure
