### ISSUE TITLE
Forced sign out

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#341]
**From:** Sara Billings

**Email:** sarab2@stanford.edu

**Server IP:** 10.142.0.16

**Msg:** I would like to know why I keep getting signed out every time I navigate to a different screen within the gEAR website. I'm using Chrome.

**Tags:** ['']

**Screenshot:** None

**Comment by jorvis** [comment]
I have responded to this user.  My guess is session cookies are blocked but I'll await their response.

**Comment by adkinsrs** [comment]
@JPReceveur was this one of the issues you encountered as well?

**Comment by JPReceveur** [comment]
@adkinsrs Yeah, it sounds like https://github.com/IGS/gEAR/issues/215

**Comment by adkinsrs** [comment]
@JPReceveur reports this fix works in gear-devel.  I'm going to close this ticket and #216 as well.  Again this is in the projectR branch, but I can do a similar commit to "main" if need be
