### ISSUE TITLE
Functionality of Scoring method on gene search page unclear

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#353]
Joshua, 
Can you provide some info on what the expected functionality of the scoring method dropdown on the gene search page is? 

Noticed something that might be a bug but not sure what the expected result is supposed to be (and at the least, I should probably write up some documentation on the dropdown).

If I look at the svg files in the default profile and choose gene scope I see a normal looking visualization, however if I chose tissue scope, the numeric values on the svg legend go away and leave a plot with no expression values shown (second image).

<img width="1463" alt="Screen Shot 2022-07-07 at 3 03 52 PM" src="https://user-images.githubusercontent.com/28451557/177853405-294528be-97dd-4323-83e0-9dcbdde7da6f.png">

<img width="1457" alt="Screen Shot 2022-07-07 at 3 04 39 PM" src="https://user-images.githubusercontent.com/28451557/177853415-e02f1d8d-e1e8-4ac5-b49e-2a0014e1f6ff.png">

**Comment by JPReceveur** [comment]
It looks like the folder gear_site_documentation ([Link](https://drive.google.com/drive/folders/1_ZTEVKp9heVawowB5Wj-cGi2hXYP3LW1?usp=sharing)) is the only one I have access to with gEAR slides and I didn't see any info on scope in those slides, is there another folder of slides?

**Comment by jorvis** [comment]
Here you go:

![Screenshot from 2022-07-09 14-09-43](https://user-images.githubusercontent.com/330899/178119578-e2169c94-5ec8-438e-955e-26755b5034c8.png)

**Comment by jorvis** [comment]
That image is a screenshot from an [early gEAR poster](https://docs.google.com/presentation/d/1zif9WBR6AAm1ev5XzBz0jQxYP8ZViheD/edit?usp=sharing&ouid=101883820133011497593&rtpof=true&sd=true) (2016!):
