### ISSUE TITLE
Cell type for Mouse, scRNAseq,postnatal mouse utricle,raw matrix(Jan)

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#356]
@songeric1107 Can you add the cell type for this dataset?
A space is needed between "matrix" and "(Jan) for Mouse, scRNAseq,postnatal mouse utricle,raw matrix(Jan)
A space is needed between "plot" and "(Jan) for Mouse, scRNAseq,postnatal mouse utricle,SWNE plot(Jan)

**Comment by songeric1107** [comment]
Done
![Screen Shot 2022-07-12 at 11 56 22 PM](https://user-images.githubusercontent.com/6730079/178647331-9196f511-3dd6-4a1a-ae40-614b1311bc23.png)
