### ISSUE TITLE
Visualize from scRNAseq worbench is broken

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#358]
@jorvis @adkinsrs 
Once the marker genes appear in a table for the scRNA-seq primary analysis, if I select few of them in the table and try to visualize them, I get a broken icon.
I tried with Chicken Basilar Papilla Baseline, P7, tSNE plot,scRNA-seq (Janesick), geneID and with P1, mouse, scRNA-seq, cochlear epithelium (Kelley)

![image](https://user-images.githubusercontent.com/70719873/178367288-a1379b99-dae6-4313-a817-6c72764a0714.png)

**Comment by adkinsrs** [comment]
@jorvis I can take a look at this.  I thought I had resolved this for the workshop in May, by adding `add_raw=False` to fix the updated scanpy version issues. May need to roll that change back or something else.

**Comment by adkinsrs** [comment]
<img width="1630" alt="Screen Shot 2022-07-12 at 8 41 07 AM" src="https://user-images.githubusercontent.com/5665914/178492112-a96b94be-6a93-45aa-8a13-82fdc2ce1ca4.png">

**Comment by jorvis** [comment]
Production updated.
