### ISSUE TITLE
Related to #360 that is closed

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#364]
@adkinsrs I found one dataset that still has the same problem in the default profile: P2, mouse, sc-qRT-PCR, cochlea (Heller).
![image](https://user-images.githubusercontent.com/70719873/179077505-f52ee15e-4321-41c1-bdb2-85d0b3d6ae3d.png)

**Comment by adkinsrs** [comment]
`PlotError("Only one gene from the searched gene symbols was found in dataset.  The heatmap option require at least 2 genes to plot.")`

I'm assuming that you were searching the Pou4f1, Pou4f2, Pou4f3 again.  Basically only one of the three searched genes was in the dataset, and the "clustergram" method I use to create heatmaps requires at least 2 genes.

What I need to do is get that error message propagated up to the display.

**Comment by adkinsrs** [comment]
@beamilon care to verify things work now?

**Comment by beamilon** [comment]
Working. Thanks.
