### ISSUE TITLE
exact match and multigene icons inactive

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#366]
@jorvis @adkinsrs The exact match icon and the multigene display icons become inactive randomly in the result page. I didn't notice specific actions I took before clicking but it has happened several times now and the only way I can go around it, is to go back to the main page and restart the search.

**Comment by adkinsrs** [comment]
I'm clicking around doing random searches under random conditions.  I cannot seem to replicate this.

Possibly related to #295

**Comment by beamilon** [comment]
It is really random. It happened twice today, once few days ago (I ignored it), and it happened to Ronna too.

**Comment by adkinsrs** [comment]
I think there is probably a race condition where those buttons are dependent on something to have previously been loaded and it has not.  I'm going to keep looking around, but no guarantees I will find anything quickly

**Comment by adkinsrs** [comment]
One other question.  How quickly are you clicking through the results pages?  Ideally it shouldn't be an issue but it may help me figure out some patterns on when this may occur.

**Comment by adkinsrs** [comment]
Also, these two buttons do not have code in them that "disables" them.  So when you say "inactive" you mean that they are just not usable, right?  I think there may be a javascript error if this is the case.

**Comment by beamilon** [comment]
Yes, I mean not usable. Nothing happens when clicking. I don't understand the question about How quickly are you clicking through the results pages?

**Comment by adkinsrs** [comment]
> Yes, I mean not usable. Nothing happens when clicking. I don't understand the question about How quickly are you clicking through the results pages?

I meant when going from front page -> results display -> another result display, are you doing these steps in under 5 seconds, or are you giving the page a little bit of time to load before hitting "search" or changing profiles?

Again it should work no matter the case, but in the past I did encounter an issue where clicking "search" before certain page elements loaded let to unpredictable things, including searches happening twice.

**Comment by adkinsrs** [comment]
I'm setting my browser to "slow 3G" mode to see if I can detect your issue by throttling the data transfer speed.

**Comment by adkinsrs** [comment]
Ok so what I see is that the button does work (I can see the tooltip change).  But what I think is happening is that the "img" (image) element on the buttons do not change until some particular loading event happens.  And I'm trying to figure that out.

**Comment by adkinsrs** [comment]
I'm going to put this on hiatus, since I am just speculating potential issues without a way to replicate them.  I told @beamilon to grab the browser console log and paste next time she encounters this issue.

**Comment by adkinsrs** [comment]
@beamilon showed me an instance of these buttons locking up.  There was no Javascript errors present.  I could click  one of the two buttons and see that the HTML elements in the "Inspect" section of the developer change, but they change to the same state they were in.  This leads me to believe there is a condition in the JS where the variable is true but is locked in a state where it is going to always change to true.
