### ISSUE TITLE
Several datasets have multi-gene displays but none are marked as default

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#367]
@jorvis I don't know why but all the datasets that you took care of related to #246 are now back again to the message No default display. Create one in the multigene curator.
![image](https://user-images.githubusercontent.com/70719873/179289110-b5e27c0e-8a7e-4024-9468-45463501ba1f.png)

**Comment by jorvis** [comment]
I can look at this but, if you would, please name these tickets with what the problem is rather than these "Related to ...." names.  Looking at the task list makes it near impossible to know which is which.

**Comment by jorvis** [comment]
OK, I have fixed all of these except for "P7-adult, mouse, RNA-seq, medial geniculate and primary auditory cortex (A1) (Hackett)", which was already working fine.
