### ISSUE TITLE
Ability to change filtering parameters and rerun in single cell workbench

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#370]
In the single cell workbench, once a set of filtering parameters are selected in the QC by mitochondrial content step and you hit save the icon is greyed out (which is fine). However, if you wish to change the parameters and redo this step, you have to exit the workbench and start a new session. 

Can the button be altered so if you put in new values into the fields, it gives you the option to save and pick top genes again?

<img width="1469" alt="Screen Shot 2022-07-19 at 9 18 37 AM" src="https://user-images.githubusercontent.com/28451557/179760202-081d0166-b9bd-489b-bd88-e25d97eac486.png">

**Comment by adkinsrs** [comment]
I think this was discussed a while back (years).  One thing of note is that saved analyses for future steps would have to be deleted since changing previous steps would affect future results.  Also I'd have to add code to treat the future steps as if they hadn't been run.

(notes for myself)

**Comment by jorvis** [comment]
Yes, this is one of those steps which actually reduces the data content of the file and would have to nullify all future steps if they were already performed.  We'd need to (in the background) re-apply using the source dataset as the starting point.  Doable, just a bit of work.  How often is this needed once saved?

**Comment by adkinsrs** [comment]
This wasn't directly addressed, but in ui-v2 there are better indicators that certain steps are irreversible (since the dataset is filtered or transformed), and the user would need to start anew. Closing for that reason
