### ISSUE TITLE
Fix projectR import error when running PCA

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#373]
Blocks #243 progress

I have noticed my local copy projectR version is 1.12.0 and the version on nemo-devel is 1.2.0.  On nemo-devel, I can create projections using the PCA (prcomp) option and without it (default params).  However on my local copy, I run into "projectR" errors when I attempt to run in "PCA" mode.  It seems that the step in lib/gear/rfuncs.py to convert an R matrix to an R prcomp-class object is now not working.

**Comment by jorvis** [comment]
Is it time to do the full versioning update (OS + python + modules) on NeMO as we did on gEAR?  Will that fix this issue?

**Comment by adkinsrs** [comment]
This is only happening on my local copy, so I think updating code would break things in those places.

I feel confident now it's not the projectR package that is the issue now.  I believe the "prcomp" package is native R code, so it's either my R version, or rpy2.  Basically converting the R matrix to a prcomp object using rpy2 is giving a None value, which is then passed to projectR.

**Comment by adkinsrs** [comment]
Differences:

My local version
python - 3.10.4
R - 4.2.0
rpy2 - 3.5.1

nemo-devel
python -3.7.3
R - 3.6.3
rpy2 - 3.5.1

My next step is to investigate the major version change between R in both areas, as I think this could be the culprit.

**Comment by adkinsrs** [comment]
In "rfuncs.py" if I change the following line: 

`prcomp_obj = ri.ListSexpVector({"rotation": mtx})   # low-level equivalent to ro.ListVector`

to

```python
from rpy2.robjects import ListVector
prcomp_obj = ListVector({"rotation": mtx})
```

the problem is resolved.  However, I need to import in local scope and try to avoid importing rpy2.robjects globally if possible.  Every time the high-level "robjects" interface is called, it instantiates a new version of R, which eats up threads if there are lots of API calls going on.

**Comment by adkinsrs** [comment]
Addressing with [10309af](https://github.com/IGS/gEAR/commit/10309af0d6473a8f2914e9b0907d0992640a96cf)

Ideally I'd rather use the low-level interface code for performance reasons, ultimately I'd rather ensure the code works.  So I changed this line to use the high-level code, which should not be computationally expensive.
