### ISSUE TITLE
Add option to modify axis labels for static UMAP plot type

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#382]
For static UMAP plot types, can the option to modify axis labels be added? If a user selects the UMAP static plot type but their data uses a different clustering approach (e.g. in the case of the dataset I'm helping to curate now, a SWNE plot) the labels show the incorrect names.

<img width="850" alt="Screen Shot 2022-07-26 at 2 40 24 PM" src="https://user-images.githubusercontent.com/28451557/181086063-2ee7c54b-95f7-443c-8f78-3fac2ac79ed1.png">

**Comment by adkinsrs** [comment]
This may not be possible in the dataset curator.

Currently, the scanpy.pl.embedding plot function, the axis labels are based on the "basis" type, which is either "pca", "tsne", or "umap".  This function does not provide an option to change the labels. I believe it is possible to do in matplotlib after the scanpy function is run though.

A lot of the recent static_tsne adjustments seem to ask for features that are present for the Plotly-based plot types, so it may be worth refactoring some of the curator to ensure these "feature" components can be loaded in "tsne" plot types also. I also imagine the tsne_data.py could use a good refactoring to accommodate some of these requests too.

**Comment by adkinsrs** [comment]
This has been committed in [5c9604d](https://github.com/IGS/gEAR/commit/5c9604dd7e150dc9ecb94c6aa0cf2f310ab0e33f)
