### ISSUE TITLE
Question about Downloading

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#384]
**From:** Jeffrey Lee

**Email:** posiden072@gmail.com

**Server IP:** 10.142.0.11

**Msg:** Hi, I was just wondering if we are able to directly download the data from the website since I was curious as to whether I would be able to see if a specific protein is going to be transported outside the cell. Thanks,
Jeffrey

**Tags:** ['']

**Screenshot:** None

**Comment by jorvis** [comment]
Jeffrey -

If you are looking at the results of any search for a given dataset you can always use the menu in the upper-right corner of that dataset to download the source data.  I've attached a screenshot to illustrate this.  

![Screenshot from 2022-07-27 00-53-38](https://user-images.githubusercontent.com/330899/181171962-8ba48e78-01df-49a0-8c5a-e0ce696fb14c.png)


Notice the two "Download" options at the end of the list.

JO
