### ISSUE TITLE
tSNE/UMAP don't look right in the sc workbench

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#386]
@jorvis @adkinsrs @songeric1107 I used E14, mouse, scRNA-seq, cochlear epithelium (Kelley) and started a new analysis. The clustering looks horrible, not like a clustering at all, everything seems to overlap. I noticed that when I prepared the slides for the EARssentials workshop but didn't think much of it at the time. Katie noticed the same thing with different parameters, different datasets even her own. We may add more examples tomorrow.
![image](https://user-images.githubusercontent.com/70719873/181382792-37fb961c-70c3-409c-8473-6e31c5da4f2d.png)

**Comment by songeric1107** [comment]
@beamilon , that is what I mentioned before, the problem is caused by the normalized values.  all the Kelly datasets are normalized values, not raw values. so it is not appropriate to use sc workbench to re-nomoralize the log normalized values. you should use the primary analysis for those datasets.

**Comment by jorvis** [comment]
This is an ongoing discussion on updating the datasets which are normalized and which aren't, then disabling parts of the interface where they shouldn't be used.

**Comment by beamilon** [comment]
Does it make sense that the tSNE function (instead of UMAP) works great? I know these are 2 different methods but why would one be so messed  up and not the other one (top image).
I also used the raw datasets from Jan and when choosing the UMAP, the result is really not good (middle image). Choosing tSNE instead bring up something expected for clustering (bottom image).
I don't think the raw versus normalized matrix is the problem. Something is wrong with the UMAP function and it was not the case before.
![image](https://user-images.githubusercontent.com/70719873/181414314-427ea7e8-8ff8-4fea-8cd2-f60050b7550d.png)
![image](https://user-images.githubusercontent.com/70719873/181414958-dafcd788-ad74-44e6-82d9-cc46d9bfea85.png)
![image](https://user-images.githubusercontent.com/70719873/181415449-151fb946-c634-4df1-b208-d0cf62387999.png)

**Comment by songeric1107** [comment]
@jorvis , I compare the saved analysis from before and a new one that I tried just now, I agree with @beamilon  that there might be a bug for umap display which leads to different UMAP display although I use the same parameter.



_**test dataset with raw values**_
https://umgear.org/analyze_dataset.html?dataset_id=e084843c-32b0-4551-7307-0942eaa45756


_**saved analysis from before:**_
![Screen Shot 2022-07-28 at 10 48 50 AM](https://user-images.githubusercontent.com/6730079/181566581-df95afea-28e8-4b08-9774-a2117739389e.png)


**_new analysis today:_**

![Screen Shot 2022-07-28 at 10 51 50 AM](https://user-images.githubusercontent.com/6730079/181567688-b662c282-1c2b-405a-9cac-101cd41f5747.png)

**Comment by adkinsrs** [comment]
We haven't really messed with how these plots are generated, but I'll take a look today

**Comment by adkinsrs** [comment]
I believe this is definitely a scanpy issue.  See https://github.com/scverse/scanpy/issues/2291 for examples.  

This person was using scanpy v1.8.1 and I am using 1.7.2 to get similar findings as the plots above

**Comment by beamilon** [comment]
Yes, that is definitely it. Was the scanpy version related to gEAR updated recently?

**Comment by adkinsrs** [comment]
I believe that scanpy was last updated around May this year, around the time of the workshop then.  I remember @jorvis having to downgrade scanpy from ~1.8.1 to 1.7.2 due to some other reported issues (#318)

**Comment by adkinsrs** [comment]
<img width="1040" alt="Screen Shot 2022-07-29 at 11 16 55 AM" src="https://user-images.githubusercontent.com/5665914/181790892-5414dced-4379-40f6-ae85-a0fe95b3e435.png">

Looking at the scanpy code, I see they changed something in the umap calculations script 9 months ago that addressed an issue with some tool called umap-learn, and I believe that changed messed up something.  The `scanpy.tl.umap` function now has a "maxIter" function that is turned off by default and auto-calculated based on the shape of the data.  It seems that the default is 500 if the dataset has less than 10000 observations and 200 if it has more.  I set maxIter = 200 and got the UMAP plot above

**Comment by adkinsrs** [comment]
edited gear-prod directly to fix this issue in this file, since the workshop is approaching

**Comment by bsierieb1** [comment]
can confirm that setting `maxiter=500` in `scanpy.tl.umap` fixed the issue for me
