### ISSUE TITLE
Query about pre-processing of P7, Mouse, cochlea, scRNAseq dataset (Hertzano/Ament)

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#389]
**From:** MacKenzie Wilke

**Email:** sarvism@myumanitoba.ca

**Server IP:** 10.142.0.16

**Msg:** I was wondering if I could have any information regarding the standard processing, quality control and normalization processes of this scRNAseq dataset. For example, was the Seurat pipeline used?

Here is the link to the dataset I am talking about: https://umgear.org/p?s=7e32dd02 

**Tags:** ['gEAR,cochlea,scRNAseq,p7']

**Screenshot:** None

**Comment by jorvis** [comment]
Kevin is looking into this one but I can't assign him the ticket due to group issues.

**Comment by Kvnrose** [comment]
Should I email directly or do we have a gEAR helpdesk email?

**Comment by jorvis** [comment]
I just e-mail directly but make the subject line reflect the title, like this:

Re: Query about pre-processing of P7, Mouse, cochlea, scRNAseq dataset (Hertzano/Ament)

**Comment by Kvnrose** [comment]
Hello Mackenzie,

This dataset was processed in Seurat and the Seurat object was then imported into gEAR.

Seurat Parameters used:
1) Quality Control (min.cells = 3, min.genes = 200, mitochondrial.content < 20%)
2) Normalization via "LogNormalize" method with scale.factor of 10,000
3) Variable genes - 2000
4) PCs used in visualization = 10
5) Resolution of tSNE = 0.6

Best,
Kevin

**Comment by Kvnrose** [comment]
from Mackenzie:

Thank you very much Kevin!

MacKenzie
