### ISSUE TITLE
Add descriptions for gene carts

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#392]
To help users better understand what goes into particular gene carts (and if a particular cart is useful to them), gene cart descriptions should be made available and displayed somewhere users can see.

**Comment by jorvis** [comment]
Funny, we're already accepting this information but not displaying it.

![Screenshot from 2022-07-29 14-48-03](https://user-images.githubusercontent.com/330899/181833397-161fba94-c12d-4b86-9f5e-075921233278.png)

**Comment by jorvis** [comment]
Joe - assigning to you and can be closed after grant update text is written.

**Comment by JPReceveur** [comment]
Grant text added
