### ISSUE TITLE
Add portal to Jenkins for monitoring

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#397]
The gEAR portals should be added to our local Jenkins for continuous monitoring

**Comment by adkinsrs** [comment]
gEAR and NeMO Analytics portal health checks are set up on Jenkins. The current test is to search a gene and check for the dataset display grid panel.

**Comment by JPReceveur** [comment]
Added to Accomplishments-2023 related to FAIR/TRUST
