### ISSUE TITLE
Unable to download data from GEO ID GSE137299

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#401]
**From:** Feryal Ladha

**Email:** ladhaf@myumanitoba.ca

**Server IP:** 10.142.0.16

**Msg:** I am trying to download the data from the "P7, mouse, scRNA-seq, cochlear epithelium (Kelley)" data set but cannot find the "genes.tab", "expression.tab", and "observations.tab" files. A link to where I can download these files would be much appreciated. 

**Tags:** ['download']

**Screenshot:** None

**Comment by songeric1107** [comment]
send an email to the user with the screenshot about dataset downloading and the link of wiki page.
