### ISSUE TITLE
Datasets for backfilling

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#404]
Could you send along a dump of the datasets uploaded to gEAR since November so I can get started backfilling them? It looks like the last entry in the previous list was 11/18/21.

**Comment by songeric1107** [comment]
send an email to you with new datasets

**Comment by jorvis** [comment]
OK, so is this done?

**Comment by JPReceveur** [comment]
If it is possible, could you pull the dataset list the same way you pulled it for Jain? 

The list Yang sent has all the dataset names but not the other metadata columns that help to narrow down the dataset and cell types for backfilling. If its a pain, no worries I can work from the list Yang sent

**Comment by jorvis** [comment]
I've generated this and e-mailed it to you @JPReceveur.  Please re-open if there is an issue.

**Comment by JPReceveur** [comment]
Hi Joshua, Could you generate a new list of datasets from Aug 10th until now to be backfilled for the FAIR/TRUST work?

**Comment by jorvis** [comment]
Sent to e-mail

**Comment by JPReceveur** [comment]
@jorvis Can you dump out an updated list of datasets in gEAR for us to use for backfill/ finding pubmed IDs?

**Comment by jorvis** [comment]
Yes, for what date range?

**Comment by JPReceveur** [comment]
From 2023-03-06 to now
