### ISSUE TITLE
Dataset preview images in dataset explorer do not show for certain displays

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#406]
Depending on the display chosen as default, when datasets are viewed in the dataset explorer, most show up with 'No preview image found' (e.g. the first two datasets below are UMAPs) while others (e.g. violin plots have a preview image. Since a large proportion of what people show are UMAPs, could this functionality be updated to allow for preview displays of additional plot types (Alternatively if most of the thumbnails are going to be 'no preview' should we think about removing the thumbnail)? 

<img width="1343" alt="Screen Shot 2022-08-12 at 9 10 06 AM" src="https://user-images.githubusercontent.com/28451557/184360734-d537d837-1f94-4c55-a893-c1cdb3afdcfb.png">

**Comment by adkinsrs** [comment]
For reference, at the time of this ticket, only plots generated within Plotly were converted into static PNGs for the dataset previews. tSNE/UMAP, svg, and multi-gene plots were not saved.
