### ISSUE TITLE
Prof

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#408]
**From:** Felix Schweizer

**Email:** felixs@ucla.edu

**Server IP:** 10.142.0.16

**Msg:** Is there a plan to incorporate SWNE in addition to tSNE and UMAB into gEAR? Or maybe its already there and I cannot find it.

**Tags:** ['']

**Screenshot:** None

**Comment by jorvis** [comment]
I have e-mailed the user thanking for the feedback and guided them to follow issue #409
