### ISSUE TITLE
Using zoom function disrupts profile switching

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#414]
If you zoom in on a dataset in a profile and then try to switch the profile to a second profile, the only dataset shown remains the one you zoomed in on. Could this be updated so that hitting switch profile brings users to the new profile's layout rather than staying on the zoomed in dataset?

Steps to replicate:
- Search gene in the hearing profile
- Use the zoom function to view a dataset
- Click the select profile dropdown and pick a different profile to switch to

**Comment by adkinsrs** [comment]
This should be resolved in gEAR 2.0, as the act of searching will reset to the regular display view
