### ISSUE TITLE
copyright for images? 

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#424]
**From:** Alexandra Kaufman

**Email:** alexandra.kaufman@regeneron.com

**Server IP:** 10.142.0.16

**Msg:** Hi all! I am interested in using images from the gEAR for a poster, and wanted to ask about the copyright for images. Are they public use, or copyrighted? Is it ok to use them if we cite the gEAR and the relevant dataset? 

Thank you! 

**Tags:** ['']

**Screenshot:** None

**Comment by jorvis** [comment]
Writing the user now.
