### ISSUE TITLE
Ability to hide sample names: Multigene curator

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#427]
In the multigene curator, it would be useful to have the ability to hide the sample IDs along the x axis without having to do a matrix plot. 
<img width="464" alt="Screen Shot 2022-09-06 at 12 52 16 PM" src="https://user-images.githubusercontent.com/28451557/188694708-f1a4ec99-bfe7-455b-b7bd-98c9b808a4a7.png">

**Comment by adkinsrs** [comment]
I used to hide them by default for the raw sample heatmap. Should be easy to implement that option

**Comment by adkinsrs** [comment]
Only going to apply this option to the heatmaps

**Comment by adkinsrs** [comment]
Resolved with 863459d7fe27791a570fb20a9a4e2995f79cc708
