### ISSUE TITLE
keep the title of each dataset in the consistent way

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#430]
For search purposes, each word in the title for each dataset should be separated with a space, even for the parentheses. 

for example, 

_Wrong version:  utricle,violin(xx lab), entrezID_

- --"utricle,violin(xx lab)" is considered as one word, no result will be found if searching for "utricle" only.

_**Correct version**: utricle, violin (xx lab), entrezID_

**Comment by songeric1107** [comment]
@JPReceveur could we add this to the manual?

**Comment by jorvis** [comment]
I'm not sure it needs to be added to the manual, it's normally just what people do, is it not?

**Comment by songeric1107** [comment]
or maybe add to our "note" for future curation.

**Comment by songeric1107** [comment]
put in the wiki page for internal use.  https://github.com/jorvis/gEAR/wiki/title-format-for-each-dataset
