### ISSUE TITLE
Reducing browser window results in header button with no functionality

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#431]
Related to the discussion in #239, If you make the browser window small enough so it changes the header names to the hamburger icon, clicking on the icon doesn't give you a dropdown menu of the various header links.

<img width="695" alt="Screen Shot 2022-09-07 at 2 11 23 PM" src="https://user-images.githubusercontent.com/28451557/188949579-aea18590-6fb0-48aa-9dfd-c96f685bea19.png">

**Comment by adkinsrs** [comment]
Marking this as a low-priority task. We currently do not support or implement a mobile version of the site, but maybe there was work in attempting this in the past.

**Comment by adkinsrs** [comment]
Closing this ticket as the UI refactor should address this indirectly
