### ISSUE TITLE
Implement a lock file in case multiple people run projectR on the same dataset/pattern simultaneously

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#441]
Suggestion:

Implement a lock file in case multiple people run projectR on the same dataset/pattern simultaneously (like in a workshop

_Originally posted by @adkinsrs in https://github.com/IGS/gEAR/issues/243#issuecomment-1246876425_

**Comment by adkinsrs** [comment]
Currently implementing a lockfile using the python `fcntl.flock` module function, and am naming the lock file based on the projection output CSV filename with .lock appended.

Occasionally I get `Truncated or oversized response headers received from daemon process 'api': /var/www/api/api.wsgi, referer: http://localhost:8080/index.html?multigene_plots=0&projection_source=f206c5bc&projection_algo=pca` or something similar, which comes from Apache rather than Python.  This is problematic as I typically use Python to clear the lock files either through resolving an error or the projectR API call finishing successfully. 

I need to either write some exception handling for Apache, if that is possible, or we may need to look into a cron to sweep away lock files on occasion (which is not ideal at all).

Another issue I realized is that the projectR API call actually creates the UUID to be used in the projection output csv file (where the lock file is named after). If two users run at the same time, two separate UUIDs will be created and the lock file will be ignored (so we'll get two duplicate outputs of the projectR run under different UUIDs). I guess I could abandon the UUID approach to explicitly name the output file after the dataset, genecart, and all options in use but that feels like it could get hairy if options for the projectR run were to be expanded.

**Comment by adkinsrs** [comment]
https://stackoverflow.com/a/7985612

If I write the process ID (PID) inside the lock file, it would allow for a shell script to cross-check active processes to determine if the lock is stale, then clean up.

**Comment by adkinsrs** [comment]
[f629ce5](https://github.com/IGS/gEAR/commit/f629ce50008aa6f7f7c2ca467bdb7137d08e5dfd) has the lock file commit code

I also added the PID in the lock file, but sweeping stale locks is going to be difficult.  It seems that the PID saved is an apache process, which is persistent except for unexpected shutdowns.

**Comment by jorvis** [comment]
Haven't looked at the implementation but might have to be careful regarding PID as there is a single apache parent daemon running but with multiple threads.  Not sure if that effects anything here.

**Comment by adkinsrs** [comment]
The assigned pid ends up being one of the child Apache processes

**Comment by adkinsrs** [comment]
Code is ready and works. [60cc714](https://github.com/IGS/gEAR/commit/60cc714ebc2c81425621d09c1b0ef4c42132a4c9)

However I commented it out because I feel the potential for occasional stale lockfiles (from apache response header issues) and cleanup involved is more likely than the chance the same projection is run again before the other finishes.

**Comment by adkinsrs** [comment]
resolved with [a7226b6](https://github.com/IGS/gEAR/commit/a7226b6d051297aa637d0c6833c9d1fee9bf2c88)
