### ISSUE TITLE
Functional annotation not updating if the next gene is not found

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#445]
I looked for the gene Mau2 and functional annotation, deafness annotation and expression (top figure). I then search for the gene Adss2 which was not found in any of the datasets in the profile, while the deafness annotation updated to the new gene, the functional annotation stayed for gene Mau2 (bottom figure). 
![image](https://user-images.githubusercontent.com/70719873/190498642-68279709-b7b2-4a54-99b4-5e68dd02ac89.png)
![image](https://user-images.githubusercontent.com/70719873/190498796-b9c4c851-a731-4898-aa6d-287d87f3c615.png)

**Comment by jorvis** [comment]
Taking ownership of this one since I'm redoing a lot of this right now on a branch anyway.
