### ISSUE TITLE
Senior Computational Biologist

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#452]
**From:** Damon Polioudakis

**Email:** dpolioudakis@primemedicine.com

**Server IP:** 10.142.0.16

**Msg:** Hi,
I'm really impressed with the number of datasets on the gEAR portal.  The visualizations are quite helpful for the epigenetic datasets for a first pass.  I was wondering if there is a way to download a few of the actual bigwig files they are derived from for some of the mouse datasets?  It may be right in front of me and I'm missing it.
Thank you
-Damon

**Tags:** ['']

**Screenshot:** None

**Comment by jorvis** [comment]
I've written Jay to see if he can respond here.

**Comment by jorvis** [comment]
I responded to the submitter.
