### ISSUE TITLE
projectR - Show top N upregulated/downregulated genes in each pattern

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#456]
@hertzron had a suggestion to show the top 10 up- and down-regulated genes per pattern for the selected weighted genecart when performing projection.  That way, the user has a bit more of an idea of what the pattern represents biologically when comparing it to a dataset's plot.

It's worth noting that unweighted genecarts have the same weight per pattern

**Comment by adkinsrs** [comment]
<img width="971" alt="Screen Shot 2022-10-19 at 3 28 38 PM" src="https://user-images.githubusercontent.com/5665914/196785803-94eaff4e-e93a-4e4e-8128-903ae992175a.png">
<img width="1110" alt="Screen Shot 2022-10-19 at 3 28 57 PM" src="https://user-images.githubusercontent.com/5665914/196785876-95244a02-8611-4210-800c-ea3e9fb8014e.png">

Progress update.  In these top two photos the 10 genes with the highest and lowest weight for each of two patterns is placed in an info card at the top of the page. I still need to test situations where the panel shows and hides.

The biggest problem I am having right now is the proper wording.  If we are using patterns (PC1, p1, etc) as weights, then using "upregulated" and "downregulated" is not quite the right terminology, as it is more that the genes with the highest weights are the most representative or have the most contribution (in which case, I do not know if want to include the genes with the lowest weights then).  However, if we are using something like Log2FC as a weight, then it does make more sense to keep "upregulated" and "downregulated".  Ideally I would love to find a wording that encompasses both these scenarios so that I do not have to create conditions for each.

A second, minor issue is whether it is best to show the top 10, or should we just condense it to the top 5.  The top 10 is more informative but can be construed as looking "busy", especially where the genes are in all-caps (see picture above).

**Comment by hertzron** [comment]
Shaun,
Really nice progress. How about top 5 with a button to click to see full list in a new page?
Best,
Ronna

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by adkinsrs** [comment]
<img width="950" alt="Screen Shot 2022-10-20 at 10 54 20 AM" src="https://user-images.githubusercontent.com/5665914/196983544-006d2821-2f3a-46c9-ac84-fd4138dcaea4.png">

This genecart only had 20 genes.  After clicking the "View all genes with weights" button, a new tab is opened with a simple table of genes and weights, sorted by weight.
<img width="217" alt="Screen Shot 2022-10-20 at 10 54 43 AM" src="https://user-images.githubusercontent.com/5665914/196983668-d9b7d60f-27cf-4bc7-ac08-0d4303a693de.png">
