### ISSUE TITLE
X axis label hidden on faceted violin plot but customize option still given

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#458]
In the dataset curator, when you facet a violin plot, it hides the x-axis label and the customize axis title under advanced tools doesn't have any functionality. Could this plot type be altered so plots faceted by row can have x-axis titles? Alternatively, if we don't plan on implementing that ability, should the x-axis title customization be removed if users select a facet (so users aren't expecting to customize something that is hidden either way)?
<img width="1400" alt="Screen Shot 2022-10-11 at 9 23 22 AM" src="https://user-images.githubusercontent.com/28451557/195104097-f1ef914f-1996-4aa4-973f-d02f10e05d32.png">

**Comment by adkinsrs** [comment]
I think the change that needs to be made is to have the x_title or y_title be implemented when facets are added. Seems that the function https://github.com/IGS/gEAR/blob/0b3c171e5ac27d435f09d374018ae07ecf42ace1/lib/gear/plotting.py#L226 needs to be modified as it only accounts for x_title in facet_cols and y_title in facet_rows

**Comment by adkinsrs** [comment]
This is a bit tricky.

I can remedy the violin plot by commenting out the `_update_axis_titles` function call and pass in x_titles and y_titles to the Plotly `make_subplots` call.  However, the "tsne/umap dynamic" plot type seems to have a bug where the axis title shows in every facet.

**Comment by adkinsrs** [comment]
Committed, so I am closing.

I realized that there are two approaches.  Any non-violin plot that uses plotly express (where facet titles have to be created manually) and any violin plot which allows for use of `make_subplots` for quick axis title setting.
