### ISSUE TITLE
GCID uploading error

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#466]
gcid uploading failed. I tested the files in gEAR; I could upload the file without problems.  @adkinsrs , could you please check it? 

![Screenshot 2022-11-03 at 9 20 34 PM](https://user-images.githubusercontent.com/6730079/199866607-bf36196a-7695-4024-acc7-f552912cefba.png)

**Comment by adkinsrs** [comment]
I am guessing this requires adjusting the upload limit on the PHP conf file. Will check sometime today

**Comment by songeric1107** [comment]
It is a small RNAseq dataset.

**Comment by jorvis** [comment]
OK, please try again now.  The issue was the 'locate' command was showing php.ini from PHP 7.4, but wasn't updated after PHP 8.x was installed.  While the php.ini for 7.4 was modified for larger uploads, the one for 8.x wasn't.  I've fixed this and restarted apache (and updated the locatedb)

**Comment by songeric1107** [comment]
works. thank you
