### ISSUE TITLE
Increase the size of multigene display box to three panels

### ISSUE THREAD

**Issue by nsuvarnaiari** [IGS/gEAR#467]
Hi Josh,

Could you please increase the size of multigene display box to 3 planels  for https://gcid.umgear.org/p?l=0b32a4fd?

Thanks,
Suvvi

**Comment by adkinsrs** [comment]
Defaults on every portal is to set "mg_grid_width" to 4 (out of 12 columns). In the past I have manually changed some db entries to either 6 or 12 for both gEAR and GCID

**Comment by jorvis** [comment]
Shaun corrected this layout, and I modified the schema and code so that 4 will explicitly be the default in single-gene view, and 12 the default in multi-gene view.

I have updated the schema on all instances (production and devel) but only updated code on devels.
