### ISSUE TITLE
Ensure previews can be generated for all datasets in explorer

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#470]
Currently not happening for SVGs, tSNEs, multi-gene

**Comment by adkinsrs** [comment]
Also I believe the "save_dataset_display.cgi" is not retrieving a dataset ID for the dataset, since that ID is being replaced with "None" in the saved static image filenames

**Comment by adkinsrs** [comment]
Tested and got tSNE/UMAP plots saved as preview images. Also fixed a bug where multi-gene plots were not rendering

SVGs are going to be a bit more tricky. The client-side JS code renders the SVG whereas the API server-side code returns the values for the SVG. Python does not have any native SVG creation code it seems, so I would need to install a package, and essentially recreate the SVG in Python.

**Comment by jorvis** [comment]
We don't need to actually color the SVG. Instead, let's just show the SVG there and then can use CSS to remove any demo coloring so just the shape is shown.

**Comment by JPReceveur** [comment]
This ticket can also be closed when the above ticket is complete https://github.com/IGS/gEAR/issues/406

**Comment by adkinsrs** [comment]
<img width="1210" alt="Screenshot 2022-11-16 at 3 07 37 PM" src="https://user-images.githubusercontent.com/5665914/202283468-4373e57f-3956-4e71-8e8d-b54dbd139519.png">

Still rendering "previews" on gear-devel to test functionality, but at least tSNE and multi-gene displays work now

**Comment by adkinsrs** [comment]
<img width="1200" alt="Screenshot 2022-11-17 at 2 11 16 PM" src="https://user-images.githubusercontent.com/5665914/202536960-ec6cc7c8-662f-412e-bf42-4af17a89681f.png">

SVGs now show, though the blank svg is a bit hard to see

**Comment by adkinsrs** [comment]
af1cc7e24f50db31799752ff3d34105526bb7153
