### ISSUE TITLE
Sadkins testing screenshots

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#473]
**From:** Shaun Adkins

**Email:** shaun.adkins@gmail.com

**Server IP:** 10.142.0.14

**Msg:** mwahaha!

**Tags:** ['']

**Screenshot:** https://umgear.org/contact_screenshots/ca684a5a-1a29-41c9-b0c8-abc7893fdb8a.jpg

**Comment by adkinsrs** [comment]
Screenshot has wrong URL domain, as I sent this from NeMO Analytics
