### ISSUE TITLE
Sadkins testing screenshots

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#474]
**From:** Shaun Adkins

**Email:** shaun.adkins@gmail.com

**Server IP:** 10.142.0.16

**Msg:** Mwahaha!

**Tags:** ['']

**Screenshot:** https://umgear.org/contact_screenshots/de191c6c-8b05-4d94-b461-2d0cf21dca96.jpg

**Comment by adkinsrs** [comment]
ADMIRE MY SCREENSHOT!
