### ISSUE TITLE
Front page - Create single-gene/multigene toggle

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#48]
Currently I added the font awesome gear/gears icons as a placeholder, but it would be nice to have a formal button toggle for this.

Single Gene (to left of magnifying glass)
<img width="632" alt="Screen Shot 2021-10-06 at 4 02 13 PM" src="https://user-images.githubusercontent.com/5665914/136274974-428ca789-6ad0-4ced-9844-f82aa7a58d9a.png">

Multigene toggle
<img width="627" alt="Screen Shot 2021-10-06 at 4 02 18 PM" src="https://user-images.githubusercontent.com/5665914/136274993-0226c530-9d04-4e65-922f-3b2a4bb78d77.png">

Ronna wants Lance to handle the graphic design (and I can implement into the page)... @victor73 can you ask Lance for help on this?

**Comment by jorvis** [comment]
Yeah, working on the spacing with Lance.

**Comment by jorvis** [comment]
Updated in commit ed1942e
