### ISSUE TITLE
Research Scientist

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#485]
**From:** Royce Clifford

**Email:** r2clifford@health.ucsd.edu

**Server IP:** 10.142.0.16

**Msg:** I have a question on the multigene displays. 
The heat maps are wonderful. Is there any way to download the information within the graphs themselves, i.e., the mean gene expressions that one can obtain by mousing over the map itself?
Thanks.
Royce

**Tags:** ['datasets,expression']

**Screenshot:** None

**Comment by adkinsrs** [comment]
This is currently not possible but we can make a ticket to add this in a future release.

If the user is plotting all replicates in their heatmap (i.e. no averaging replicates or conditions to create a matrixplot) then they could just download the h5ad dataset to get the expression values. But I imagine this is not their case.

**Comment by adkinsrs** [comment]
closed due to inactivity
