### ISSUE TITLE
Primary analysis "Labeled tSNE" window missing for some datasets

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#498]
@jorvis 
@adkinsrs 
@songeric1107 
Going to the single cell workbench and selecting "Primary analysis", I noticed that for some datasets, 2 windows appear: Find marker genes AND Labeled tSNE. For other datasets, only Find marker genes appears. Below are two examples. I don't know if it is a bug or if it is dataset dependent.

![image](https://user-images.githubusercontent.com/70719873/216113820-ef9cbbe3-9f81-4a82-a821-e886b556172c.png)
![image](https://user-images.githubusercontent.com/70719873/216114127-0e866146-24e6-4f73-860e-e2fffa2a43ca.png)

**Comment by jorvis** [comment]
When a user uploads their dataset there are two types of pre-computed analysis they can include - tSNE/UMAP and cluster information.  If the cluster information is present marker genes can be computed.

P2, mouse, scRNA-seq, cochlea (Hertzano/Ament) - Has both tSNE and clustering data uploaded
Single cell RNA-Seq analysis of embryonic mouse spiral ganglion neurons (Sanders & Kelley 2022)  - Has only UMAP

The interface reads whether these datasets have these attributes and only shows the available options.
