### ISSUE TITLE
Pressing enter to search on gene search page results in 'gene not found'

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#501]
Using the keyboard enter key rather than the interface search button is causing some issues related to genes not being found when they are present in a dataset.

Steps to replicate: 
On homepage, search for a gene (e.g. sox2) in the default profile and hit search
On the profile display page, type a new gene in the search gene box (e.g. pou4f3) and press the enter key (not the search button)

<img width="1449" alt="Screenshot 2023-02-03 at 2 45 52 PM" src="https://user-images.githubusercontent.com/28451557/216693930-045042ca-3836-4fb9-8112-818c03d602a9.png">

**Comment by adkinsrs** [comment]
My initial thoughts, is that Enter is a way to submit an HTML form element, but on index.js we have various .onclick events bound to clicking the search button(s)

**Comment by adkinsrs** [comment]
Committed ([3cb4c56](https://github.com/IGS/gEAR/commit/3cb4c56e503b7ef821468012df8beaaf5db17c7f)) and pushed to production and devel (works)
