### ISSUE TITLE
System won't accept my password, won't email me new one

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#502]
**From:** Gabor Halasz

**Email:** gabor.halasz@regeneron.com

**Server IP:** 10.142.0.16

**Msg:** Hi-
Thanks for making this great tool. Unfortunately I can't seem to log in, and when I try the "forgot password" route, the system says "looking for your password" and shows that spinny thing, but nothing else happens. Thank you for your help,
Gabor

**Tags:** ['Password']

**Screenshot:** None

**Comment by jorvis** [comment]
This has been fixed.  Google changed the way they supported application passwords.  

https://www.letscodemore.com/blog/smtplib-smtpauthenticationerror-username-and-password-not-accepted/
