### ISSUE TITLE
Planning meeting on 3/28 - brain initiative and tool demo

### ISSUE THREAD

**Issue by RLC-DCPPC** [IGS/gEAR#512]
Ronna to describe grant
Brian to present tool

**Comment by adkinsrs** [comment]
This is at 2pm Eastern

**Comment by RLC-DCPPC** [comment]
From Anup: 

FAIR/TRUST changes
Automating NeMO -> NeMO Analytics
Implement UI changes suggested by CP

**Comment by RLC-DCPPC** [comment]
- For April 19
- ownership (who owns after its converted and transferred to NeMo-A?)
- user importing 10 but one fails, what to do? (Anup?, Ronna?)
- another gEAR paper (where and when)? Topic(s)? [after UI rewrite, NeMO import, by end of '23?] Nucleic acid research volume in summer '24
