### ISSUE TITLE
Is ProjectR implemented or is it still on the work?

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#518]
@jorvis
@adkinsrs 
When I try to use projectR with a gene cart as the source to project on any profiles, I get the following message: (404, "NOT_FOUND - no exchange 'message' in vhost '/'")
![image](https://user-images.githubusercontent.com/70719873/229159385-73e29609-5a32-4390-97c2-0d857bcfd192.png)

**Comment by adkinsrs** [comment]
@beamilon care to try again?

**Comment by adkinsrs** [comment]
Just hit "search" again, and that last one should run soon.  We still need to get the apache configuration perfected to handle these situations where a process is dropped

------------------------------------------------------
Ricky "Shaun" Adkins
Bioinformatics Software Engineer II
Institute for Genome Sciences
University of Maryland, School of Medicine
Phone (410) 706-6766
________________________________

**Comment by beamilon** [comment]
Doesn't work. I tried several times over the last few days and it never worked with that specific profile.
![image](https://user-images.githubusercontent.com/70719873/229163001-6b793ff9-6033-4b2c-a647-82306b5c3050.png)

**Comment by beamilon** [comment]
Actually, for this profile, none of the datasets work with 'compare gene expression' or create multigene display. So something is missing when the datasets were uploaded.

**Comment by adkinsrs** [comment]
Was about to post to it seems one of the dataset projection outputs indicates there are 4097 samples in one of the datasets, but the h5ad file seems to have 1181611 observations to 1 gene.

**Comment by beamilon** [comment]
@adkinsrs 
The problem is back: trying ProjectR returns "404, "NOT_FOUND - no exchange 'message' in vhost '/'"

**Comment by adkinsrs** [comment]
Try again now.... did not realize that the VM was restarted (which kills the RabbitMQ consumer)

**Comment by adkinsrs** [comment]
Relates to #521

**Comment by beamilon** [comment]
Working. Thanks.
