### ISSUE TITLE
Epiviz results not displaying all track

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#529]
When viewing the Epigenetic tracks in a profile, the tracks are not displaying. Replicated in several profiles.

https://umgear.org/index.html?multigene_plots=0&layout_id=e2d98834&gene_symbol_exact_match=1&gene_symbol=sox2

<img width="1465" alt="Screenshot 2023-05-02 at 1 37 34 PM" src="https://user-images.githubusercontent.com/28451557/235742357-22278c99-8d12-49f0-be40-56b996877590.png">

**Comment by jorvis** [comment]
Thank you, fixed.  The drive wasn't mounted.
