### ISSUE TITLE
To have the ability to update the cluster names after saving an analysis

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#530]
@jorvis 
@adkinsrs 
It would be very useful to be able to update the names of the clusters from a previous analysis:
For example, I have a dataset and create an analysis up to the 'find marker gene' step and save it either with the default cluster names (0, 1,2...) or with temporary names. Then, after checking additional gene expressions, I want to refine the names of the clusters without having to start the analysis from scratch. At the moment, doing that results in a total scramble of the original clusters. Below is an example where I only changed what is in parenthesis without changing the word before it. When I click on 'rerun with labels', my original clusters are reassigned randomly.
![image](https://github.com/IGS/gEAR/assets/70719873/c1447b20-ce23-4bce-af09-e26fc0071e39)

**Comment by adkinsrs** [comment]
@beamilon when you go back to refine the cluster names, are you leaving the page and then returning/reloading the analysis, or are you changing the names without navigating away from the page?  I ask because there is obviously a step somewhere where the labels are not respecting the cluster mapping or sort order, and this would help to get a better picture of that.

**Comment by adkinsrs** [comment]
So I can confirm if I rerun with labels twice without leaving the page. The order appears to be consistently correct in the script request payload, but inside the script, the louvain groups are switched to the wro
<img width="569" alt="Screenshot 2023-06-26 at 11 28 39 AM" src="https://github.com/IGS/gEAR/assets/5665914/a2d18f86-e0a0-42cf-9a12-e05131cd722d">
ng samples (see photo).

**Comment by adkinsrs** [comment]
Seems like the louvain categories are sorted and then the new labels are assigned, so you can predict where the new label will go.  I'm going to add a column "louvin_order" that will allow use to ensure the correct categories are present.  We can copy that into our "louvain" field before relabeling.  I will have to figure out how this will play with "merging" from ticket #533 but shouldn't be a big deal.

**Comment by adkinsrs** [comment]
also addressing all of this on the branch at https://github.com/IGS/gEAR/tree/533-single-cell-workbench-explore-filtering-out-clusters-or-merging-clusters

**Comment by beamilon** [comment]
@adkinsrs 
Thank you Shawn. I will try your trick about changing the resolution for the analysis I already did.

**Comment by adkinsrs** [comment]
Sounds good.  You may have to redo the marker gene and comparison steps after but it saves you a couple of steps.  Also, my commits are not up on the server yet but the workaround should work, as changing the resolution tells the louvain step to recompute it again.
