### ISSUE TITLE
Annotation not updating after new gene selection

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#531]
See screenshot.  URL is used for Atoh1, then a gene is searched and clicked, but annotation for Sox2 isn't shown.

![Screenshot from 2023-05-12 14-24-13](https://github.com/IGS/gEAR/assets/330899/b57f9827-3658-4786-aa5a-fea29955fa43)

**Comment by beamilon** [comment]
@jorvis
@adkinsrs
I noticed that this issue is still a problem.

**Comment by jorvis** [comment]
Closing this since this has been completely reimplemented in v2

**Comment by jorvis** [comment]
And actually closing.
