### ISSUE TITLE
Single-cell Workbench: Explore filtering out clusters or merging clusters

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#533]
Suggested by @hertzron

It would be nice to merge louvain clusters into a super-cluster for downstream analysis, or allow the user to filter out clusters for downstream analysis. The "louvain" step saves to adata.obs so it should be easy to implement some of this.

@songeric1107 feel free to correct this if I am misunderstanding some of the objective

**Comment by songeric1107** [comment]
there are two ways to subcluster: 
1. simply subset certain clusters and plot directly. 
2. or subset certain clusters and recluster

**Comment by adkinsrs** [comment]
Since the "louvain" step is saved in adata.obs it is easy to filter or merge clusters. I think the issue is how best to do this in the UI.

For filtering:
* Maybe a checkbox to select which clusters to keep for downstream analysis. All clusters will be checked by default.

For merging:
* A button that brings up a modal and lets you pick 2 or more clusters, and they will be merged on the first cluster's ID. The plot will also be updated to reflect the new merge. I think it's best that this button only handles 1 merge process at a time, since trying to perform multiple merges at once could get dicey with checking clusters.

**Comment by adkinsrs** [comment]
When rerunning with labels based on the marker genes, we could also have a "merge similar labels" button that will quick-merge those clusters together.

**Comment by adkinsrs** [comment]
Got merging clusters to work, but I need to do more work to ensure the correct new clusters are respected downstream. Basically I added a "merge clusters" checkbox that will merge any clusters with duplicate labels when rerunning with labels.  If unchecked, the standard validation checking will happen where the box is red if duplicated labels are found.

<img width="653" alt="Screenshot 2023-06-26 at 3 36 17 PM" src="https://github.com/IGS/gEAR/assets/5665914/aa88d1bd-96c0-4b28-890e-d69b92df8294">
<img width="579" alt="Screenshot 2023-06-26 at 3 47 25 PM" src="https://github.com/IGS/gEAR/assets/5665914/cf290726-a7c5-4427-8fea-e9fc5c895a0e">
<img width="350" alt="Screenshot 2023-06-26 at 3 50 29 PM" src="https://github.com/IGS/gEAR/assets/5665914/c8755ef3-8054-44e3-a0b9-8361c334c908">

For some examples that demonstrate the merging, check out clusters 13+14 in the lower left as well as 9+21 at the top.

I believe this will resolve 90% of the "merge clusters" requests, particularly if the user wants to decrease louvain resolution to get fewer clusters. I cannot see too many users wanting to perform custom "pick and choose" merging, even though that was what I suggested in an earlier comment

**Comment by hertzron** [comment]
Thanks, Shaun. I do think many users will want to build a new dataset starting with just a handful of picked clusters.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by adkinsrs** [comment]
My next step will be to add filtering of clusters.  I just need to ensure the updated clusters (merged or subsetted) are respected in the marker gene and compare steps, which is easier said than done.

**Comment by adkinsrs** [comment]
@jorvis suggested creating a one-off script which can be used to get all previous louvain analyses compatible with these changes (essentially adding a "orig_louvain" numerical ID)

**Comment by adkinsrs** [comment]
May have a way to make this backwards-compatible.  Basically for each cluster I need to make a data structure like so

```javascript
// old group labels saved before being mutated into the new ones
cluster = {"old_label":old_label, "new_label":new_label, "keep":true}
clusters.push(cluster)
```

If I can ascertain the old group labels (which should be present in the `current_analysis.group_labels` array before the "rerun with labels" list is made, I can easily map old to new as well as know the numerical cluster index. And as said before, once we merge/filter to have a different number of clusters, we update `current_analysis.group_labels` to the revised ones.

**Comment by adkinsrs** [comment]
This commit should fix back-compatibility problems now.  When the user saves marker genes, the "labels" are listed as the numerical cluster IDs, but the current analysis "labels" will now be updated once relabeling of louvain is complete, as opposed to before that happens. This means, that upon success, the most recent labels will be saved to JSON and can be easily restored.

**Comment by adkinsrs** [comment]
@beamilon, @JPReceveur , @songeric1107 can any of you test the new functionality on devel.umgear.org and let me get some feedback on it.

Things I want to know:
- Does merging clusters, filtering clusters, and relabeling clusters work and is it easy to understand
- Does the flow of performing the initial clustering, finding marker genes, and then manipulating the clusters make sense
- Does everything downstream work? I did not update the "find marker genes" step for when clusters are merged, since I figure the markers would mostly be the same but I can do that.  I also added some code in the "compare genes" step to allow it to work in more recent versions of scanpy
- Any other general feedback?  Suggestions, bugs, etc.

**Comment by beamilon** [comment]
@adkinsrs
I went on devel and chose a single cell dataset but I am not sure where to start. I did the analysis up to the Clustering but I didn't see anything about manipulating the clusters. Is there a specific place I should start?

**Comment by adkinsrs** [comment]
The options show up in the "marker renaming" step of the louvain clustering, so you will need to run marker genes first to bring that up. Then any clusters with the same revised label can be merged, or you can uncheck "keep" to filter that cluster out


------------------------------------------------------
Ricky "Shaun" Adkins
Bioinformatics Software Engineer II
Institute for Genome Sciences
University of Maryland, School of Medicine
Phone (410) 706-6766
________________________________

**Comment by beamilon** [comment]
Ok. Thank you. I will play with it tomorrow.

**Comment by adkinsrs** [comment]
Also, you can refine the clusters over multiple rounds of hitting the "relabel" button


------------------------------------------------------
Ricky "Shaun" Adkins
Bioinformatics Software Engineer II
Institute for Genome Sciences
University of Maryland, School of Medicine
Phone (410) 706-6766
________________________________

**Comment by beamilon** [comment]
@adkinsrs @songeric1107 @JPReceveur @hertzron 
It is a nice feature and it is working well. The only minor modification that would be useful is to modify the sentence that appears on top of the "find marker genes" result. Right now it says "Please either rerun louvain clustering with labels (in previous step) or click on the "Compare genes / clusters" toggle to proceed."
With the new feature, it should say something like "Please either go back to the Clustering (Louvain) result window below to rename, merge and/or select specific clusters or click on the "Compare genes / clusters" toggle to proceed"

**Comment by adkinsrs** [comment]
> Right now it says "Please either rerun louvain clustering with labels (in previous step) or click on the "Compare genes / clusters" toggle to proceed."
> With the new feature, it should say something like "Please either go back to the Clustering (Louvain) result window below to rename, merge and/or select specific clusters or click on the "Compare genes / clusters" toggle to proceed"

This seems reasonable.  I will make an adjustment soon
