### ISSUE TITLE
Dataset uploader unable to open for validation

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#538]
Been running into an error in the dataset uploader where its unable to open the tarball for validation, even after repeated uploads. Thought it was a data issue at first but I'm able to reproduce the same error with tarballs from previous successful data uploads and the example tarball from the upload page. Any thoughts on the potential cause?

Will try on another network later today to see if I can reproduce.

<img width="1517" alt="Screenshot 2023-05-31 at 6 38 08 AM" src="https://github.com/IGS/gEAR/assets/28451557/dcd73ac3-2e07-4707-a7e6-331d81d48a3d">

<img width="1792" alt="Screenshot 2023-05-31 at 7 00 39 AM" src="https://github.com/IGS/gEAR/assets/28451557/f2614888-9231-428c-a185-1ebd883d13f4">

**Comment by jorvis** [comment]
Can you put the tarball somewhere I can access it?

**Comment by songeric1107** [comment]
@jorvis if you try our template download tar file, the uploading will fail. please see below.

![Screenshot 2023-05-31 at 11 34 19 AM](https://github.com/IGS/gEAR/assets/6730079/f761310b-8730-4811-9bfc-c21355e17e2a)
[example_3tab.tar.gz](https://github.com/IGS/gEAR/files/11615970/example_3tab.tar.gz)
[metadata_template.xlsx](https://github.com/IGS/gEAR/files/11615971/metadata_template.xlsx)
