### ISSUE TITLE
Enumerate what we want to show in user history

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#540]
In the UI update, there will be a section where users can see their (and only their) activity history and return directly to any action/view.  In this ticket, I want to enumerate the sort of actions we want to store and support here.  Feedback encouraged.

- Gene expression search for single, multi-genes or carts.  Here we'll store the genes/carts searched and the active profile.  Permalink already supported.
- Projection search.  Source pattern and target dataset needed.  Permalink already supported.
- Dataset search.  All search params of each search within a Dataset Explorer session, or only the last search within a session?
- scWorkbench state.  Returns to the last point when using the workbench, requires the dataset, analysis ID and any primary analysis params.  Permalink partially supported.
- Public gene cart added
- Public profile added

Could use feedback/additional item ideas.

**Comment by jorvis** [comment]
As a reminder, the area of the UI in the demo looks like this:

![Screenshot from 2023-06-05 15-11-34](https://github.com/IGS/gEAR/assets/330899/6579cd18-c0a5-42d1-a95c-b9e1ebbe74f4)

**Comment by adkinsrs** [comment]
recently created curations (single and/or multigene)?

**Comment by adkinsrs** [comment]
recently created genecarts or profiles?

**Comment by jorvis** [comment]
Closing this for now as I think this is a good set for addition.  Others could be added later.
