### ISSUE TITLE
Functional annotation not loading

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#545]
Just noticed that the functional annotation information doesn't seem to be loading, even for profiles where the information was there previously. For example screenshot of the default hearing profile.
<img width="1207" alt="Screenshot 2023-06-16 at 1 14 29 PM" src="https://github.com/IGS/gEAR/assets/28451557/283d6c5c-8117-4793-8681-4d1b63e186ca">

**Comment by adkinsrs** [comment]
It seems you can click a "disabled" organism button and it reveals annotation info, but then that button and the tooltip are locked in state.

**Comment by jorvis** [comment]
Fixed fully in commit e2134b9
