### ISSUE TITLE
Remove toggle for enabling/disabling projection learning

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#573]
Sometime last year, @hertzron had requested we have a toggle to enable or disable displaying of the "Transfer Learning" link until stability issues were worked out. I feel we are at a point where the toggle can be removed and the "Transfer Learning" link is permanent.  One reason is also that @carlocolantuoni noted the link sometimes does not load instantaneously since gEAR has to go through a server-side check to know if the link should be displayed or hidden.

**Comment by carlocolantuoni** [comment]
Sounds good to me
