### ISSUE TITLE
Download data in nemoarchive.org

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#578]
**From:** Siqi Shen

**Email:** sshen82@wisc.edu

**Server IP:** 10.142.0.14

**Msg:** I want to download all scHi-C files from the paper https://www.biorxiv.org/content/10.1101/2023.04.16.536509v1.full.pdf with the portal nemoarchive.org. I have three questions on this,
1. Does "U19_Cemba" in Grants option contain all the files I need?
2. The website said that I can't put more than 10000 files into the cart. Do you know how to download those files?
3. I tried to contact NeMO in https://nemoarchive.org/contact, but when submitting the question, it said "This page isn’t working". Do you know what happened? If this is not the correct place to contact, then where should I seek help?

**Tags:** ['']

**Screenshot:** None

**Comment by jorvis** [comment]
I have forwarded these questions to Victor and the NeMO team, who will take it over in their ticketing system.
