### ISSUE TITLE
is there a way to download sample metadata?

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#579]
**From:** Roberto Avelar

**Email:** ravelarvargas@gmail.com

**Server IP:** 10.142.0.16

**Msg:** I would like to explore this dataset further: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE178931

However, the cell ontology labels are not provided on geo, but the cells are labelled in gEAR. I was wondering if it is possible to download the cell ontologies from gEAR?

Cheers,
Roberto

**Tags:** ['gEAR,single-cell RNAseq']

**Screenshot:** None

**Comment by jorvis** [comment]
Sent this to the user:

I'm happy to help, but cannot see the dataset in question.  The URL you provided shows a Pubmed ID of 35320729, but we don't currently have any datasets related to that publication in gEAR (at least, none with the pubmed ID entered.)

Can you send the link within gEAR of the dataset you're referring to?
