### ISSUE TITLE
Error in clustering

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#581]
**From:** Nicholas Jacobs

**Email:** nicholas.jacobs@yale.edu

**Server IP:** 10.142.0.14

**Msg:** Hello,

I was doing a test run on the single cell workflow, going through the pipeline for the "scRNAseq of human prefrontal cortex at GW18" and when I got to the step to perform clustering analysis I got an error message saying that it couldn't perform clustering. I used all the default parameters except I had 15 PCs and 20 neighbors and used UMAP in that step. Any idea what that error could be?

**Tags:** ['']

**Screenshot:** None

**Comment by DanLesperance** [comment]
Looking into this

**Comment by DanLesperance** [comment]
Reached out to Nicholas regarding potential workarounds.  The issue is due to the Louvain clustering memory issue on larger datasets
