### ISSUE TITLE
Enquiry about downloading data

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#607]
**From:** Sonya Yoeung

**Email:** sonyawxiii@gmail.com

**Server IP:** 10.142.0.16

**Msg:** To whom it may concern,

Thank you for creating and managing such a great tool as gEAR as it is. May I wonder is it possible that I can download the datasets from gEAR? 

Thank you for your time and consideration. Look forward to hearing from you.

Best,
Sonya

**Tags:** ['#download']

**Screenshot:** None

**Comment by jorvis** [comment]
I responded to the user:

Hi, I work on the gEAR team and am responding to your question about download datasets.

You certainly can.  If you're viewing results of any gene search each dataset is a block in the display.  You can use the drop-down menu in the upper-right to access many tools for each dataset, including download links.

I've attached a screenshot to hopefully illustrate.

Let me know if you have any other questions.
![download](https://github.com/IGS/gEAR/assets/330899/1c587dfd-9ea6-4caf-a8a2-839a08150f42)
