### ISSUE TITLE
Error caused by not all parts of primary analysis present in a dataset

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#609]
To have primary analysis in the dataset curator, datasets need both coordinates and cluster information. It looks like primary analysis is an option in the dropdown for datasets that have only coordinate information which results in an error when a user tries to find marker genes.

**Comment by jorvis** [comment]
Confirmed that right now the 'primary analysis' is showing up if any of the following are present: clustering, tSNE, UMAP.  But the steps available on the interface with primary analysis require clustering info and that's all.  

Going to change this to show primary analysis only if clustering is present.

**Comment by jorvis** [comment]
Committed code to fix this and tested locally?  How urgent is it that we export this fix?

**Comment by JPReceveur** [comment]
Not urgent, I can take care of the rest of the user's request and let them know that that bug will be fixed in an upcoming update. Have a rough timeline of when that might be?

**Comment by JPReceveur** [comment]
Is there an interaction between the primary analysis and de novo analysis? Just tried to run a denovo analysis on the dataset above and am running into an unspecific error on the clustering step. Looked at the h5ad and nothing is jumping out as wrong when I do a test read.

**Comment by jorvis** [comment]
Closing this feature as implemented - the issue Joe mentioned above can be logged separately if it's still a problem.
