### ISSUE TITLE
Unable to upload the tar file

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#614]
**From:** Ishwar Hosamani

**Email:** hosamani@bcm.edu

**Server IP:** 10.142.0.16

**Msg:** Hello, 
I receive the following error message when I try to upload the 3-file tarball.
"Oops! Unable to finish dataset upload. Please try again." I see "Finalizing dataset upload ... please wait ..." and the flashing dots, even though this error message is displayed at the top. Since it's a fairly small file, I presume it shouldn't take too long to upload. I have tried it a couple of times and I get the same error. 
FYI, I prepared the 3 files starting from seurat object using the R code provided in the FAQ section. 

**Tags:** ['upload,Fbxo2,issue']

**Screenshot:** None

**Comment by jorvis** [comment]
I've e-mailed the user asking if I can get access to the files being uploaded.

**Comment by jorvis** [comment]
Done, user has confirmed.  Issue was non-numeric strings in the annotation release field in metadata sheet.  New uploader to have far better validation so it doesn't get this far.
