### ISSUE TITLE
add ability to flip axes in static tSNE/UMAP display curation

### ISSUE THREAD

**Issue by carlocolantuoni** [IGS/gEAR#615]
in the display curation for the static scatter plots, especially for when we are sing this for spatial data, it wold be great to be able to reverse the order of plotting for 1 or both axes. this would simply be multiplying the X or Y values by -1. could we add this as a radio button under the pulldown menus for the X and Y axis values?

**Comment by adkinsrs** [comment]
Regular tSNE
<img width="929" alt="Screenshot 2023-10-26 at 9 45 40 AM" src="https://github.com/IGS/gEAR/assets/5665914/7f7a04dc-90f3-4779-a3ba-e3b1eacb1444">

Flipped x-axis
<img width="930" alt="Screenshot 2023-10-26 at 9 52 21 AM" src="https://github.com/IGS/gEAR/assets/5665914/e0bc80a9-12bd-4b2f-823a-16725c49f5de">

Flipped y-axis added
<img width="932" alt="Screenshot 2023-10-26 at 9 52 41 AM" src="https://github.com/IGS/gEAR/assets/5665914/1782f3ee-61c5-4967-84a3-68c594d8663f">


@carlocolantuoni  is this what you wanted?

**Comment by adkinsrs** [comment]
Addressed in [4055005](https://github.com/IGS/gEAR/commit/40550054ef49943923b4ac69ac382baeed1a8610)

**Comment by carlocolantuoni** [comment]
Looks perfect!
