### ISSUE TITLE
download of weighted gene carts writes empty file

### ISSUE THREAD

**Issue by carlocolantuoni** [IGS/gEAR#617]
when i try to download an unweighted gene cart i get the list of genes in a file. when i try to download a weighted gene cart i get an empty file.

**Comment by adkinsrs** [comment]
This has been addressed in [61b11fa](https://github.com/IGS/gEAR/commit/61b11fa1a65992a86770a58cd5c6f43e34aab171)

Downloading a weighted gene cart will download a tab file of genes + weights

**Comment by adkinsrs** [comment]
Note this in the v2 code
