### ISSUE TITLE
Update Flask to v3.0.0

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#621]
Recently ran across this when doing a docker build on some code changes.  Despite my Flask version being v2.1.0, pip installed Werkzeug 3.0.0, which removes some deprecated functions, and temporarily broke my local dockerized area.

Flask has also updated to v3.0.0 (documentation here -> https://flask.palletsprojects.com/en/3.0.x/changes/#version-3-0-0). I am building and running this on my local docker instance as a test of sorts, but eventually when things are calmer, it may be good to upgrade the servers to utilize tis too.

**Comment by jorvis** [comment]
Can you detail where all this is still used?  I thought the Flask dependency went away with the removal of Vue.js

**Comment by adkinsrs** [comment]
Flask is still used as a dependency of the flask-restful package for the API calls. I don't think there was ever a direct Vue-Flask dependency coupling, since both are two different languages and vue was client-side.


------------------------------------------------------
Ricky "Shaun" Adkins
Bioinformatics Software Engineer II
Institute for Genome Sciences
University of Maryland, School of Medicine
Phone (410) 706-6766
________________________________

**Comment by adkinsrs** [comment]
Been using Flask 3.0.0 for tasks for a while now and have encountered no issues with it

**Comment by adkinsrs** [comment]
This is being used in v2
