### ISSUE TITLE
Rewrite "gene cart manager" (gene lists) page

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#622]
@amahurkar  said this should be the next priority in the UI rewrites, and since @jorvis is still busy with other things, I will take first crack at this.

**Comment by adkinsrs** [comment]
Features #403, #405 will be added.

#587, #617 will be addressed.

#598 may be added as a future or implemented in a different way.

**Comment by DanLesperance** [comment]
Few initial observations

- Navigating to any of the other tabs (Single-gene Curator) works fine, but can't navigate back to gene lists
- Once opening the page, downloading a tsv of the genes results in 0 byte file
- Editing the metadata and saving (without doing any changes) results in the options disappearing for the gene list (screenshot below)
![Screenshot 2023-11-30 at 4 00 21 PM](https://github.com/IGS/gEAR/assets/32070437/ab6c82bc-d4de-45c9-bfb2-8afa7df33d00)
- Search seems to have issues picking up partial names, SURFACE doesn't pick up SURFACE_MARKER and Tono misses Tonotopic Axis (Koo et.al. 2021)
- (Minor) clicking the 1 or 2 page selector results in a duplicated page selector appearing for a split second.  Not really a problem just looks slightly buggy.

**Comment by jorvis** [comment]
I just fixed the nav buttons

**Comment by adkinsrs** [comment]
Ironically I also pushed a commit to hyperlink the gene collections nav button, and deployed to gear-devel


------------------------------------------------------
Ricky "Shaun" Adkins
Bioinformatics Software Engineer II
Institute for Genome Sciences
University of Maryland, School of Medicine
Phone (410) 706-6766
________________________________

**Comment by adkinsrs** [comment]
I've addressed all of @DanLesperance's suggestions with commits except `Search seems to have issues picking up partial names, SURFACE doesn't pick up SURFACE_MARKER and Tono misses Tonotopic Axis (Koo et.al. 2021)`. I think that may be more of a @jorvis one since he has worked on the search functionality in the past (though I'm willing to take a crack)

**Comment by jorvis** [comment]
I don't mind if you want to look.  Currently it uses the database full text indexes to perform SQL 'MATCH AGAINST" which, at least by default, don't support substring matches.

**Comment by adkinsrs** [comment]
development server is updated for more testing
