### ISSUE TITLE
Delete dataset display where analysis was deleted.

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#623]
@JPReceveur had a situation where a dataset display did not show because the corresponding analysis h5ad was not found. The "user_saved" analysis ID directory was actually not present on the filesystem, leading me to believe that the user deleted the analysis.  Currently our "delete analysis" CGI script just removes the analysis directory, but does not delete any corresponding dataset displays using this analysis.

Low priority since it seems like an edge case.

**Comment by adkinsrs** [comment]
Example (WT Saccula dataset) -> https://umgear.org/index.html?multigene_plots=0&layout_id=d8a88ca9&gene_symbol_exact_match=1&gene_symbol=sox2

**Comment by adkinsrs** [comment]
Observed a case in nemoanalytics where the user_saved analysis files + directory are missing. Dataset can be found near bottom of the link redirect in the opening comment of #847. Unsure if "delete_analysis" was run. One caveat to this, is that the original dataset supposedly has no metadata, so curation cannot happen unless it came from an analysis.

**Comment by adkinsrs** [comment]
Adding some commented-out code that would remove any displays where this analysis ID, and would cascade to remove dataset_preference and layout_displays entries with the same display ID.  However I am leaving it commented out because I'm not sure if it is worse to have the display "mysteriously" vanish (from a user's perspective), or have the display show an error when drawn.

What I am also doing is adding better error-handling when analysis file paths are retrieved.

**Comment by jorvis** [comment]
Probably need to warn a user when they delete an analysis that there are displays depending on that analysis, so they can decide if they still want to remove it.

**Comment by adkinsrs** [comment]
That makes sense.

**Comment by JPReceveur** [comment]
Is there any cleanup we can do to make the error message related to this look nicer?

<img width="372" alt="Screenshot 2024-08-09 at 2 14 10 PM" src="https://github.com/user-attachments/assets/fd08e5eb-4a4a-4186-9e6c-f9e7581f354d">

https://umgear.org/expression.html?gene_symbol=pou4f3&gene_symbol_exact_match=1&is_multigene=0&layout_id=d8a88ca9

**Comment by adkinsrs** [comment]
oof, yea I'll fix that.

**Comment by adkinsrs** [comment]
@JPReceveur care to check the new message.  It's a generic "Can not retrieve AnnData object" error.

**Comment by adkinsrs** [comment]
Adjusted error message to better reflect the actual issue (analysis h5ad not found)
