### ISSUE TITLE
primary analysis - ScRNA-seq - P8, P12, P20 mouse cochlea (Michalski 2023)

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#625]
**From:** Elena Chrysostomou

**Email:** echrysostomou@salk.edu

**Server IP:** 10.142.0.16

**Msg:** Hello
I had two questions about this dataset:
1.If you do primary analysis on this dataset which stage would I be looking at?
2.Is there a cluster for outer hair cells? I couldn't seem to find it when looking at find marker genes using primary analysis
Best,
Elena

**Tags:** ['']

**Screenshot:** None

**Comment by jorvis** [comment]
Elena -

I can't see from your post which dataset you are referring to.  If it's private feel free to e-mail me the link to it, else you can put it here.

**Comment by echrysostomou** [comment]
https://umgear.org/index.html?multigene_plots=0&share_id=a46dab6f&layout_id=f64f9c22&gene_symbol_exact_match=1&gene_symbol=atoh1

**Comment by jorvis** [comment]
Elena -

I looked into this and see that this dataset has the following observation columns:

```
                                      cell_type  age                louvain
observations                                                               
AAACGCTAGCGAAACC_CA08_S1  Tympanic border cells  P12  Tympanic border cells
AAGCGTTAGGAATCGC_CA08_S1             Osteocytes  P12             Osteocytes
AATTTCCAGGGCCTCT_CA08_S1                B cells  P12                B cells
ACGTAACAGACTAGAT_CA08_S1     Intermediate stria  P12     Intermediate stria
ACTTTCATCATTTGGG_CA08_S1  Tympanic border cells  P12  Tympanic border cells
AGCGTATAGGTAGTCG_CA08_S1  Tympanic border cells  P12  Tympanic border cells
```

There, the 'age' column has all the values of P8, P12 and P20, so if you use the primary analysis provided by the author, which was clustering, they'll be merged in the single-cell workbench.

Now, in the beta version of gEAR in the dataset curator you can now not only create a display which uses the age column, but you can filter on the values within that column too.  So this would let you create displays only for P20, for example, and show the cluster data.

**Comment by echrysostomou** [comment]
I had a look for this dataset in beta via the workbench and I only found this dataset. Could you please confirm this is the correct dataset as the author wasn't in the title. Is this just the P20 data.? Michalski 2023 doesn't seem to be there?
![P20](https://github.com/IGS/gEAR/assets/150873066/b6e2dc33-ed5a-41f7-a885-6c58fe70ea62)
