### ISSUE TITLE
H5AD file read error shows up as "Resources are busy ..."

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#628]
A file transfer failed so that the EOF was shorter than expected, but the interface showed this:

![Screenshot from 2023-11-14 21-37-49](https://github.com/IGS/gEAR/assets/330899/26ddaa24-f29f-4b73-a958-90dc68f1c7b7)

While the apache log says this:

OSError: Unable to open file (truncated file: eof = 9020719104, sblock->base_addr = 0, stored_eof = 9773599513)

To duplicate, do anything to make the h5ad unreadable, truncate one, maybe permissions, etc.

**Comment by adkinsrs** [comment]
So is the issue to fix this H5AD file or is the issue to catch and throw a more appropriate error?

**Comment by jorvis** [comment]
I fixed the data file.  Issue is to catch the error and report more
accurately

**Comment by jorvis** [comment]
No longer valid I believe in V2
