### ISSUE TITLE
Gene Cart - Make label required

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#63]
I was testing the gene cart manager (to see if I need to add my tree structure code there).  I created a gene cart without a label, and I realized that I have no way to search for this cart since the search is done by label.  So I propose making the label required or give a warning that the dataset will not show in label-based searches.

**Comment by jorvis** [comment]
Now reddens the required field and halts submission if label not entereed:

![Screenshot from 2021-10-19 00-17-01](https://user-images.githubusercontent.com/330899/137848209-f14f05cc-63ff-416c-884c-20f53f56cf70.png)
