### ISSUE TITLE
Visualizing marker genes return an error

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#634]
@adkinsrs 
@jorvis
I tried to visualize marker genes from the sc workbench (tried several datasets) and it returns an error. I also tried to capitalize the gene names and the error is the same. The problem is just for the genes that are typed in. The visualization works perfectly for genes selected in the table.
Below is an example with the P1, mouse, scRNA-seq, cochlear epithelium (Kelley).

![image](https://github.com/IGS/gEAR/assets/70719873/99d17199-7a4a-4bfc-8bd0-f4701cdfd998)

**Comment by adkinsrs** [comment]
Going to commit a "main" and a "v2" fix for this.  We aren't rewriting this page for the v2 UI yet, so if we end up switching codebases on the production servers, this bug will still be resolved

**Comment by adkinsrs** [comment]
Testing is going to be interesting here.... the production server uses scanpy 1.7.2 and the devel server (and my local one) use scanpy 1.8.2, and the QC-to-mito server-side script is throwing an error when using the later version.

**Comment by beamilon** [comment]
@adkinsrs
It's working perfectly. Thanks.
