### ISSUE TITLE
Refactor of Single Gene Curator

### ISSUE THREAD

**Issue by DanLesperance** [IGS/gEAR#635]
Area to track bugs in the Single Gene Curator a few quick ones are noted below

- [ ] Action buttons on the "Your Displays" section of "Create new or load existing curation" overhang the display box of the image
![Screenshot 2023-12-07 at 10 47 23 AM](https://github.com/IGS/gEAR/assets/32070437/a4094118-7ec7-4978-ad26-e79ff71c6b50)

- [ ] If a dataset has more than 1 curated image the multiple images start to overlap the action buttons (may be related to the first issue above)
![Screenshot 2023-12-07 at 10 45 12 AM](https://github.com/IGS/gEAR/assets/32070437/7da03958-49c3-4bed-8b9a-341ba5890050)

**Comment by adkinsrs** [comment]
I initially had some trouble with lining up these buttons. Do you think it would be better just to have the buttons stacked vertically instead (each taking up the width of the "display card") ?

**Comment by DanLesperance** [comment]
I believe that would be the best option.  It actually appears that this issue is from not having the page the full width of the screen (ie. changing the size of the web browser).  This issue is only seen under the Your Displays section, the "Displays by Dataset Owner" switch between stacked and in-line as you change the browser size 
(Screenshot below is only a part of my screen)
![Screenshot 2023-12-07 at 11 18 58 AM](https://github.com/IGS/gEAR/assets/32070437/54ae814c-72c2-4cdf-87f7-27c902d27f7d)


(Full screen size screenshot)
![Screenshot 2023-12-07 at 11 21 33 AM](https://github.com/IGS/gEAR/assets/32070437/df5a6b96-da42-457a-85a7-c9539d3956a2)

**Comment by adkinsrs** [comment]
Good examples. Has to be some minute CSS style differencing when the default button size makes all buttons extend beyond the buttons or not.

I'll make that change then.
