### ISSUE TITLE
Exact match behavior when using multigenes

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#640]
If you toggle off exact mapping and search for the start of a gene family it results in all the options showing up. If you try to use the exact matching with a multigene display, it returns an error (not enough genes in search) when a user may be expecting to be able to make a heatmap with those partial matches. 

<img width="816" alt="Screenshot 2024-02-03 at 9 58 02 AM" src="https://github.com/IGS/gEAR/assets/28451557/a67338a4-7037-477d-995a-228e909df0bb">

**Comment by adkinsrs** [comment]
Closing in favor of #795
