### ISSUE TITLE
Index and expression page - highlight  region if no dataset collection selected after searching

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#645]
Currently if the user attempts to search without selecting a collection, a toast-like message (correctly) appears to let the user know to select a collection. But it would be useful to highlight the box they need to change ("is-danger" border) so they will know what to change.

**Comment by adkinsrs** [comment]
<img width="766" alt="Screenshot 2024-02-06 at 8 24 46 AM" src="https://github.com/IGS/gEAR/assets/5665914/1600086e-640e-463a-9d3d-7e1def4a3c1c">

An example of what I think should happen.  May some small help text under to say "this is required".  I already have some CSS here https://github.com/IGS/gEAR/blob/335197da41b44073931a855e00f8d4490d8bd7da/www/css/common.v2.css#L112-L127 that will overwrite the default "salmon"-looking is-danger class coloring that we have in our SASS file for these situations with "select" objects

**Comment by jorvis** [comment]
For now I've implemented it with coloring only, but no separate label, which can be added later if needed.  I tried a few views of it and it didn't fit well with the rest of the form.
