### ISSUE TITLE
Database download for enrichment analysis

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#651]
**From:** Ishan Bhatt

**Email:** Ishan-Bhatt@uiowa.edu

**Server IP:** 10.142.0.16

**Msg:** Is it possible to download scRNA seq database from a specific study through the gEAR portal? I would like to curate scRNA seq database(s) to conduct enrichment analysis. 
Thank you!
Ishan

**Tags:** ['gEAR,download,scRNAseq']

**Screenshot:** None

**Comment by jorvis** [comment]
I've responded to the user.

```
![Screenshot from 2024-02-13 09-46-05](https://github.com/IGS/gEAR/assets/330899/6d7a3d95-ecce-4142-abd7-c7236d0441d3)
```

**Comment by jorvis** [comment]
![Screenshot from 2024-02-13 09-46-05](https://github.com/IGS/gEAR/assets/330899/35d7258a-52ce-487c-9fa3-937246b2b297)
