### ISSUE TITLE
Download Raw or Seurat Object

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#658]
**From:** John Pham

**Email:** john.pham@umanitoba.ca

**Server IP:** 10.142.0.16

**Msg:** Hi,

I was wondering if there was a way to download/access the raw dataset or even Seurat object create from finding the top variable features. I was looking at "scRNA-seq—P8, P12, P20 mouse cochleae (Michalski, 2023)” and “snRNA-seq—P8 mouse cochleae (Michalski, 2023)", but I could not see an option to do either. Would I have to get author permission or may I download the data from gEAR?

Sincerely,
John Pham

**Tags:** ['gEAR,mouse,snRNA-seq']

**Screenshot:** None

**Comment by jorvis** [comment]
I have responded to this user.
