### ISSUE TITLE
Dataset/Gene/Pattern selectors - Clear search results if text input field is cleared

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#662]
If I type in a keyword for a dataset, for example, to filter datasets, the filtering correctly happens.  But if I backspace or clear out the input box, the filtered datasets remain.  I would expect to see all datasets in whatever view I'm in, or see no datasets at all if I have not selected a view if the input box has been cleared.

Assigning @jorvis for his selectors, and myself for the pattern one.

**Comment by jorvis** [comment]
Added code to handle the gene and dataset search parts, so removing myself from the assignment list.
