### ISSUE TITLE
UI-V2 - Potential race condition loading plugins

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#665]
Occasionally I get the following error `Uncaught (in promise) TypeError: Cannot set properties of null (setting 'innerHTML')
` in the following code block https://github.com/IGS/gEAR/blob/23832009af7b1ef1eb83a646d2c8535631cf603f/www/js/common.v2.js#L514-L522

This error happens spontaneously (cannot reproduce), and it seems the fetch is occurring before the element is created. I checked and the "fetch" is returning successfully but the `plugin_name + "_html_c"` element is not in the body.  Maybe line 516 should be moved within the ".then" at line 520.

Two minor nitpicks/suggestions
1. Since `plugin_html_element.id` is already defined, use that in the getElementById instead of writing out the string again.
2. Replace `var` with `let/const` in the "for" loop (for consistency with modern JS)

**Comment by jorvis** [comment]
Addressed all these.  There was definitely some un-refactored code copied here from v1 I didn't modernize.

**Comment by adkinsrs** [comment]
<img width="1833" alt="Screenshot 2024-04-22 at 9 31 16 AM" src="https://github.com/IGS/gEAR/assets/5665914/d73e63e6-d294-4243-a9a3-88efc2943df3">

Still observing this (the second error was from clicking the "functional annotation dropdown".)

<img width="801" alt="Screenshot 2024-04-22 at 9 32 12 AM" src="https://github.com/IGS/gEAR/assets/5665914/e67a82d7-3f28-4a0e-8eb3-b26198b9ee5f">

**Comment by jorvis** [comment]
I was able to reproduce this repeatedly on staging and the above commit fixed the issue where the JS was being loaded before the DOM finished populating.
