### ISSUE TITLE
Test upgrading scanpy/anndata

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#670]
When we redesign the single-cell workbench page, I think it would be a great time to update the scanpy and anndata packages.  I made a branch "scanpy-1.9.8-upgrade" where I will install the latest versions of several packages and test them out.  I already have been doing a bit of work on this, and found a couple of small bugs that have been cleaned up. Another nice perk is some of our own code can be condensed or removed due to new options from scanpy.

Scanpy -> 1.9.8
Anndata -> 0.10.6
pandas -> 2.2.1
h5py -> 3.10.0
(and other things)

**Comment by jorvis** [comment]
This will be very nice to have done!

**Comment by adkinsrs** [comment]
Testing sc workbench is done. Single gene curator is done though I did not exhaust every single possible option. Expression and projection pages also complete (generally these plots also overlap with testing the curators)

todo- compare tool and multigene curator.

**Comment by adkinsrs** [comment]
Closing this since we have deployed on production
