### ISSUE TITLE
Refactor dataset collection page for ui-v2

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#671]
This is normally @jorvis's domain, but I will take first crack at this.

**Comment by adkinsrs** [comment]
Tentatively done with this.  It is deployed to gear-devel for testing if anyone wants to try it out.

There are a lot of moving parts, so I certainly can imagine there are bugs or things I forgot to implement or design decisions that need to be reviewed

**Comment by jorvis** [comment]
Awesome! Does this included respecting the guser.is_admin and guser.is_curator settings yet?  We need to elucidate out what those mean still.

**Comment by adkinsrs** [comment]
New additions

* Layout arranger is split into single and multi-gene layouts
* Layout arranger now works for adjusting display width and height, as well as moving to different spots on a grid
* Condensed table view of datasets
* More explicit toggle to search all datasets or in the scope of the selected dataset collection
* Toggle to make dataset downloadable. Dataset will also not be downloadable if the h5ad file is not present (per the database flag)
* Various security-related fixes on what database pieces are returned to the client from the CGI calls.

Known things left to do
* Adding a dataset to a layout multiple times (#687)
* Layout arranger needs to pick displays instead of datasets (#687)
* Just realized I forget to get image previews working for the layout arranger
* is_admin and is_curator -> https://github.com/IGS/gEAR/issues/671#issuecomment-2072670521

**Comment by adkinsrs** [comment]
> Awesome! Does this included respecting the guser.is_admin and guser.is_curator settings yet? We need to elucidate out what those mean still.

The above is still a TODO

Also need to add the ability to change share IDs (permalinks) for dataset collections as well as individual datasets

**Comment by adkinsrs** [comment]
Last bullet point in the set has been converted into #871 so closing
