### ISSUE TITLE
V2 - Add "history state" for expression and projection pages

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#683]
Currently if you are on the projection or expression search page and change conditions, then search, the URL state history is not updated (which was sort of by design as this is added to the User History) I believe.  Currently the only way to generate a URL would be to search from the index page, which creates an expression page URL only and navigates there... there is no similar mechanism for the projection page.  I am proposing that a "create URL" button be added to both pages, that would create a URL based on the currently set conditions for the search when the button is clicked. This way a user can easily return to such a search.

**Comment by adkinsrs** [comment]
This indirectly relates to #674

**Comment by jorvis** [comment]
I'd rather us use URL rewriting if we can.

**Comment by adkinsrs** [comment]
Acknowledged.  So on the expression and projection pages, the "state history" code from v1 should be implemented again.

**Comment by jorvis** [comment]
That, anything newer you prefer, whatever.  But users are going to naturally copy the URL in the browser so it's better to embrace that.

**Comment by adkinsrs** [comment]
resolved with commit [b430841](https://github.com/IGS/gEAR/commit/b4308415797c12b24e6694cc54f2cedbc6c6928f)
 ·
