### ISSUE TITLE
Figures for review paper 

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#685]
**From:** Melise Edwards

**Email:** medwards@umass.edu

**Server IP:** 10.142.0.14

**Msg:** Hi Allen Team, 

I am wondering if the patch-seq data are available to screenshot and/or download (png file) for users to incorporate them into review papers? I am writing about the ways in which cellular subtypes are uniquely affected by steroid hormones (i.e., estrogens and their receptors) and love the resolution at which I can see this data in the patch-seq datasets. However unlike other atlases, there isn't an option to download the figure. Is this intentional or do you foresee being able to allow users to download png files from this atlas?

In addition, I am seeing inconsistencies in the png files I download versus those featured on the interactive "Nemo" platform (see attached graph with the downloaded png and the x-axis labels which do not match.) The example is from the Primary Motor Cortex Mouse 10X_cells_v2_AIBS

Thank you very much for your time. 

**Tags:** ['RNAseq,Isocortex,mouse,motor']

**Screenshot:** https://nemoanalytics.org/contact_screenshots/3aa473f5-7911-4c10-b428-433515cafdf2.png

**Comment by DanLesperance** [comment]
Contacted the user to inform them of different ways to download images.  Also mentioned we are looking into the second concern on the engineering side of things

**Comment by adkinsrs** [comment]
Regarding the 2nd issue, one thing Plotly does is try to condense axis labels when it can.  Unfortunately this was not a good time to do that, as the number of labels in the PNG (about 30) is less than the browser plot (way more than 30). If you were to resize the browser into a smaller window, I think you would find the plot to look similar to the PNG.  I think a solution would be to resize the image dimensions based on the number of samples present so that it doesn't skip some axis labels.

**Comment by DanLesperance** [comment]
User also pointed out the expression label will occasionally display odd values.  The below screenshot taken by the user shows the expression label going from 0.0 to 0.5 and then restarting 0.0 to 1.0 to 0.5 (seen on top) or values overlapping (seen on bottom image).  They have informed me that a simple refresh of the page works, but this happens often enough to be a slight annoyance.  I have not been able to replicate on my end though.
![Screenshot 2024-04-18 at 11 26 39 AM](https://github.com/IGS/gEAR/assets/32070437/be6fbebf-153c-4f48-ac26-7c640e03de73)

**Comment by adkinsrs** [comment]
Those are SVGs correct?  I'm guessing what is happening is that two legends are being created one on top of the other and slightly offset.  I rewrote the legend code in v2 so I'd be curious to see if the issue occurs in nemo-devel or a v2 environment.

**Comment by jorvis** [comment]
Checking in on the status here.  Has the user been contacted?

**Comment by DanLesperance** [comment]
Issue is completed.  User has been contacted and we've resolved all questions
