### ISSUE TITLE
snRNAseq Data Uploaded - Still Error on Display

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#691]
**From:** Rebecca Chase

**Email:** chaser@wustl.edu

**Server IP:** 10.142.0.14

**Msg:** Hi. I have uploaded some data to the site but when trying to view I get an error message and it prompts me to contact gear for assistance. 

**Tags:** ['']

**Screenshot:** None

**Comment by adkinsrs** [comment]
If I recall, this is the person whom @jorvis asked me to look into an issue for. In that particular case, her sample metadata (when looked at from the h5ad file) only had barcodes but no actual discernible metadata

**Comment by DanLesperance** [comment]
Correct.  I've worked with the user as well on figuring out their data, also provided them documentation on uploading analyzed data, rather than the raw 10x matrix data.

**Comment by jorvis** [comment]
Can this be closed?
