### ISSUE TITLE
User unable to leave comments/feedback 

### ISSUE THREAD

**Issue by echrysostomou84** [IGS/gEAR#7]
User unable to submit form for comments and feedback.

**Comment by jorvis** [comment]
Confirmed.  I fixed the issue where tags weren't loading, but there's still an error when saving:

Error during creation: HTTP error occurred: 401 Client Error: Unauthorized for url: https://api.github.com/repos/jorvis/gEAR/issues
comment.js:67

**Comment by jorvis** [comment]
OK, the issue here was that the .env file expected in www wasn't present.  Corrected and tested.
