### ISSUE TITLE
Profiles to move to NeMO devel for upcoming SCORCH meeting

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#702]
For the SCORCH meeting next week, could we have the following datasets (owned by curator) copied from NeMO Analytics to NeMO Analytics Devel?
- Dev Human Hypothalamus
    - Dataset IDs: 84b8a04a-b995-4735-98c7-73072cb1480d, f973952f-29fa-4352-a041-a3acd4223fde, 4e5ee5b7-ba42-9cbf-fe4b-e6148309358e
 - SCORCH: Plaza-Jennings 2023
     - Dataset IDs: 46976813-7ee6-48f3-b8a8-dc295385f5d1, d9177729-387f-476b-8fce-a475e6afc35a
 - SCORCH: PFC Integration
     - e8819592-19d5-d1c0-1e99-dfdf53411aa8

**Comment by jorvis** [comment]
All datasets and their corresponding curations have been copied, but we don't currently have a tool for copying the profile itself.  Can you try creating these three and making sure the datasets look right for you?
