### ISSUE TITLE
Figures for review paper 

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#706]
**From:** Mélise Edwards

**Email:** medwards@umass.edu

**Server IP:** 10.142.0.14

**Msg:** Hi there, 

I am going through the patchseq data and hoping to use some of these figures for a review paper I'm working on. However, when I search for certain genes (ESR1, ESR2, GPER1) their values do not change at all in the IT neurons patchseq data. This seems odd to me as they should have very different mRNA expression across cell subtypes. Additionally, the only way to save these images is through a screenshot, which impairs the quality a bit. 

Thank you very much for your help and time, 

Mélise 

**Tags:** ['brain,RNAseq,patchseq']

**Screenshot:** https://nemoanalytics.org/contact_screenshots/5fcff89a-e5cf-4d84-a90f-407239b15145.png

**Comment by DanLesperance** [comment]
@adkinsrs In regards to the downloading of the image. You can right click on the Flagship Patchseq IT middle image, but then it doesn't download with the gene expression data; however, as mentioned in the comment a screenshot impairs the resolution.  Any recommendations?

nemoanalytics link
[https://nemoanalytics.org/index.html?multigene_plots=0&layout_id=1206f7ce&gene_symbol_exact_match=1&gene_symbol=ESR1,ESR2,GPER1](url)

**Comment by adkinsrs** [comment]
Right now, we don't have any explicit way to download a higher quality SVG beyond the screenshot.  Definitely something we can look to incorporate in the v2 release, as we already have a button for downloading higher quality tSNE images

**Comment by DanLesperance** [comment]
Informed user regarding the inability to download SVGs beyond screenshot.  

Their first inquiry seemed to be an issue with the user's internet and not an issue in the platform.
