### ISSUE TITLE
Dr

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#707]
**From:** Helen Eachus

**Email:** h.eachus@aston.ac.uk

**Server IP:** 10.142.0.14

**Msg:** Hello,

Is it possible to see if 2 genes are co-expressed in a specific cell type using this platform?

Many thanks,
Helen

**Tags:** ['']

**Screenshot:** None

**Comment by DanLesperance** [comment]
Contacted user and provided resources.  They will begin making a profile to help with their query
