### ISSUE TITLE
Gene Expression Search doesn't return results after adding and deselecting genes

### ISSUE THREAD

**Issue by DanLesperance** [IGS/gEAR#714]
I was performing the following steps on the My Workspace Gene Expression Search, and when I click on the Search button, the Gene Expression page shows up without searching any genes or datasets

1. For Gene Lists select "Cochlear HC's Adult", "Cochlear HC's P0-P2", "Henson Cells E16-P2", "IHCs Adult"
2. Deselect each gene list
3. In Cochlear HC's Adult select the first four genes and click proceed
4. Go to Dataset selector and navigate to select Hearing (Default) --- I know this is the default profile but was showing the selector during the tutorial video
5. Click Search

Even after minutes of waiting this is what the page appears as

![Screenshot 2024-06-27 at 5 31 26 PM](https://github.com/IGS/gEAR/assets/32070437/48fcc6ee-5c71-41b1-8af8-e28da7bfd001)

**Comment by DanLesperance** [comment]
Assigned both Joshua and Shaun as not entirely sure if this bug is due to My Workspace or the Dataset Collection/Gene Expression page

**Comment by adkinsrs** [comment]
The `selected_genes` variable resets (empties) when you go from the home page to the expression page.  I can confirm this without selecting and deselecting gene lists (steps 1 and 2)

**Comment by adkinsrs** [comment]
Pushed commit [8c88ccf](https://github.com/IGS/gEAR/commit/8c88ccf24527c0c1726dfb467f99c8fbecfaee96) and pulled over to gear-devel

**Comment by adkinsrs** [comment]
Closing this as it is over on gear-devel.  Feel free to reopen if it still an issue
