### ISSUE TITLE
gear 2.0 Adding Dataset to new Dataset Collection gives Errors 

### ISSUE THREAD

**Issue by DanLesperance** [IGS/gEAR#715]
Under curator user, I've created a new dataset collection (demo412).  Changed the dataset filter to only public datasets.  I tried adding the first four datasets and received an error on each one.

![Screenshot 2024-07-01 at 12 34 43 PM](https://github.com/IGS/gEAR/assets/32070437/cf30df62-6a14-4d8c-b693-40c506014d24)

**Comment by adkinsrs** [comment]
This should fall under me, so I unassigned @jorvis

**Comment by adkinsrs** [comment]
Found a small bug where a variable wasn't being iniitialized... pushed to gear-devel.  Can you try again?

Also when you say push 4 datasets, you mean 4 displays, correct?

**Comment by DanLesperance** [comment]
This issue has been fixed.  

As for whether i meant displays, the +/- button on the dataset specifically was what was providing error.  I wasn't even able to get to image selection, but that's resolved now.

**Comment by DanLesperance** [comment]
Reopening as this bug seems to have been recreated. As I'm trying to create video tutorial.  Personal user (Daniel Lesperance) can create a new Collection (TutorialDemo1); however when clicking any of the +/-  public datasets in devel.umgear.org error pops up with "Something went wrong"

![Screenshot 2024-07-17 at 12 09 05 PM](https://github.com/user-attachments/assets/a8daac0d-4700-432a-b23e-97f8415c67b3)

**Comment by adkinsrs** [comment]
Sent back to @DanLesperance for testing on the staging area

**Comment by DanLesperance** [comment]
@adkinsrs Mostly works, ie. I can add dataset plots to the the dataset collection; however there's a small issue where you need to reload the dataset explorer page in order to have the dataset plots show up in the dataset collection arrangement view.

**Comment by adkinsrs** [comment]
Ah good to know... I'll get on that tomorrow.

**Comment by adkinsrs** [comment]
Try again?

**Comment by adkinsrs** [comment]
Sounds good. I already created #768 to address this.  I personally have not observed it.
