### ISSUE TITLE
gEAR Workshop - Two manual genes in expression genes multigene mode erroneously leads to "please provide 2 genes to proceed"

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#719]

**Comment by adkinsrs** [comment]
Cannot seem to replicate this. However heatmaps will produce this error with 2 genes if one of the genes is not found in the dataset.

**Comment by DanLesperance** [comment]
@adkinsrs I was able to replicate this issue using the following steps
- Search ATOH1, POU4F3, SOX2 in the gene expression search and click multi-gene dispaly (I used hearing (default profile))
- Remove all but one gene and click search, this should correctly tell you to provide at least two genes
- Switch the radio button to single-gene display with one gene and you still get the error and nothing happens

**Comment by adkinsrs** [comment]
Can confirm locally.  Will address soon

**Comment by adkinsrs** [comment]
Pushed a commit to address the last comment.
