### ISSUE TITLE
Move 'Projection analysis' left menu item under 'Analyze' category instead?

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#724]
Up for debate here

**Comment by jorvis** [comment]
Decision was to rename "Projection analysis" to just "Projection" but add a 'New' icon if possible.  Else create "New" menu category.

**Comment by JPReceveur** [comment]
With the renaming to projection, the text on the project page (top right text block) could be updated to just 'The projection tool ' so theres not a mismatch between the tool name and description

**Comment by jorvis** [comment]
Moving this out of the current project since too many videos have been made and, for now, I don't want to change any of the primary menus.

**Comment by JPReceveur** [comment]
Above minor change to text has been made by @adkinsrs
