### ISSUE TITLE
gEAR Workshop - Dataset Collection bugs / updates

### ISSUE THREAD

**Issue by DanLesperance** [IGS/gEAR#731]
- [ ] tsne / umap preview image resolution is pretty poor.  
- [ ] Create new dataset collection takes longer than 1-2 seconds
- [ ] Searching by dataset name currently has a min character length of 3 -- for example search "p8" won't work

**Comment by jorvis** [comment]
Can these things be separate tickets please?  It's easy to note and close them as we go.

**Comment by jorvis** [comment]
The project itself organizes them together, so we don't also need a grouping ticket
