### ISSUE TITLE
gEAR Workshop - Single Gene / Multi Gene curator bugs / updates

### ISSUE THREAD

**Issue by DanLesperance** [IGS/gEAR#732]
- [ ] Move "Change Gene" outside plot configuration --- or add a "Current Gene" at the top of the page near the Dataset and Analysis sections
- [ ] During curation process change the cursor to a hand when over the entire dropdown box to let the user know they can click anywhere

**Comment by jorvis** [comment]
Again, let's avoid multi-issue tickets and create one per task, each organized under the project.
