### ISSUE TITLE
Gene Expression Search - Set default organism should be button and not question

### ISSUE THREAD

**Issue by DanLesperance** [IGS/gEAR#734]
Currently you're asked a question to set default organism, we should change this to a button to make it obvious to the user to click on this to change organism

![Screenshot 2024-07-08 at 11 17 34 AM](https://github.com/IGS/gEAR/assets/32070437/6e41005d-1123-4cad-8ed4-246845b7163a)

**Comment by jorvis** [comment]
Done and updated on devel.
