### ISSUE TITLE
Gene Expression Search - Search results should follow with scrolling

### ISSUE THREAD

**Issue by DanLesperance** [IGS/gEAR#735]
As you scroll down on the gene expression page, the gene search results should scroll down with you.  Currently they stay static.

![Screenshot 2024-07-08 at 11 20 51 AM](https://github.com/IGS/gEAR/assets/32070437/62805d06-4be5-4236-9cf3-8afb5e3c85eb)

![Screenshot 2024-07-08 at 11 21 12 AM](https://github.com/IGS/gEAR/assets/32070437/6ad6ef32-bdfd-47bc-a291-7cccee02e8ca)

**Comment by adkinsrs** [comment]
Gotta figure out some CSS magic here.  Setting `position: fixed` does the behavior but hides the gene results behind the dataset tiles.

**Comment by jorvis** [comment]
Hold on here or communicate with Will - he's working on this one currently.  I just can't assign the task.

**Comment by adkinsrs** [comment]
ah ok.  I found the solution anyways.  Use "sticky" position and give it a "top" offset in pixels to stick to

**Comment by jorvis** [comment]
I think he was actually going to try to instead cleanly make the result grid scroll and the rest of the page stay in place and see if we liked it.

**Comment by adkinsrs** [comment]
![Recording 2024-07-18 at 15 25 42](https://github.com/user-attachments/assets/27659f17-5665-4299-82e2-1871f48ba2f4)

Exhibit A

**Comment by jorvis** [comment]
Nice.  I like it, but I worry the next request will be if the annotation panel, search controls, etc. can be sticky too, in which case we should have added it to the result grid in the first place.  Thoughts @beamilon ?

**Comment by beamilon** [comment]
I like it too.
I am not sure people will ask to have the rest sticky. The goal (at least mine) for having the gene list scroll down is that sometimes I am interested in only one or two datasets in the profile, so I like the fact that I can click on the next genes without having to go all the way back to the top and then scrolling back down to view the specific dataset I wanted to see.

**Comment by wscerbo-igs** [comment]
> I think he was actually going to try to instead cleanly make the result grid scroll and the rest of the page stay in place and see if we liked it. We can see which we like better?

@jorvis Here's the selector that gives the search results box its own scroll. 

`#annotation-and-grid-c {`
`   max-height:100vh;`
`   overflow-y: auto;`
`}`

If we want to just have the search results column sticky, we can add what Sean posted above (plus we'll need the flex-start here). 

`div#gene-result-list-c {`
`   position: sticky;`
`   top: 0px;`
`   align-self: flex-start;`
`}`

**Comment by beamilon** [comment]
Sure. Let's see how it looks.

**Comment by jorvis** [comment]
@adkinsrs Let's go ahead and push that version out (with Will's note about the flex-start?)

**Comment by adkinsrs** [comment]
Updated with Will's solution
