### ISSUE TITLE
Navigation Menu - Dataset and Dataset Collection redirect to the same location

### ISSUE THREAD

**Issue by DanLesperance** [IGS/gEAR#738]
Datasets and Dataset collection in the Navigation menu redirect to the same location.  This is the only menu choice that does this and may be redundant

![Screenshot 2024-07-08 at 11 37 30 AM](https://github.com/IGS/gEAR/assets/32070437/71910e73-dfc1-462e-add7-895d2ff25d3b)

**Comment by jorvis** [comment]
I'm not sure what to "fix" here?  This is as the design team specified and I'm not sure where else either one of them would point to.  I think the idea was that the top link met the users' need to enter either by gene or by dataset, and the links lower were specifically to manage the different collections of things.  And both applied to datasets.  

Any alternative ideas?  @brianherb

**Comment by jorvis** [comment]
Making the executive decision for now to leave these how they are, especially since we have recorded videos already and don't want to redo them for a bit.
