### ISSUE TITLE
Single Gene / Multi Gene curator - Provide section for "Current Gene(s)"

### ISSUE THREAD

**Issue by DanLesperance** [IGS/gEAR#739]
In the display curation provide a Current Gene(s) section near the top with Dataset and Analysis showing current gene(s) that have been searched for so the user can easily see what gene they're curating for

![Screenshot 2024-07-08 at 11 42 56 AM](https://github.com/IGS/gEAR/assets/32070437/9024731e-8eb5-4773-8d70-423f527d15ce)

**Comment by adkinsrs** [comment]
For single gene, it's a simple line addition.  For multi-gene, I wonder if I should just put the number of genes, or a box showing all genes (similar to when you initially select genes/genelists). Thoughts @DanLesperance ?

**Comment by DanLesperance** [comment]
There's benefits to both ideas, namely with the box of all genes they can ensure every gene selected is one they truly want, but the number of genes I think is enough information to provide to the user.

My choice would be to add number of genes and not the entire box (which can become unruly with higher number of genes)

**Comment by adkinsrs** [comment]
I agree.  For the box, in other situations I have just added a "+ 31 genes" button that could be expanded if there were more than 10 genes, but keeping the element as a number lets the style be more consistent between the two curator types
