### ISSUE TITLE
Single Gene / Multi Gene Curator - Change cursor for dropdown 

### ISSUE THREAD

**Issue by DanLesperance** [IGS/gEAR#740]
During the curation process for single-gene and multi-gene curation, the dropdown boxes are each clickable, we should change the cursor to a hand to show that the boxes are clickable anywhere and not just on the dropdown arrows. 

![Screenshot 2024-07-08 at 11 46 51 AM](https://github.com/IGS/gEAR/assets/32070437/a34b37cd-c9b4-42c0-b760-229f2da62e6c)

**Comment by adkinsrs** [comment]
Added CSS to make the "header" of each step have a clickable cursor but the section content have the original arrow
