### ISSUE TITLE
MyWorkspace Dashboard Guides - Change one of the "Search faster using gene lists and dataset collections" to a gEAR 2.0 Changes Walktrhough

### ISSUE THREAD

**Issue by DanLesperance** [IGS/gEAR#746]
The "Search faster using gene lists and dataset collections" guide exists in two places on the My Workspace Dashboard.  Probably best we provide a guide on the gEAR 2.0 changes.

![Screenshot 2024-07-11 at 11 06 49 AM](https://github.com/IGS/gEAR/assets/32070437/1d5fd168-f5be-4f2b-b15e-020d87e5dc2b)

**Comment by jorvis** [comment]
This has been done.
