### ISSUE TITLE
Staging gEAR-Comparison tool-X and Y axis not resetting after change of parameters

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#751]
@adkinsrs 
The following happened with several dataset but here is an example with the P30, mouse, snRNA-seq, Stria Vascularis (Hoa).
Using the compare tool, I compared Marginal and Intermediate cells and it worked fine. Then I went back to change the parameters, chose to compare Basal and Spindle/Root cells. The X and Y axis do not reset so I can change the cell types. It is locked in Intermediate and Marginal cells.
![image](https://github.com/user-attachments/assets/f96203af-fa89-4d02-b05f-c59a43240f41)

**Comment by adkinsrs** [comment]
@beamilon have you tried unchecking one of those two checkboxes?  The validation should reset the checkboxes to be OK.  But I do agree that it should be clearer.

Also, if you are choosing "cell types" in X and Y, you do not need to filter them out in the "shared filtered conditions" step. That step is meant for filtering to a subset of data beyond what you choose for X and Y (i.e. look at Intermediate and Marginal cell types only at the 24hr timepoint if "timepoint" was a field in your dataset)

**Comment by beamilon** [comment]
@adkinsrs 
Unchecking the checkboxes doesn't work. The choice is still lock on the previous parameters.
![image](https://github.com/user-attachments/assets/f8d70f21-3be9-4d2e-a1f7-b72652927f8c)

**Comment by adkinsrs** [comment]
While changing the "series to compare" would cause the checkboxes to re-render, the best solution would be to add triggers on the "filter" selections to disable and enable boxes if a series is rendered.  I also changed some of the text to help the user understand that the "shared filters" are meant to filtering subsets of data beyond the main series to compare.

**Comment by adkinsrs** [comment]
![Screenshot 2024-07-22 at 8 38 58 AM](https://github.com/user-attachments/assets/f567a84c-f41a-4e55-acf7-788cdb86c4f1)

Was chatting with @DanLesperance and I think what I am going to do is swap the "series to compare" section and the "shared filters" section to promote a better flow.  First you select the series you want to compare, which will be excluded from the "secondary/shared filters", so there is less chance of running into situations like @beamilon's screenshots where the X/Y conditions are filtered out.

**Comment by adkinsrs** [comment]
Commit [804b990](https://github.com/IGS/gEAR/commit/804b990d2c328f83b0eda61b5391f51af8033f4f) address my proposed changes.  You select the series first, and this hides that out of the filter categories.  Changing the compare series again will reset the state of the selected series groups (x and y) as well as the selected filters.
