### ISSUE TITLE
Staging gEAR, scRNAseq workbench-Primary dataset filtering

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#752]
@adkinsrs 
In the primary dataset filtering, the pre-filled 300 needs to be moved to "Exclude cells with <"
![image](https://github.com/user-attachments/assets/fd7e0a7d-0eb3-4189-8a76-0cb8becea789)

**Comment by beamilon** [comment]
@adkinsrs 
That was fast :)

**Comment by beamilon** [comment]
I just saw that when I click "apply filter", once it is done, the 300 reappears in the "Exclude cells with >". Since it is after the step, it is not a problem but it look strange.
![image](https://github.com/user-attachments/assets/8755e8ab-fec7-485f-a262-ab3d8ad08e20)

**Comment by adkinsrs** [comment]
I just pushed a fix that addressed this right before I left work. Refresh the page

**Comment by adkinsrs** [comment]
The extra 300 shouldnt be there. I'll look, but it may be how you are testing right as I updated the codebase

**Comment by beamilon** [comment]
Ok. Thank you.
