### ISSUE TITLE
Staging gEAR-Marker gene visualization-"Visualize" icon inactive

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#754]
@adkinsrs 
In the Marker gene visualization step, the "Visualize" icon doesn't get activated when a gene is entered in the box (I tried slc26a4 and Slc26a4 in case the lower case was the problem), top image.
The icon gets activated only if a gene is highlighted in the table, bottom image.
![image](https://github.com/user-attachments/assets/cfbc62fe-e703-4d40-9fe2-c28df59b7bdd)
![image](https://github.com/user-attachments/assets/625ace7b-1719-46ad-9a8f-65bd92c608a4)

**Comment by adkinsrs** [comment]
Changed it so that inputting text in the "manual gene entry" field will enable the button (or disable if empty and no genes in table selected).  Note there is no check to see if the text entered is a valid gene though.
