### ISSUE TITLE
Staging gEAR-"Something went wrong message" but can't figure out what went wrong.

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#755]
@adkinsrs 
With 2 different datasets (mouse, scRNA-seq, Organ of Corti Violin Plots (Waldhaus) and P1, mouse, scRNA-seq, cochlear epithelium (Kelley)), when I loaded the Primary analysis and then click the "Compute" icon, everything seemed to work great but I got a "Something went wrong. Please contact the gEAR team and provide steps to reproduce." message. Nothing seems wrong to me. I opened the console for the page in the second example.
![image](https://github.com/user-attachments/assets/ce171787-b25e-40eb-a9da-d357ceaca5cc)
![image](https://github.com/user-attachments/assets/a9f5a2c5-1609-4970-8ba6-4c2cac5ec835)

**Comment by adkinsrs** [comment]
Error is in the "save analysis" step where I convert snakeCase property names into camel_case, but for some reason there is a null being passed in.

**Comment by adkinsrs** [comment]
Resolved.

1) There was a bug where the workbench attempted to save primary analyses (bad property reference)
2) As the previous comment suggests, the script was trying to convert null values into snake_case and failing.
