### ISSUE TITLE
Staging gEAR-The "Sort by" in the dataset explorer does not sort accurately

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#756]
@adkinsrs 
The Sort by feature seems to be sorting randomly.
![image](https://github.com/user-attachments/assets/11b2dd27-2e26-4f58-bf2b-aa2758eaa981)
![image](https://github.com/user-attachments/assets/81d36342-985d-4e72-906c-b1c94184307f)
![image](https://github.com/user-attachments/assets/a0282c65-958d-4855-a916-b0cf8f31611a)

**Comment by beamilon** [comment]
Related to that I think, when the sort by "Owner" is selected, the results numbering on top of the page is totally off.
![image](https://github.com/user-attachments/assets/aa610bbf-1044-41fa-9f23-81c598d1b6bc)

**Comment by adkinsrs** [comment]
I think the datasets are being "unsorted" after being returned from the server.  I'll get to the bottom of it.

**Comment by adkinsrs** [comment]
Fixed.  And closing
