### ISSUE TITLE
Primary row IDs (not share IDs) used for gene lists in V2 code

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#758]
In the common.v2.js code there's a mixin method:

`async fetchGeneCartMembers(geneCartId) {
`

This appears to only currently be used by the gene list manager code, but we should not be using primary row IDs anywhere in the interface or the API calls on the JS level.  It allows too many openings for users to access data that isn't theirs.

**There are other priorities right now before the v2 release** and I'm going to create another method alongside this one for my own needs which uses the same CGI script but calls using share IDs instead.  When possible, we need to transition this code to not use primary IDs.

**Comment by adkinsrs** [comment]
Fixed the edits to the gene_list_manager page (where the CGI was only used to download an unweighted gene list).  Also removed references to supplying a gene list ID as an argument (which involved some merge conflict resolution.
