### ISSUE TITLE
Gene list manager - Make view 'remembered'

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#761]
The user shouldn't have to reclick their preferred view every time they load the page.  Instead let's remember their last selection and do that again until they change it.

![Screenshot from 2024-07-17 13-00-15](https://github.com/user-attachments/assets/a930ce3e-6999-410e-9aa4-6c03dbc83305)

**Comment by adkinsrs** [comment]
I'll do this with the dataset collections page as well.

**Comment by adkinsrs** [comment]
The intention was to save this as part of the User object.  I feel that some settings, like organism, would be shared across both gene lists and dataset collections though, whereas others, like "date added" would need to be separate between the two.  Thoughts?

**Comment by jorvis** [comment]
I can see arguments either way.  I was seeing layout and cart selection as more transitory, where cookies sufficed. Also it means those quick preferences aren't limited to users with accounts.  It would just work with anyone using the site.
