### ISSUE TITLE
Staging gEAR - Dataset information is not available

### ISSUE THREAD

**Issue by RAmanipour** [IGS/gEAR#762]
@adkinsrs When I click on the "Dataset Information", I receive an error message stating, 'This feature is not yet implemented.' However, in the older version of gEAR, it displays the dataset information.

New version of gEAR:
![image](https://github.com/user-attachments/assets/c84a56f8-1ef2-43f2-816f-6b00124c56c6)

Old version of gEAR:
![image](https://github.com/user-attachments/assets/c5571d54-a956-41ad-968b-38712e772bf8)

**Comment by adkinsrs** [comment]
Closing as it is now implemented on the staging server

**Comment by RAmanipour** [comment]
Thank you Shaun, it is now working in the new version of the gEAR:

![image](https://github.com/user-attachments/assets/9015240d-0dc4-4f73-8f41-2471021cff58)
