### ISSUE TITLE
Staging gEAR - Too many significant digits

### ISSUE THREAD

**Issue by RAmanipour** [IGS/gEAR#763]
@adkinsrs When moving the cursor over the data, the Y-axis value and standard deviation are shown with 18 significant digits, whereas in the old version of gEAR, they were displayed with only 2 significant digits.

New version of gEAR:
![image](https://github.com/user-attachments/assets/b4dac312-1fad-419b-9cb8-22546ccacaca)

Old version of the gEAR:
![image](https://github.com/user-attachments/assets/d3800884-4f2b-4d8c-b2ce-304ee0dee6b6)

**Comment by adkinsrs** [comment]
Probably due to the update in Plotly versions.  I'll adjust when I get the time for it.

**Comment by adkinsrs** [comment]
@RAmanipour , How old is the 2nd image from your comment?  The v1 version of gEAR (at umgear.org) does not format hover data values like the one you have pictured.

**Comment by adkinsrs** [comment]
Fixed it so that sigfigs are rounded to 2 places

**Comment by RAmanipour** [comment]
Perfect, it is now fixed, Thank you!

![image](https://github.com/user-attachments/assets/80bff0e8-0af0-4cdd-988e-3c3d4b036356)
