### ISSUE TITLE
V2: Some images are 'stretched' with incorrect aspect ratio

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#765]
Example, the top image is stretched too wide, which is especially noticeable in the font text.

![Screenshot from 2024-07-18 10-43-53](https://github.com/user-attachments/assets/da6c3d2d-9ee4-412f-b077-60efe136e272)

**Comment by jorvis** [comment]
If I correct this so the image maintains its aspect ratio (CSS contribution from @wscerbo-igs, do we like this better? 

![Screenshot from 2024-07-18 10-45-40](https://github.com/user-attachments/assets/fb755b57-9ae7-4879-b480-5f63a11592d5)

Thoughts @brianherb @DanLesperance

**Comment by DanLesperance** [comment]
This aspect ratio looks significantly better and cleaner than before.

**Comment by jorvis** [comment]
@adkinsrs  - Could this be improved further by informing the drawing API of the aspect ratio and having it create an image with that in mind?  In this layout, for example, the top dataset is configured to have a 3:1 aspect ratio.  Does the underlying plotting library take this as an argument?

**Comment by adkinsrs** [comment]
More discussion is found here -> https://github.com/IGS/gEAR/issues/705

**Comment by adkinsrs** [comment]
But yes, I can add parameters to pass in a aspect ratio.  In #705, I had discussed having variable aspect ratios for the normal tSNE and the "expanded" version

**Comment by jorvis** [comment]
Also, here's what the zoomed version looks like:

![Screenshot from 2024-07-18 12-02-41](https://github.com/user-attachments/assets/842938d8-616e-4ca3-b68f-77b58b13cbaf)
