### ISSUE TITLE
Quick search boxes can go off the page if left menu is collapsed

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#769]
Will is going to look at this one.

But if you go to the main workspace page:

https://staging.umgear.org/

And then click the "Quick search using Gene Lists" a custom menu appears.  This survives decently as the page is resized, but if the left main navigation menu is collapsed, the box shifts off the left side of the window.

![Screenshot from 2024-07-18 14-54-48](https://github.com/user-attachments/assets/7fc52dd6-d4c9-442d-af2c-e72da344bda9)

**Comment by adkinsrs** [comment]
The CSS I had added to address this was only applied to the gene-collection-selector.css file.  In most cases the other selectors were either to the right enough where it wasn't an issue, or the "is-right" class was added to the dropdown to remedy this

**Comment by wscerbo-igs** [comment]
We could either keep the dropdown at a fixed size to prevent the overflow at larger screen sizes (greater than ~1100px) or add a bit of javascript that toggles the `.is-right` class on `#dropdown-gene-lists div.dropdown-menu` with a click event listener on `#navbar-toggler` - let me know which one sounds better to you all.

**Comment by jorvis** [comment]
As I was implementing the toggle above I decided to instead switch them such that the gene list selector is always left aligned, and the dataset one is always right aligned (both on index and expression pages)  That seems to keep them off the edges for reasonable window widths.  For any other pages which incorporate these later we can still dynamically set these as needed with JS
