### ISSUE TITLE
Projection Analysis is constantly giving "Error: Something went wrong with the projection-creating step."

### ISSUE THREAD

**Issue by DanLesperance** [IGS/gEAR#771]
- The initial projection worked using Cochlear HC's adult Gene List and Hearing (Default) dataset collection.
- Moving to Type 1a SGN's provides this error, also receive it on IHC's Adult

![Screenshot 2024-07-19 at 10 14 18 AM](https://github.com/user-attachments/assets/926066b9-9007-469c-8350-6bec6b75f9e8)

**Comment by adkinsrs** [comment]
The steps weren't working at all this morning due to adjustments to the GeneCart table in geardb.py.  Will need to investigate more.

I may just need to restart the projectR consumer.

**Comment by adkinsrs** [comment]
Hmm... not replicating this locally

**Comment by adkinsrs** [comment]
@DanLesperance care to try again?
