### ISSUE TITLE
gEAR staging: X icon in guides on my workspace has no functionality

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#774]
In the guides section on the my workshop page, there is a x in the top right. Currently it doesn't appear that this is clickable to get rid of/collapse the guides section.

**Comment by jorvis** [comment]
I'll probably drop them out.  They were in the design group's spec but I'm not sure why they should be there.  

Any disagreement?

**Comment by JPReceveur** [comment]
Nope, sounds good to me

**Comment by adkinsrs** [comment]
No arguments here. The guide should always be available.  Only thing I could think of is if the guide section was closed, it could be remembered, and the left panel could be condensed into a smaller full-width panel.

**Comment by JPReceveur** [comment]
On other pages, the x has functionality so that might be a point in favor of keeping it the same as the other pages e.g. https://staging.umgear.org/compare_datasets.html

**Comment by jorvis** [comment]
I think the initial design idea was that they could close it, recover that space, and then it would be ON that page that work happened.  But when a search or anything occurs the page is replaced with another, so that flow doesn't happen.  So for now I just removed the X.

**Comment by adkinsrs** [comment]
I think the X will still need to be removed for all the "tool"pages. But the "x" functions on all those pages too.
