### ISSUE TITLE
gEAR staging: Citation block copy icon doesn't have functionality

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#776]
On the left dashboard, the citation block has a copy icon that looks clickable if you hover over it. However it doesn't copy the citation to the clipboard if you click on it.

<img width="259" alt="Screenshot 2024-07-19 at 11 18 00 AM" src="https://github.com/user-attachments/assets/9cf40f2a-2fca-4e38-9eef-e9b2fa55ec0d">

**Comment by jorvis** [comment]
Fixed
