### ISSUE TITLE
gEAR staging: Improve error message for select default organism for functional annotation

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#778]
When selecting a default organism under functional annotation, the dropdown allows you to have the it set to  'select an organism' and click the 'set default button'. This gives back a generic error message. Could either the error message be made clearer or it modified so you can't try to use the nonsensical value as a a default in the first place?

<img width="1591" alt="Screenshot 2024-07-19 at 11 31 45 AM" src="https://github.com/user-attachments/assets/b5d3ed9f-8714-48d3-a31f-00e1c14b8a38">

**Comment by jorvis** [comment]
Fixed
