### ISSUE TITLE
gEAR staging: 'Show only selected collection datasets' does not change search results

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#780]
In the dataset explorer, moving the 'Show only selected collection datasets' toggle does not result in the list to the right being subset to only datasets in the current collection.

<img width="1514" alt="Screenshot 2024-07-19 at 12 04 51 PM" src="https://github.com/user-attachments/assets/9b855638-aef5-4836-9332-bbd349e9b087">

**Comment by adkinsrs** [comment]
It may be that an explicit search (with keywords & filters) will add in the collection share ID if the toggle is set.  I need to change it to also perform the search if the toggle is changed.

**Comment by jorvis** [comment]
From meeting with Beatrice/Ronna, this is a priority when you're able to resume tickets.

**Comment by adkinsrs** [comment]
The event callback previously only changed if a layout share id should be passed to the dataset search or not.  Now it also triggers the dataset search too.
