### ISSUE TITLE
Staging gEAR-Single cell workbench not working when selected from the dataset itself

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#782]
@adkinsrs @JPReceveur 
The problem happened with the different datasets I tried.
When getting to the single cell workbench from a specific dataset (top picture), the workbench doesn't load the dataset so the "select new or saved analysis" stays inactive. Clicking on the highlighted dataset in the "select a dataset" drop down doesn't do anything (bottom picture).
![image](https://github.com/user-attachments/assets/6cb2739c-d898-4043-a153-53fb51c27d1f)
![image](https://github.com/user-attachments/assets/249288da-ab7a-402c-9d72-ad6243096102)

**Comment by adkinsrs** [comment]
I think what is happening is that the dataset is being set as active in the tree structure but it is not triggering the select, which would do cascading things.

**Comment by adkinsrs** [comment]
Should work now
