### ISSUE TITLE
gEAR staging: duplicates present in 'Found in these collections you own'

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#785]
In the dataset explorer, it looks like any collection that is a site- curated collection ends up with a duplicated value under the 'Found in these collections' section. 

Putting as low priority since I'm guessing its only related to 'site-curated displays'. I wasn't able to replicate issue on my personal account.

<img width="1322" alt="Screenshot 2024-07-19 at 12 19 05 PM" src="https://github.com/user-attachments/assets/9adb984c-7cdb-47a3-a440-adbb2248384b">

**Comment by adkinsrs** [comment]
Can confirm this with my own user account as well

**Comment by adkinsrs** [comment]
Resolved in commit [28308ed](https://github.com/IGS/gEAR/commit/28308ed6cbbddbba76880a7039dbc89cde584516)
