### ISSUE TITLE
gEAR staging: Dataset explorer group searching results in error message when no datasets are present

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#787]
If you search for group-affiliated datasets under ownership in the dataset explorer and you don't have any, it returns an error popup with the message 'failure to search datasets'. Should this just be returning a 'no results found' in the search instead of looking like an error?

<img width="1587" alt="Screenshot 2024-07-19 at 12 37 30 PM" src="https://github.com/user-attachments/assets/ce4ad449-e67d-4a86-9c2f-ee113ed7b5cc">

**Comment by adkinsrs** [comment]
Code has been committed, and I tested the SQL query in the MySQL REPL, but have not tested it from a browser perspective (in the sense that my user is not in any groups and will return no datasets).  

I also made the equivalent change in the gene lists manager page.
