### ISSUE TITLE
Staging gEAR-Choosing a profile in the dataset explorer does not display the datasets from that profile

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#788]
@adkinsrs @JPReceveur 
In the dataset explorer, choosing a profile under the Collection management does not update the list to display the datasets present in the profile. The old version of gEAR had an eye icon to update the list.
![image](https://github.com/user-attachments/assets/1a30afd5-33f8-43f7-bc42-2bc595552838)
![image](https://github.com/user-attachments/assets/19c91dc5-4448-4191-b58a-67ed05b9bed0)

**Comment by adkinsrs** [comment]
@beamilon Look at the "show only selected collection datasets" toggle.

**Comment by adkinsrs** [comment]
I wanted a more distinctive way to let the user view only datasets within a collection or all datasets.

**Comment by JPReceveur** [comment]
https://github.com/IGS/gEAR/issues/780

**Comment by beamilon** [comment]
> @beamilon Look at the "show only selected collection datasets" toggle.

I did but toggling the toggle doesn't update the list either.

**Comment by adkinsrs** [comment]
Going to close this in favor of #780
