### ISSUE TITLE
gEAR staging: Profile arrangement view includes search results bar but no search results

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#790]
In the profile arrangement view in the dataset explorer, if you select the sort by dropdown, it results in the search par page navigation showing up. This should probably be disabled for profile arrangement (since its not showing anything useful for arrangments).

<img width="1584" alt="Screenshot 2024-07-19 at 1 00 44 PM" src="https://github.com/user-attachments/assets/f617193b-13c9-4338-9520-31bfd4ee5be2">

**Comment by adkinsrs** [comment]
So I think you happened to have caught that error right as I was updating code on the server.

Can you confirm that still happens with a fresh page?

**Comment by adkinsrs** [comment]
Pushing commit to hide the "sort by" which when modified brings up the pagination section.
