### ISSUE TITLE
Staging gEAR-Alphabetical order of the profiles in the drop down menu

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#791]
@adkinsrs 
This is not high priority.
The alphabetical order of the profiles takes into account the fact that the first letter is either upper case or lower case. Upper case names are listed first, then the lower case ones.
![image](https://github.com/user-attachments/assets/5d0ccaf0-f07c-430a-bfe2-b150bf0a5e9c)

**Comment by jorvis** [comment]
This has been fixed but I haven't updated the production servers for this minor change.
