### ISSUE TITLE
gEAR staging: Profile arrangement enhancements

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#792]
On the profile arrangement page , a dataset in the collection doesn't show up in the multigene window unless a multigene display has already been made. We should have some text or maybe a tooltip next to the multigene display header letting people known that if they want to curate the multigene layout, the datasets need to have a multigene curation first.

**Comment by adkinsrs** [comment]
What I've done so far.

* If no singlegene and multigene layout display members - notify that you should add some
* If one of the two has no members, just hide that arrangement view container

For the second one, do you think that is enough, or should I add a message saying to add some (like you suggest in the opening comment)?

**Comment by JPReceveur** [comment]
I think thats fine for now
