### ISSUE TITLE
gEAR staging: Ortholog mapping issue with chicken datasets

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#793]
Ran into an issue with displaying a profile, from the messages seems to be related to orthologs for these particular datasets. 

Steps to reproduce, choose chick collection and a gene cart (cochlear hair cells adult) or single gene (e.g. atoh1)

<img width="1569" alt="Screenshot 2024-07-19 at 1 33 29 PM" src="https://github.com/user-attachments/assets/72ee5eb4-b3fd-4ec4-a30a-fbd191f27649">

**Comment by JPReceveur** [comment]
Tagging with low priority, haven't been able to reproduce with other chicken datasets, might just be a dataset specific issue.

**Comment by adkinsrs** [comment]
I've found datasets where the gene should have ideally been found being the correct organism but the gene was not in the dataset for some reason.

**Comment by jorvis** [comment]
Seems like what is needed here is just a better error message then?

**Comment by beamilon** [comment]
I went through all the datasets in profiles and the error appears in every single chick datasets. So I would change that for a high priority ticket.
![image](https://github.com/user-attachments/assets/e47dbbec-6149-42a5-b42c-d9b66ce8d0db)

**Comment by jorvis** [comment]
@adkinsrs Is this a difference in how the code is handling feature mapping in v2?  We will not always have mapping between organisms, and in v1 we also don't have orthology files for chicken, since they're not part of the alliance of genomes datasets.

But it seems in v1 rather than putting up an error we just aren't mapping and instead only showing the genes which have the same names. That should be happening here too.

**Comment by adkinsrs** [comment]
Generally if the input gene does not have an ortholog to map to, I use the original gene which will be filtered out of the dataset's gene list most likely.  This is a different error entirely, were ortholog mapping did not return a list of genes (should always return the map or the original), meaning there was probably an error in the script I need to correct for and handle.

**Comment by adkinsrs** [comment]
Should be fixed now.  If a mapping file is not found, the API will catch the FileNotFoundError and handle gracefully, using the original gene symbols passed in.
