### ISSUE TITLE
Staging gEAR-Sort by owner result number inaccurate

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#794]
@adkinsrs @JPReceveur 
When sort by "owner" is selected, the result number is huge and random.
![image](https://github.com/user-attachments/assets/0a6822a7-cec9-4f2b-9403-96c03f449528)

**Comment by JPReceveur** [comment]
Similar issue as  https://github.com/IGS/gEAR/issues/781

**Comment by adkinsrs** [comment]
Closing for #781
