### ISSUE TITLE
Comparison tool: Allow users to define comparison-eligible columns

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#80]
The comparison tool dynamically generates the menu options based on observation columns not in an exclusion list. If there are more than 5 columns it throws a descriptive error to the user.

It would be nice if at some point in the dataset upload or in the Explorer the user could instead choose which obs columns are appropriate to be included as conditions in the comparison tool.

It is the same as ticket under Josh account https://github.com/IGS/gEAR/issues/6

**Comment by adkinsrs** [comment]
Ready for testing now.  Waiting for the production rollout to complete then I will push this to the devel server

**Comment by adkinsrs** [comment]
Merged branch "issue_80" into "new_mg_plots" for easier testing of both the multigene curator and the compare tool on the development server

**Comment by adkinsrs** [comment]
Closing this ticket for now since the issue seems to be resolved, and #150 is addressing other minor issues related to this
