### ISSUE TITLE
gEAR staging: single cell workbench view top genes per PC 

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#804]
In the single cell workbench at the view top genes per PC step, can the principle components to view button be greyed out until principle components are added (since it'll fail with a nonspecific error code if you don't supply any PCs)? Alternatively the error message could be more informative here. 

<img width="1254" alt="Screenshot 2024-07-22 at 11 17 13 AM" src="https://github.com/user-attachments/assets/2054651a-00b5-401c-986d-a5fdb68f7c0d">

**Comment by adkinsrs** [comment]
Button is disabled by default and is enabled when input contains a number in the first element (comma-separated)

If the Run button is clicked, it will throw an error before running if all comma-separated elements cannot parse to integers
