### ISSUE TITLE
gEAR staging: single cell workbench, unique check when saving PCs as pattern signatures 

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#805]
If you use the save PCs as a pattern signature step in the workbench the green 'saved' popup takes a bit to show up but the spinning wheel on the save PCs stops prior to the success popup.

If you're impatient and keep clicking you end up with something like below.
Should we be checking for name uniqueness within a user when saving new gene patterns?

<img width="931" alt="Screenshot 2024-07-22 at 11 27 55 AM" src="https://github.com/user-attachments/assets/0de04d8e-e6d0-40a6-b5ed-b897f87feeb3">

**Comment by adkinsrs** [comment]
Addressed with commit bc4f12d

The actual "save" server side call should have not a blocking indicator (async/await) but did not.  The "loading" icon should stay until the "success" indicator happens
