### ISSUE TITLE
gEAR staging: unable to edit gene cart metadata/description

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#807]
In the gene list manager, if you try to make edits to the descriptions, visibility, etc of gene lists. when you hit save it returns a 'Failed to save gene list changes' message. Replicated on both my personal and curator accounts
<img width="1651" alt="Screenshot 2024-07-22 at 11 41 29 AM" src="https://github.com/user-attachments/assets/e912f9be-d844-408d-b601-4a5608afa91a">

**Comment by adkinsrs** [comment]
Fixed
