### ISSUE TITLE
gEAR staging: external resources and annotation linkouts when not logged in

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#810]
When logged out, the external linkout and annotation boxes are present but don't display any information on load. It requires an organism to be set under functional annotation and then it works, (guessing the default isn't being set when logged out).

<img width="922" alt="Screenshot 2024-07-22 at 12 19 42 PM" src="https://github.com/user-attachments/assets/9e7cfac7-f68d-4634-bb1a-f71a9c93bd06">

**Comment by jorvis** [comment]
This is currently by design, yes.  When they expand functional annotation a pop-up should appear asking to choose an organism.  Suggested why to set a default one for those not logged in?

**Comment by JPReceveur** [comment]
Thats fine for not setting a default if its intentional.
Was just think if a user doesn't have an account, they likely are not going to know enough about gEAR to realize they have to hit the functional validation dropdown and it looks just like something went wrong. 
Having the 'Select an organism popup' up one level on the dropdown might help cue people in to the need to do something but it would make the page more cluttered. If it works for you I'll close this as a will not do for now and think about it more.

**Comment by jorvis** [comment]
It's OK to leave it open.  I may scan the datasets and just default show the first organism represented there.  The organism stuff was a level up before and people wanted it moved, so here we are.  :)

**Comment by jorvis** [comment]
Fixed.  First organism in the dataset collection is now autoselected.
