### ISSUE TITLE
Comparison tool: Make unweighted the default save method

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#811]
Here the user has selected a few genes, and they want to save them. But the default option is to save the full set as a weighted list.  This is counter-intuitive since it's underneath a table of genes they manually selected.

![Screenshot from 2024-07-23 11-07-39](https://github.com/user-attachments/assets/96002951-8b09-4edf-9074-a648b83e993d)

**Comment by adkinsrs** [comment]
Makes sense.  I think the original intent was that the user could only save weighted if nothing is selected at all, but I can add a trigger to select "unweighted" in the "selection" callback.

**Comment by adkinsrs** [comment]
Pushed to production
