### ISSUE TITLE
Staging gEAR-Zooming on a dataset and going back to zoom out

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#812]
@adkinsrs @JPReceveur
It may be a one-time bug but I zoomed in the P1, mouse, scRNA-seq, utricle, hair cells, supporting cells, and transitional epithelial cells (Kelley) and when I went back to the zoom out page everything became weird.
![image](https://github.com/user-attachments/assets/9cd0c908-8752-4b61-822d-401b672334d2)

**Comment by adkinsrs** [comment]
I think i've encountered something similar in the past.  What could be happening is the CSS "grid" system is not resetting the row height after exiting zoom.

**Comment by adkinsrs** [comment]
@beamilon can you confirm this is still an issue given the dataset tile styling has been adjusted over the past week or two?

**Comment by beamilon** [comment]
It is an issue that happens really randomly so right now it is ok.

**Comment by adkinsrs** [comment]
I have observed it as well on nemoanalytics.  In addition, if you expand a dataset, then click a new gene or pattern, the expanded plot is not updated.

**Comment by adkinsrs** [comment]
Believe this and #721 are related

**Comment by beamilon** [comment]
Yes it is possible.
"In addition, if you expand a dataset, then click a new gene or pattern, the expanded plot is not updated.": it was always the case even with v1. I think Yang mentioned that it is a Cache problem but I am not an expert.

**Comment by adkinsrs** [comment]
I'm going to mark this closed based on previous updates.  It seems the plot scaling issue happens when zooming in, selecting a gene (which re-renders the zoomed-out displays), then zooming out again.  I set the behavior to zoom back to all displays before rendering the displays for the new gene.
