### ISSUE TITLE
Issue Creating Plotly Plot for Specific Dataset and Parameters on Tablet

### ISSUE THREAD

**Issue by samgevine** [IGS/gEAR#815]
Having issues creating a plotly plot for a specific dataset and parameters using iPad. See attached screenshots.

![IMG_1254](https://github.com/user-attachments/assets/1f3e4657-1f3b-4112-a0c1-50fea94fb408)
![IMG_1253](https://github.com/user-attachments/assets/d86d176a-ac52-4d14-84cd-095ad7845eae)
![IMG_1252](https://github.com/user-attachments/assets/3530c35a-6b54-4ad6-b793-95d4180b3bc5)
![IMG_1251](https://github.com/user-attachments/assets/140da885-4b97-4a4d-802c-fb27a5ea171a)

**Comment by DanLesperance** [comment]
@samgevine Can you try to create the plot with X and Y being different parameters rather than both expression and let me know if this works

**Comment by adkinsrs** [comment]
At the very least we should have a validation check to ensure X and Y are different.

**Comment by samgevine** [comment]
For whatever reason the only X and Y parameter options I have are identical. Potentially a problem with the dataset?

**Comment by adkinsrs** [comment]
@samgevine When a dataset is loaded, all categorical and continuous metadata is retrieved from the dataset.  If "expression" was the only column you saw, it could be that the observation (sample or cell) metadata is empty.  Can you inform us what dataset you selected?

**Comment by samgevine** [comment]
The dataset was “ P25-27, spiral ganglion neurons, scRNA-seq, Goodrich lab (normalized)”

**Comment by beamilon** [comment]
It's a problem with the dataset not with gEAR. Some info is missing from the raw data to be able to analyze it. It is better to use the one that is not normalize.

**Comment by DanLesperance** [comment]
@adkinsrs perhaps we create a new ticket with the validation check you proposed earlier along with a validation check to ensure there's more than one option available for X and Y, if not we provide an error saying that the dataset does not have enough categories to plot

**Comment by adkinsrs** [comment]
@DanLesperance done, and will close this in favor of #819
