### ISSUE TITLE
Ortholog lookup box

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#82]
From Ronna:

This is a request from the HRP - we need to have an 'ortholog lookup' function somewhere in the top page links or somewhere else.

Explanation - for many genes there are different gene names for orthologues. So, if someone is interested in atoh1 in mouse, in zebrafish they are called atoh1a and atoh1b and in other species they may have a completely different name.

Can we have a hyperlink that says 'orthologues' that either results in a floating box or opens to another resource (does one exist?) that shows the orthologues for the gene across different species - and at minimum - mouse, human, chick and zebrafish

**Comment by jorvis** [comment]
[Biomart](http://www.biomart.org/) is usually considered the leading tool/approach here.

**Comment by RLC-DCPPC** [comment]
@jorvis this needs to be done by 1/26

**Comment by jorvis** [comment]
Other sources:

- https://www.alliancegenome.org/downloads#orthology
- https://www.ncbi.nlm.nih.gov/homologene/?term=ATOH1 (rapid first solution)

**Comment by jorvis** [comment]
HomoloGene links are now added and can be seen on devel.
