### ISSUE TITLE
Clarification on tilegrid intended scope

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#821]
On the expression page the tilegrid variable is initially declared (via let) in the script's global space:

https://github.com/IGS/gEAR/blob/ui-v2/www/js/expression.js#L11

But then when it is loaded the setupTileGrid() does so with a function-scoped 'const' declaration:

https://github.com/IGS/gEAR/blob/ui-v2/www/js/expression.js#L455

I have some functions outside of this which could benefit from being able to access the tilegrid after it's already loaded, but is there a reason I shouldn't just remove the 'const' part there so the global version is set instead?  Just want to make sure this variable shadowing wasn't intentional, since it's a core aspect of this page.

**Comment by jorvis** [comment]
Aaaaaaand, nevermind.  I see you're returning it and saving over the global one when you catch the call.

https://github.com/IGS/gEAR/blob/ui-v2/www/js/expression.js#L474

**Comment by adkinsrs** [comment]
> Aaaaaaand, nevermind. I see you're returning it and saving over the global one when you catch the call.
> 
> https://github.com/IGS/gEAR/blob/ui-v2/www/js/expression.js#L474

LOL, yep... trying to return a value rather than manipulate the global variable directly and potentially lead to unexpected results and debugging.
