### ISSUE TITLE
Staging gEAR-SVG not fitting in the result window

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#822]
@adkinsrs @JPReceveur 
Many of the SVG do not fit in the window. Below are few examples.
![image](https://github.com/user-attachments/assets/320f75fd-a29c-44f0-9aa8-e3b2aff428b2)
![image](https://github.com/user-attachments/assets/37df0180-72be-4679-9039-b912d57c5113)
![image](https://github.com/user-attachments/assets/0a54932c-9e59-43a2-bb6d-42c1444d2e62)

**Comment by adkinsrs** [comment]
I can replicate this but I think it's more an issue with how the SVG was submitted to us. I worry that if I make changes to get these to fit in the tile window, the good SVGs will be messed up.

**Comment by DanLesperance** [comment]
It also might be the default panel layout.  @beamilon can you send me the dataset collections these were found in.  I'll make the arrangement so that hopefully these images show up better

**Comment by beamilon** [comment]
@DanLesperance 
Listed is where the above ones were found but there are many more:
- E12.5-P30, mouse, scRNA-seq, endolymphatic sac (Griffith) in Development
- The Adult Cochlea Response to PTS-Inducing Noise – Summary View (24h time point, vector graphic) in NIHL, cell type-specific transcriptomics, mouse cochlea (Hertzano 2021)
- scRNA-Seq of all principal neonatal cochlear cell groups,cell type,svg (Heller) in scRNA-seq - P2 cochlea (Heller 2021)

**Comment by adkinsrs** [comment]
The old version of gEAR had some bad CSS styling on the SVGs that caused a few to go out of their box there (such as E16.5, P0, mouse, RNA-seq, cochlear and vestibular sensory epithelium (Avraham) ). That CSS was going to be problematic with the current version of gEAR

But I will try to come up with a CSS fix for this.

**Comment by adkinsrs** [comment]
<img width="402" alt="Screenshot 2024-07-25 at 2 44 03 PM" src="https://github.com/user-attachments/assets/a65baa96-b7e7-49f6-ba83-f2f9c5ec2316">

<img width="411" alt="Screenshot 2024-07-25 at 2 44 29 PM" src="https://github.com/user-attachments/assets/57e5c1f8-fc5c-4f91-ac06-c4650e73e5b3">

<img width="417" alt="Screenshot 2024-07-25 at 2 44 44 PM" src="https://github.com/user-attachments/assets/93d4802b-1196-4888-a7ad-98f52290bcd2">

These will now fit in the container.  However if the SVG had a lot of whitespace around the main graphic, that will also be preserved, and there's nothing much I can do for that unless edit the SVG file directly.

**Comment by jorvis** [comment]
We don't have that many SVGs, so if any do prove to have a lot of whitespace around them we need to trim it.  I've tried to do this for any I've worked on so just let me know if you find others.
