### ISSUE TITLE
Staging gEAR-Several graphs (other than SVG) do not fit in the boxes

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#825]
@adkinsrs @JPReceveur
Several datasets have graphs that go over the bottom of the result window. It is often less noticeable than for SVGs but it is pretty frequent.
One example below.
![image](https://github.com/user-attachments/assets/35e1a4f4-39b7-4c98-adc1-9e29c0eb1aa1)

**Comment by beamilon** [comment]
There are many of them. It was never a problem with the previous version of gEAR.
The one above is Noise/Damage/Protection

- Adult profile: P7-adult, mouse, RNA-seq, medial geniculate and primary auditory cortex (A1) (Hackett)
- Central auditory system: P7-adult, mouse, RNA-seq, medial geniculate and primary auditory cortex (A1) (Hackett)
- Development: P3, 8 wko, mouse, microarray, cochlear sensory epithelium (Zine); P5, P18, mouse, microarray, over-expression of miRNA cluster (Mir183, Mir96, Mir182 (Tg1MDW)) in the cochlea and organ of Corti (OC) vs WT (Soukup)
- Ear (diverse variety): P1, mouse, scRNA-seq, cochlea, hair cells, supporting cells, and non sensory cells (Kelley); P1, mouse, scRNA-seq, utricle, hair cells, supporting cells, and transitional epithelial cells (Kelley)

I am going through the profiles and there are some in almost every profiles so there is no point in listing everything

**Comment by adkinsrs** [comment]
The old version of gEAR also had some bad CSS styling on the SVGs that caused a few to go out of their box there (such as E16.5, P0, mouse, RNA-seq, cochlear and vestibular sensory epithelium (Avraham) )

But I will try to come up with a CSS fix for this.

**Comment by adkinsrs** [comment]
<img width="790" alt="Screenshot 2024-07-25 at 11 20 38 AM" src="https://github.com/user-attachments/assets/4a03aebb-1630-4f23-b0a0-d2601ebb1f6f">
<img width="392" alt="Screenshot 2024-07-25 at 11 21 07 AM" src="https://github.com/user-attachments/assets/47a0f099-1ca9-4733-8a76-266b91e09b46">

@beamilon I am not seeing this with some of the datasets you have linked, though I am seeing it with the Noise/Damage Protection examples. Again, I think I just need to have the dataset title render before the plot is rendered, and that may shrink the plot to fit the boundaries.

**Comment by beamilon** [comment]
@adkinsrs 
The first two in your screenshot are extending below the box. It is not by a lot but the bottom edge of the box is not visible because it is covered by the graph.

**Comment by adkinsrs** [comment]
Oh I see now.

**Comment by adkinsrs** [comment]
<img width="1814" alt="Screenshot 2024-07-25 at 2 22 35 PM" src="https://github.com/user-attachments/assets/08a24a88-dd6d-4df9-8780-3a716b4960f7">

Closing this ticket, and going to focus on the SVG stuff in the other ticket
