### ISSUE TITLE
Staging gEAR-2 profiles have strange layouts

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#826]
@adkinsrs 
scRNA-seq - Chicken basilar papilla (Heller 2021) and scRNA-seq - P2 cochlea (Heller 2021) have strange layouts.
![image](https://github.com/user-attachments/assets/dcc7c8e7-bd48-472d-84d4-87cc18408f3e)
![image](https://github.com/user-attachments/assets/fd256baf-7a4a-4211-84d9-988b85d64d0a)

**Comment by adkinsrs** [comment]
This is probably due to the automatic conversion of layout dataset members to layout display members. I would recommend that someone goes into the data set Explorer tool and corrects the layout arrangements how they want them

**Comment by DanLesperance** [comment]
I'll spend time tomorrow and go through a lot of the curator public profiles and ensure the arrangements look appropriate.

**Comment by adkinsrs** [comment]
Thanks. And the layout arranger gives you any grief, I can do it in the database

**Comment by DanLesperance** [comment]
After some discussion I will wait until Monday when everything is in Production to alter the layouts, as changes in staging won't be moved to Prod. I'll work on coalescing a list of profiles that need to be adjusted for Monday, starting with the site-curated ones.

**Comment by adkinsrs** [comment]
Technically the positions are correct on the displays.  However there are single-gene layout displays (such as a tsne/umap_dynamic created by curator on start column 1) that are not being retrieved. So the question is figure out why they are not being retreived (was this intentional?) then adjust the converter script to account for these scripts.

**Comment by adkinsrs** [comment]
I think what may be happening, and I need to investigate, is that when database entry with the same grid position ID is booted when retrieving layout members.

**Comment by beamilon** [comment]
I went to gEAR v1 and actually datasets are missing from the scRNA-seq - P2 cochlea (Heller 2021).
The missing datasets are:
- scRNA-Seq of all principal neonatal cochlear cell groups,cell type,color_code (Heller)
- scRNA-Seq of all principal neonatal cochlear cell groups, violin, version2 (Heller)
- P1, mouse, scRNA-seq, cochlear epithelium (Kelley)
Below is the profile on gEAR v1
![image](https://github.com/user-attachments/assets/dcab8891-28eb-46d3-90e6-1eb258804321)

**Comment by adkinsrs** [comment]
Found out what the issue is!  I included layout displays from datasets where the dataset mark for removal flag is set to 1.

**Comment by adkinsrs** [comment]
Just fixed the converter script.  I do not want to wipe and reload the staging displays, but can confirm the layouts are now correct when I reload on my local copy of gEAR.  This means that when @jorvis updates production for v2, the converter script should correctly recreate the layouts.
