### ISSUE TITLE
Dataset Collections - Have quick linkout to projection page for datasets

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#828]
Had an intern under @brianherb ask me how to project for a dataset (found in the explorer page), which resulted in me showing him a hacky method of extracting the share_id out of the URL and pasting into the projection.html page.  I just realized the same hack would hold true for v2, so we should have a linkout there.  

Since the "eye" icon is devoted to linking to the expression page, I am thinking of just adding this to the "Analysis tools" dropdown, despite it not being an analysis tool in the nav menu per se.  I'm certainly open to thoughts on this.

**Comment by jorvis** [comment]
I think that's fine for now.  We may get a request later to move it out to its own button.

**Comment by adkinsrs** [comment]
I considered that out was concerned about too many buttons

**Comment by adkinsrs** [comment]
Added projection button to list of buttons. Made it match the left navbar icon, and changed the expression button to match the left navbar icon as well.
