### ISSUE TITLE
when i load a projection page link, all the profile frames load, but no images and no list of patterns

### ISSUE THREAD

**Issue by carlocolantuoni** [IGS/gEAR#830]

**Comment by carlocolantuoni** [comment]
if i enter a gene list and a data collection manually, this is not an issue, just if i use a preset link.

when using a link, the correct layout id appears in the address bar and frames for the correct datasets come up empty, but no images

and the Dataset Collection pulldown menu is not populated with the layout name in the link

**Comment by carlocolantuoni** [comment]
an example of a link i use:
http://nemoanalytics.org/p?p=p&l=NeocortexDevoHsInVitro&c=CellCycleGenes.Seurat&algo=pca

**Comment by adkinsrs** [comment]
I just realized the cloud run URL was not configured in the config file.  Can you try again?

**Comment by adkinsrs** [comment]
So @carlocolantuoni, it's worth noting that your URL does not have any patterns selected (`&projection_patterns=`), so projectR doesn't know what weight(s) to project on.

I need to write some extra code to grab the weights and use all of them (if multipattern_plots=1) if this value is not provided.

**Comment by carlocolantuoni** [comment]
is it possible this is only loading the 1st pattern? i only see the option to look at the 1st pattern when i load a projection link that should have many

**Comment by adkinsrs** [comment]
Let me fix that... I only had it load all patterns when multi was selected

**Comment by adkinsrs** [comment]
Addressed with [3ca8f6f](https://github.com/IGS/gEAR/commit/3ca8f6f6c1ca47acac09ddf8ad982914ac1df5c2)
 ·. Closing again

**Comment by carlocolantuoni** [comment]
thnx - it loads all the patterns now!
