### ISSUE TITLE
when i try to rename a dataset collection i get "Failed to rename collection"

### ISSUE THREAD

**Issue by carlocolantuoni** [IGS/gEAR#833]

**Comment by adkinsrs** [comment]
Confirmed in umgear.org as well

**Comment by adkinsrs** [comment]
Seems my `renameCollection` function from common.v2.js is missing.  Either it was never written or it was filtered out by a merge.  I swear this was working last week lol

**Comment by adkinsrs** [comment]
Resolved this

**Comment by jorvis** [comment]
The suspense!  What happened to it??

**Comment by adkinsrs** [comment]
Renamed to "renameDatasetCollection"
