### ISSUE TITLE
Expression page - include_members needs to be set false

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#842]
from @carlo in #840

on the projection page the "search for a pattern" menu loads quick, but on
the gene viewing page it is very slow to load the "quick search using gene
lists" menu

"shaun talking here"

gene-collection-selector.js->`fetchGeneCarts` has "includeMembers" default to true, but perhaps it should be set to false in expression.js and index.js. However, since I do not know why this was default true to begin with, I'd rather not tamper with it.

**Comment by adkinsrs** [comment]
I can also take this on, if needed

**Comment by jorvis** [comment]
This is super weird, as it WAS off for those pages, which is why we got the speed increase so dramatically.  It's up to you if you want to start it, I'm AFK doing family stuff for the next hour or so

**Comment by adkinsrs** [comment]
Should be resolved now.  Let me know if anything else is not right related to genecart speeds
