### ISSUE TITLE
Not able to add Pubmed ID to datasets -- edit metadata

### ISSUE THREAD

**Issue by DanLesperance** [IGS/gEAR#850]
When trying to edit a metadata that curator owns (also logged in as curator) I'm not able to edit the Pubmed ID

![Screenshot 2024-08-06 at 9 21 27 AM](https://github.com/user-attachments/assets/4bc1f2b3-ed50-4739-a484-be26eb2ba4d9)

**Comment by adkinsrs** [comment]
I can replicate on my machine and it seems to be the case with the GEO ID as well. It seems to disallow typing, clearing, etc.

**Comment by adkinsrs** [comment]
Give it a try again @DanLesperance .

**Comment by DanLesperance** [comment]
Am able to edit the info.  Thanks
