### ISSUE TITLE
problem setting newly curated views as default views

### ISSUE THREAD

**Issue by carlocolantuoni** [IGS/gEAR#852]
in curating views from several different datasets i am encountering this a problem that when i try to save the curated view as the default view, i get 2 pop-up messages. 1 tells me the data set was saved successfully, the second is "Something went wrong. Please contact the gEAR team and provide steps to reproduce." it appears the error only pertains to the setting of the view as default, because when i go look, the new view is indeed saved, but not as default. so then i set it to default manually, which appears to save fine, but when i load a data collection with that dataset in it the new default is not displayed. i can select it manually.

**Comment by adkinsrs** [comment]
Can replicate locally.

It looks like the display ID is being passed as the dataset ID option to the server, so I believe the options to save a default image are being passed in the wrong order.

**Comment by adkinsrs** [comment]
Resolved and deployed
