### ISSUE TITLE
it may be a bit confusing to have 2 different buttons with different text in different places on the same page that both go to the collection manager

### ISSUE THREAD

**Issue by carlocolantuoni** [IGS/gEAR#853]
and where can we upload new data in V2?
am i just missing the button somehwere?

**Comment by jorvis** [comment]
Can you clarify these locations from the ticket title?

And I mentioned a few days ago that the uploader wasn't ready in V2. I'm actively working on it.

**Comment by carlocolantuoni** [comment]
![image](https://github.com/user-attachments/assets/f7718049-0594-4c95-a5f9-713fe492083b)
i think the 1st link could be omitted
and sorry - forgot u were workin on the uploader

**Comment by jorvis** [comment]
I get what you're saying, and it was addressed in a few weekly meetings.  The idea was that the same thing supports multiple entry points, and this  works.  Happy to address in our next chat.

**Comment by carlocolantuoni** [comment]
maybe when the uploader arrives its button could replace the 1st of the collection manager buttons
