### ISSUE TITLE
errors from projections that have run successfully in the past

### ISSUE THREAD

**Issue by carlocolantuoni** [IGS/gEAR#856]
i am getting many of the "Could not create projection AnnData object from CSV." errors when requesting projections that i have seen already in the past, but which now are returning the error.

for this projection EVERY datasets shows the error:
https://nemoanalytics.org/projection.html?projection_algorithm=pca&multipattern_plots=0&projection_source=f61159d5&layout_id=ChenowethEtAl2024&projection_patterns=FC

in this projection many show the same error:
https://nemoanalytics.org/projection.html?projection_algorithm=pca&multipattern_plots=0&projection_source=f61159d5&layout_id=c33d33d5&projection_patterns=FC

**Comment by adkinsrs** [comment]
Looks like my edit to #847 is making the code look for h5ad files (which is not present) instead of the CSV file (which is present).  Investigating now

**Comment by adkinsrs** [comment]
links show dataset projections now

**Comment by carlocolantuoni** [comment]
awesome - good on my end too - thanks!
