### ISSUE TITLE
is it possible to edit existing curated views?

### ISSUE THREAD

**Issue by carlocolantuoni** [IGS/gEAR#859]
i only see delete and clone, no edit option

**Comment by adkinsrs** [comment]
No, the idea is that you would clone an existing view, make your edits, and save a new one.  Given that there are user and owner curations, I decided it would be easier to keep the logic consistent, and save as a new curation.  You always have the option to delete the previous edit if you own the curation.

**Comment by carlocolantuoni** [comment]
got it - ok thnx

**Comment by carlocolantuoni** [comment]
hi shaun - there are a few instances when editing would save a ton of work - for example if i have a view of a particular dataset in several data collections, if i want to simply remove the individual points from a violin plot, i have to clone the view, then go to each data collection individually, delete the old view and add a new view and then place it in the arrangement where it used to be. how hard would it be to add the edit back in?

**Comment by adkinsrs** [comment]
I can probably add a checkbox called "overwrite existing display" or something similar that will overwrite the cloned display (basically checking if a display ID is already present in the code).

**Comment by carlocolantuoni** [comment]
that would be great if it enable editing an existing display and is not too much work on your end
