### ISSUE TITLE
set a profile as public

### ISSUE THREAD

**Issue by songeric1107** [IGS/gEAR#86]
Josh

could you please make this profile as public?

https://umgear.org/p?l=dc7aaabf

could you also change the profile name from "scRNAseq-Dr.Liu" to "scRNA-seq - IKZF2-transduced adult SCs (Liu 2021)"?

#85

**Comment by songeric1107** [comment]
hold this ticket.

**Comment by songeric1107** [comment]
Josh, please go ahead set this profile as public with the name change as above. Thank you

**Comment by jorvis** [comment]
OK, this is done.
