### ISSUE TITLE
searching genes by cell type

### ISSUE THREAD

**Issue by gear-portal-team** [IGS/gEAR#867]
**From:** Dimitri Traenkner

**Email:** dimitri.trankner@gmail.com

**Server IP:** 10.142.0.16

**Msg:** Hello, I understand how I can check cell types for the expression of single or few genes. How do I do the reverse, i.e., collect all genes expressed in a given cell type (by organ, species, age)? I could not find help with that using the given resources. Sincerely, Dimitri Traenkner, University of Utah  

**Tags:** ['']

**Screenshot:** None

**Comment by adkinsrs** [comment]
Right now the only ways I can think of are "comparison ways" like the compare tool, or the volcano plot, where you would compare two cell types.  But then you are doing an unnecessary comparison if you only just want one cell type instead of two

**Comment by JPReceveur** [comment]
Responded to user: 

Hello Dimitri,
Thank you for your email. For finding genes expressed at higher levels in a given cell type compared to other cells types or other combinations of metadata, your best option will likely be to use the compare tool under the analysis heading. In the data filters, you can select comparisons of interest such as comparing individual cell types against all other cell types in a dataset. Once you create a comparison plot, you can download the list of genes (or save them as a gene list for use elsewhere on the gEAR site.

**Comment by adkinsrs** [comment]
@JPReceveur is this closable?
