### ISSUE TITLE
load time on large data collections

### ISSUE THREAD

**Issue by carlocolantuoni** [IGS/gEAR#868]
***i will work to break my giant data collections up into more digestable collecitons. i also think its worth a look at how data is being moved given the drop in performance from the older version:

i have some concerns about load times - especially for specific large dataset collections eg:

https://nemoanalytics.org/p?p=p&l=Kim2024&c=Kim2024_GWCoGAPS_I_p24&algo=nmf
above projection link took many minutes to load and then had many "Request failed with status code 500" - another time i couldnt get it to load at all.

https://nemoanalytics.org/p?l=Kim2024&g=GBX2
above gene link never loads

is the architecture of how data is being moved different than V1? i think i have made things worse by making such large data collections for sure (i will try to reduce), but in V1 these large data collections loaded quicker and without error.

**Comment by carlocolantuoni** [comment]
a note- i have been looking at several other data collections that are much larger in number of datasets and number of samples per dataset and they load much faster/more stably - maybe there is a problem with 1 or more datasets in particular in the slow loading data collection (l=Kim2024)?

**Comment by carlocolantuoni** [comment]
could it be a problem specific to this collection -  looking at the collection arrangement view for l=Kim2024: the datasets take a very long time to populate the collection arrangement view - this is one of the profiles i was trying to edit where i created tons of unintended duplicates - i thought i deleted them all, but if i left many that are under one another this might be a problem - can you check if i left lots of dups?

**Comment by carlocolantuoni** [comment]
i think thats it - there are :

48 instances of "Reference maps of human ES and iPS cell variation enable high-throughput characterization of pluripotent cell lines (Bock et al 2011)"

32 of "Bulk H3K9me3 ChIP-seq in lines 2053-2 and 2053-6 from donor 2053 (Kim et al 2024)"

48 of "Gene-summarized DNA methylation data from undifferentiated hPSC lines (Kim et al 2024)"

48 of 1 particular view of "MmGastr116Ksc_AllCellTypes.DownSamp12k: Single-cell RNAseq from gastrulating mouse embryo (Pijuan-Sala et al 2019)"

48 of "E6.50 mouse gastrula"

48 of "E7.00 mouse gastrula"

i think i will stop enumerating now bt there are many more i think - looks like a 48 x duplication happened to a lot of the datasets. can you see and remove all these dups? could you delete down to 1 for any dataset with >2 views saved? i dont think i had multiples of any and will add if i need em.

sorry guys i could not see that i was generating all these - i deleted the ones i could see graphically, bt did not relaize there were so many left - think getting rid of the many dups should help a lot!

**Comment by carlocolantuoni** [comment]
of cirse this is related to: [#768](https://github.com/IGS/gEAR/issues/768)

**Comment by carlocolantuoni** [comment]
also related to #797

**Comment by adkinsrs** [comment]
Not related to #797.  But the profiles have been de-duplicated so I am closing this ticket.

For reference what was happening, I believe, was whenever you added a display to a layout, a certain server-side call was called twice, which could retrieve the layout members twice, hence the duplication.  Now they were only duplicated in the browser, but once "save layout" was clicked, then it was locked in.  Then the cycle repeated when adding new displays and saving.  Once again, though, it should be resolved now as I removed the extra server-side call.
