### ISSUE TITLE
unable to make static tSNE and UMAP plots - because of meta data colnames?

### ISSUE THREAD

**Issue by carlocolantuoni** [IGS/gEAR#876]
for dataset:
https://nemoanalytics.org/p?s=9bc879ac

i am unable to make any tSNE or UMAP plots - is this because of an automatic colname check? i dont have any meta data with "tSNE" or "UMAP" in them, we use "Embeddings"

**Comment by carlocolantuoni** [comment]
also happening for this dataset where we just use X and Y:
https://nemoanalytics.org/p?s=088e1a9a

can we turn off the auto check? or is that not the prob here?

**Comment by adkinsrs** [comment]
Yes, currently the tSNE/UMAP/PCA static plots require that name in the "available display types" section.  However, since we now have the ability to rename axis labels within the plot, I can make this adjustment.

**Comment by adkinsrs** [comment]
Works now.

**Comment by carlocolantuoni** [comment]
Awesome!  Thanks shaun
