### ISSUE TITLE
Plotly - Some plots throw error when making a new dataframe column

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#878]
`Encountered error: Cannot set a DataFrame with multiple columns to the single column y_rounded`

Follow-up to #873.

The "y_rounded" column was made to use in hover text situations where we want to show only two sigfigs of precision when hovering over a plot.

**Comment by carlocolantuoni** [comment]
context where i saw it:

for dataset "HIV infection and anti-retroviral treatment (ART) in cerebral organoids containing microglia." in this projection link i am getting "Encountered error: Cannot set a DataFrame with multiple columns to the single column y_rounded":
https://nemoanalytics.org/p?p=p&algo=pca&c=fc5b3499&l=623b2c0a

**Comment by adkinsrs** [comment]
https://anndata.readthedocs.io/en/latest/generated/anndata.AnnData.to_df.html#anndata.AnnData.to_df

When converting from AnnData to DataFrame, the adata.var_names (index) values were being used, and for projections, I set these equal to the weights.  So I just needed to rename the chosen weight value before converting to dataframe rather than after

**Comment by carlocolantuoni** [comment]
good sleuthing!
