### ISSUE TITLE
gene list long description doesn't save when creating list

### ISSUE THREAD

**Issue by carlocolantuoni** [IGS/gEAR#879]
i can come back later and add it and it saves, but when i create a new gene list it does not save the long description

**Comment by adkinsrs** [comment]
I can confirm.  Saving new gene list does not save the ldesc to the database, despite being passed into the server-side payload. Thought I had a former ticket for this, but it seems it was not made (perhaps was discussed over chat)

**Comment by adkinsrs** [comment]
Found the "save" command in geardb.py did not include the "ldesc" field.  Fixed that and confirmed it works now. Closing

**Comment by carlocolantuoni** [comment]
👍👍👍
