### ISSUE TITLE
Expand icon and 3 dots icon outside the result windows in Regenerating Neuromast (Piotrowski)

### ISSUE THREAD

**Issue by beamilon** [IGS/gEAR#881]
@adkinsrs 
In the Regeneration Neuromast profile, the expand icons and 3 dots are not aligned with the result window.
![image](https://github.com/user-attachments/assets/68a142f6-6527-4a54-bba7-a45460e41b91)

**Comment by adkinsrs** [comment]
Odd... I've never seen this.

Can you do a hard-refresh on your browser (Ctrl-Shift-R) to ensure any previous cached stylings are cleared.

**Comment by jorvis** [comment]
My guess it's because each of those seems to have that very long string with no spaces so it can't word wrap properly.

**Comment by adkinsrs** [comment]
I tried messing around with padding and margin settings and it just pushes the icons further to the right.  We could have CSS to wrap on any letter, but that would uglify other datasets that word wrap just fine.

I wonder if I can do assign the title element a max-width with a calculation to subtract the width of the icon containers

**Comment by jorvis** [comment]
I'm also up for just fixing the titles.  :)

**Comment by adkinsrs** [comment]
Yea, let's go that route.  Occam's Razor

**Comment by beamilon** [comment]
I will add spaces in the titles.
I googled Occam's Razor :)

**Comment by beamilon** [comment]
Fixed!
