### ISSUE TITLE
Single-cell workbench: Primary analysis fails to load

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#897]
This is one of the most common datasets we use to during demos and currently simply loading the primary analysis failed when we just did our demo:

https://umgear.org/sc_workbench.html?dataset_id=c4f16a12-9e98-47be-4335-b8321282919e

**Comment by adkinsrs** [comment]
Got an "invalid session_id" error in the get_stored_analysis.cgi script

**Comment by adkinsrs** [comment]
Oh I see, session_id is null.  I had made some changes to pass the correct session id to public and saved analyses and it seems I broke primary ones

**Comment by adkinsrs** [comment]
Fixed, and waiting for a pull to the server.  Session IDs were properly populated for non-primary analyses but for the primary one, it was not returned in the CGI script to get all analyses, and so the "null" was passed along (and used).
