### ISSUE TITLE
Downloading datasets from gEAR

### ISSUE THREAD

**Issue by colewoulbroun** [IGS/gEAR#898]
Hello, I'm looking for guidelines on downloading a full dataset from gEAR.  I've downloaded one dataset from the 'Gene Expression Search' page, but I haven't been able to access the others I'm looking for, even though I see them on the 'Dataset Explorer Page'.  Are there instructions for downloading any dataset that's been uploaded to gEAR?

**Comment by adkinsrs** [comment]
<img width="1111" alt="Screenshot 2024-09-20 at 10 12 18 AM" src="https://github.com/user-attachments/assets/a0905cb3-6f83-45ea-ae3b-3834e9043c63">

This is possible to do in the Dataset Explorer.  If the dataset is downloadable (indicated by tags on the left), there is a "download" arrow in the quick actions menu after click the "List View - Compact" button at the top of the results.  Reasons the dataset may not be downloadable include if the dataset does not have an underlying h5ad file to download, or if the dataset owner has indicated that their dataset should not be downloadable.

**Comment by adkinsrs** [comment]
There are also instructions for how to download a dataset in gEAR found here -> https://github.com/IGS/gEAR/wiki#downloading-data

However, do note that the screenshots are largely for the outdated v1 version of gEAR

**Comment by jorvis** [comment]
Closing this.  @colewoulbroun please re-open if this didn't get you what you needed.
