### ISSUE TITLE
Change "gEAR" to say "NeMO" on NeMO Analytics

### ISSUE THREAD

**Issue by echrysostomou84** [IGS/gEAR#9]
![image](https://user-images.githubusercontent.com/59666680/124808961-93230400-df2d-11eb-8fbd-4ad6aee2fe32.png)
![image](https://user-images.githubusercontent.com/59666680/124809221-de3d1700-df2d-11eb-9fb6-e72b698866cb.png)

For the uploader and in the dataset explorer delete button

**Comment by jorvis** [comment]
Fixed, but not yet exported.  I also found and fixed references to gEAR specifically within the workbench.
