### ISSUE TITLE
Specifying a custom annotation in metadata results in dataset load fail

### ISSUE THREAD

**Issue by JPReceveur** [IGS/gEAR#901]
During dataset upload, if a custom annotation source is selected, and a value is inputted that doesn't correspond with one of the regular values for this field, the metadata page lets you proceed. However, when you get to the finalize dataset step, the submission fails since the value isn't an integer. 

Error saving metadata to MySQL: Failed to insert metadata: 1366 (HY000): Incorrect integer value: 'mm10 and GRCm38.vM23' for column 'annotation_release' at row 1

**Comment by jorvis** [comment]
For any exiting instances:

ALTER TABLE dataset MODIFY annotation_release VARCHAR(25);

**Comment by jorvis** [comment]
I have updated the dataset.annotation_release field on gear-prod, gear-devel and nemo-prod from int to varchar(25).

Let me know Joe if this doesn't fix it for you and re-open.
