### ISSUE TITLE
upload Rdata/Seurat not yet available

### ISSUE THREAD

**Issue by gaze-abyss** [IGS/gEAR#905]
Dear,

I want to upload some Rdata of scRNA-seq to gear, but I can't choose this type.
Please tell me what is the reason for this.
Thank you very much!
![16c795449195449c4d4ab0d7e4e5b8e](https://github.com/user-attachments/assets/a1c29cea-f291-42c7-a93f-7bfa58379234)

**Comment by jorvis** [comment]
It isn't available yet because it's a feature under development and not yet available.  Currently you'll need to export your matrix and metadata from the Seurat object and into the 3-tab or MEX format to import.
