### ISSUE TITLE
Issue with dataset column type guessing by Scanpy (Carlo's 

### ISSUE THREAD

**Issue by jorvis** [IGS/gEAR#917]
Error message scanpy gives:

```
TypeError: Can't implicitly convert non-string objects to strings
Error raised while writing key 'Gestational_week' of <class 'h5py._hl.group.Group'> to /obs
```

Looking into the data, from @carlocolantuoni:

"There are 23 unique values in the   "Gestational_week" metadata field, 22 are integers and then there is a text value: "postnatal"
cold it be that the code it auto detecting the column as an integer by checking some subset of the values and then getting tripped up later when it finds the text? If so, would it be possible to do the auto check on the unique values rather than all indiv values so this would get caught?"

**Comment by carlocolantuoni** [comment]
great! so is the original dataset processing now (i cant see it in the Dataset Explorer yet)?

**Comment by jorvis** [comment]
(E-mailed with more info)
