### ISSUE TITLE
Dataset Explorer - Table View entries expand into full-size 

### ISSUE THREAD

**Issue by adkinsrs** [IGS/gEAR#939]
Would be like the "compact list" view but for single datasets.  Accordion style

**Comment by adkinsrs** [comment]
This should also happen for the Gene List Manager page too

**Comment by adkinsrs** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

Can use this

**Comment by adkinsrs** [comment]
I think the strategy would be to have an "expand" button at the left.  It would create a new <tr> with a single <td> that has a full colspan, and this would include the list view result.  So no "detail" tag needed (which wouldn't work in HTML unless you add inside a <td>

**Comment by adkinsrs** [comment]
Dataset Explorer done.  Gene List Manager up next.

**Comment by adkinsrs** [comment]
Reopening as I will put this in gear-devel and plan to have @JPReceveur and/or @DanLesperance test changes

**Comment by adkinsrs** [comment]
TODO: Fix bug where if you are **not** logged in, the "Show from this collection only" toggle still shows (not supposed to view dataset collections if logged out)

**Comment by DanLesperance** [comment]
Tested both gene list manager and dataset collection.  Have not noticed any bugs.  Will report if I see any.
